import json

questions = []

def add_q(id_num, topic, q, opts, ans, exp_corr, exp_a, exp_b, exp_c, exp_d):
    qid = f"JB-{id_num:03d}"
    questions.append({
        "id": qid,
        "level": "beginner",
        "topic": topic,
        "question": q,
        "options": opts,
        "answer": ans,
        "explanation": {
            "correct": exp_corr,
            "A": exp_a,
            "B": exp_b,
            "C": exp_c,
            "D": exp_d
        }
    })

# Java Core Basics (51 to 70: 20 questions)
add_q(51, "Java Core", 
      "Apa perbedaan mendasar antara String, StringBuilder, dan StringBuffer di Java?",
      {"A": "String bersifat immutable, StringBuilder mutable non-thread-safe, dan StringBuffer mutable thread-safe",
       "B": "String dapat diubah langsung di memori, sedangkan StringBuilder selalu membuat objek baru",
       "C": "StringBuffer lebih cepat daripada StringBuilder dalam aplikasi single-thread",
       "D": "Ketiganya memiliki performa dan thread-safety yang persis sama"},
      "A",
      "String bersifat immutable (nilainya tidak dapat diubah setelah dibuat). StringBuilder bersifat mutable dan lebih cepat untuk single-thread karena tidak ada sinkronisasi, sedangkan StringBuffer bersifat mutable dan thread-safe karena method-methodnya tersinkronisasi.",
      "Opsi A benar karena mendefinisikan karakteristik mutabilitas dan thread-safety masing-masing kelas secara tepat.",
      "Opsi B salah karena String justru immutable, bukan mutable.",
      "Opsi C salah karena StringBuffer memiliki overhead sinkronisasi sehingga lebih lambat dari StringBuilder pada single-thread.",
      "Opsi D salah karena ketiganya memiliki karakteristik thread-safety dan mutabilitas yang berbeda.")

add_q(52, "Java Core",
      "Manakah dari interface berikut yang merupakan bagian dari Java Collections Framework?",
      {"A": "List, Set, Map, dan Queue",
       "B": "Array, Vector, String, dan Matrix",
       "C": "Thread, Runnable, Callable, dan Future",
       "D": "InputStream, OutputStream, Reader, dan Writer"},
      "A",
      "Interface inti pada Java Collections Framework meliputi Collection (diwarisi oleh List, Set, Queue) serta Map (sebagai pemetaan key-value).",
      "Opsi A benar karena mencantumkan interface utama dalam Java Collections Framework.",
      "Opsi B salah karena Array bukan interface melainkan tipe struktur data dasar, dan String bukan koleksi.",
      "Opsi C salah karena merupakan interface dalam Java Concurrency API, bukan Collections.",
      "Opsi D salah karena merupakan kelas-kelas dalam Java I/O Stream API.")

add_q(53, "Java Core",
      "Apa kegunaan utama dari keyword 'static' pada variabel atau method di Java?",
      {"A": "Membuat variabel atau method menjadi milik kelas secara global tanpa perlu instansiasi objek",
       "B": "Mencegah variabel atau method agar nilainya tidak dapat diubah lagi",
       "C": "Membuat method otomatis berjalan di thread terpisah",
       "D": "Menjadikan variabel hanya dapat diakses di dalam package yang sama"},
      "A",
      "Keyword static menandakan bahwa member (variabel atau method) tersebut milik class itu sendiri, bukan milik instance/objek tertentu, sehingga dapat dipanggil langsung melalui ClassName.methodName().",
      "Opsi A benar karena menjelaskan konsep class-level member milik keyword static.",
      "Opsi B salah karena mencegah perubahan nilai adalah fungsi dari keyword final.",
      "Opsi C salah karena eksekusi multi-threading dilakukan dengan Thread atau ExecutorService.",
      "Opsi D salah karena pembatasan akses package adalah fungsi dari default (package-private) access modifier.")

add_q(54, "Java Core",
      "Apakah yang dimaksud dengan checked exception di Java?",
      {"A": "Exception yang wajib ditangani dengan try-catch atau dideklarasikan dengan throws saat kompilasi",
       "B": "Exception yang terjadi karena bug logika program seperti NullPointerException",
       "C": "Error fatal pada level JVM seperti OutOfMemoryError",
       "D": "Exception yang hanya terjadi pada runtime dan diabaikan oleh compiler"},
      "A",
      "Checked exception adalah subclass dari Exception (kecuali RuntimeException) yang diverifikasi saat compile-time; programmer wajib menanganinya menggunakan try-catch atau mendeklarasikannya di klausul throws.",
      "Opsi A benar karena checked exception diperiksa saat kompilasi dan wajib ditangani.",
      "Opsi B salah karena NullPointerException adalah unchecked exception (turunan RuntimeException).",
      "Opsi C salah karena OutOfMemoryError adalah subclass dari Error, bukan checked Exception.",
      "Opsi D salah karena exception yang diabaikan saat compile-time adalah unchecked exception.")

add_q(55, "Java Core",
      "Apa hasil dari operasi perbandingan 'new String(\"test\") == new String(\"test\")' di Java?",
      {"A": "false, karena operator '==' membandingkan alamat referensi memori dari kedua objek baru",
       "B": "true, karena isi teks string keduanya identik",
       "C": "Compile error karena operator '==' tidak dapat digunakan untuk objek",
       "D": "NullPointerException karena String baru belum memiliki hashcode"},
      "A",
      "Operator '==' pada objek di Java membandingkan kesamaan referensi memori (memory address). Karena keyword 'new' mengalokasikan objek baru di heap, kedua referensi berbeda sehingga hasilnya false. Untuk membandingkan nilai konten, gunakan .equals().",
      "Opsi A benar karena operator == memeriksa referensi objek bukan konten teks.",
      "Opsi B salah karena operator == tidak membandingkan kesetaraan isi teks string.",
      "Opsi C salah karena operator == valid digunakan untuk membandingkan referensi objek.",
      "Opsi D salah karena string instansiasi valid dan tidak bernilai null.")

add_q(56, "Java Core",
      "Prinsip OOP manakah yang menyembunyikan detail internal objek dan hanya menyediakan akses melalui getter/setter?",
      {"A": "Encapsulation (Enkapsulasi)",
       "B": "Inheritance (Pewarisan)",
       "C": "Polymorphism (Polimorfisme)",
       "D": "Abstraction (Abstraksi)"},
      "A",
      "Encapsulation adalah teknik membungkus data (field) menjadi private dan mengontrol akses terhadapnya melalui public method (getter/setter) demi menjaga integritas data objek.",
      "Opsi A benar karena pembungkusan field dan proteksi akses adalah definisi enkapsulasi.",
      "Opsi B salah karena inheritance adalah mekanisme pewarisan sifat dari parent class ke subclass.",
      "Opsi C salah karena polymorphism memungkinkan objek memiliki banyak bentuk implementasi method.",
      "Opsi D salah karena abstraksi lebih berfokus pada menyembunyikan kompleksitas implementasi menggunakan interface atau abstract class.")

add_q(57, "Java Core",
      "Manakah pernyataan yang benar mengenai method overriding di Java?",
      {"A": "Subclass mendefinisikan ulang method yang ada di superclass dengan nama, return type, dan parameter yang sama persis",
       "B": "Satu kelas memiliki beberapa method dengan nama yang sama namun parameter berbeda",
       "C": "Method di superclass harus memiliki keyword 'final' agar bisa di-override",
       "D": "Overriding dilakukan saat compile time menggunakan static binding"},
      "A",
      "Method overriding terjadi saat subclass mengimplementasikan kembali method milik superclass dengan nama, return type (atau covariant), dan parameter yang persis sama. Ini merupakan contoh runtime polymorphism.",
      "Opsi A benar karena menjelaskan aturan method overriding.",
      "Opsi B salah karena pendefinisian method bernama sama dengan parameter berbeda adalah overloading.",
      "Opsi C salah karena method final justru dilarang untuk di-override.",
      "Opsi D salah karena overriding dievaluasi secara dinamis saat runtime (dynamic dispatch).")

add_q(58, "Java Core",
      "Blok kode apakah yang selalu dieksekusi setelah blok try-catch, baik terjadi exception maupun tidak?",
      {"A": "finally",
       "B": "catch-all",
       "C": "final",
       "D": "default"},
      "A",
      "Blok finally selalu dijalankan setelah blok try atau catch selesai dieksekusi, sangat umum digunakan untuk membersihkan resource seperti menutup koneksi database atau file stream.",
      "Opsi A benar karena finally dijamin dieksekusi dalam alur penanganan exception.",
      "Opsi B salah karena catch-all bukan keyword Java.",
      "Opsi C salah karena final adalah modifier untuk variabel, method, atau class.",
      "Opsi D salah karena default digunakan pada switch-case atau interface method.")

add_q(59, "Java Core",
      "Apa fungsi utama dari garbage collection (GC) pada Java Virtual Machine (JVM)?",
      {"A": "Secara otomatis membebaskan memori heap dari objek yang sudah tidak memiliki referensi aktif",
       "B": "Menghapus file temporary yang dibuat di sistem operasi",
       "C": "Mengompilasi bytecode Java menjadi kode mesin native",
       "D": "Memastikan tidak ada duplikasi data di dalam database"},
      "A",
      "Garbage Collector (GC) adalah modul otomatis pada JVM yang bertugas mendeteksi dan menghapus objek-objek di memori heap yang sudah tidak dapat dijangkau (unreachable) oleh aplikasi.",
      "Opsi A benar karena mendeskripsikan fungsi pembersihan memori objek oleh GC.",
      "Opsi B salah karena GC bekerja pada memori heap JVM, bukan file sistem operasi.",
      "Opsi C salah karena kompilasi bytecode ke machine code dilakukan oleh Just-In-Time (JIT) Compiler.",
      "Opsi D salah karena GC tidak berhubungan dengan database.")

add_q(60, "Java Core",
      "Manakah implementasi List yang memiliki performa penambahan elemen di awal daftar paling efisien (O(1))?",
      {"A": "LinkedList",
       "B": "ArrayList",
       "C": "Vector",
       "D": "CopyOnWriteArrayList"},
      "A",
      "LinkedList diimplementasikan sebagai doubly-linked list, sehingga penyisipan atau penghapusan elemen di awal list (head) berkecepatan konstan O(1) tanpa perlu menggeser elemen lainnya.",
      "Opsi A benar karena LinkedList hanya memanipulasi pointer node kepala.",
      "Opsi B salah karena ArrayList berbasis array kontinu yang harus menggeser seluruh elemen (O(n)) saat menyisipkan di awal.",
      "Opsi C salah karena Vector berbasis array tersinkronisasi dan tetap membutuhkan pergeseran elemen O(n).",
      "Opsi D salah karena CopyOnWriteArrayList menyalin seluruh array saat mutasi (sangat lambat untuk penambahan terus-menerus).")

add_q(61, "Java Core",
      "Apa perbedaan utama antara abstract class dan interface di Java modern (Java 8+)?",
      {"A": "Abstract class dapat memiliki state (instance variable) dan konstruktor, sedangkan interface tidak memiliki instance variable",
       "B": "Interface sama sekali tidak boleh memiliki implementasi method apapun",
       "C": "Satu class dapat meng-extend lebih dari satu abstract class",
       "D": "Abstract class tidak boleh memiliki method konkret"},
      "A",
      "Abstract class dapat memiliki instance variable non-static dan constructor, serta mendukung single-inheritance. Interface (meskipun mendukung default dan static method sejak Java 8) hanya mengizinkan variabel public static final dan tidak memiliki state/constructor.",
      "Opsi A benar karena membedakan kepemilikan instance variable dan constructor.",
      "Opsi B salah karena sejak Java 8 interface dapat memiliki method konkret melalui default method dan static method.",
      "Opsi C salah karena Java tidak mendukung multiple inheritance untuk class.",
      "Opsi D salah karena abstract class boleh memiliki method konkret.")

add_q(62, "Java Core",
      "Manakah keyword yang digunakan untuk memanggil constructor dari superclass di dalam constructor subclass?",
      {"A": "super()",
       "B": "this()",
       "C": "parent()",
       "D": "base()"},
      "A",
      "super() digunakan untuk memanggil constructor superclass dari dalam constructor subclass, dan harus menjadi baris perintah pertama di constructor tersebut.",
      "Opsi A benar karena super() adalah sintaks resmi Java untuk constructor superclass.",
      "Opsi B salah karena this() memanggil constructor lain di dalam kelas yang sama.",
      "Opsi C salah karena parent bukan keyword dalam bahasa Java.",
      "Opsi D salah karena base adalah keyword bahasa C#, bukan Java.")

add_q(63, "Java Core",
      "Bagaimanakah urutan eksekusi blok inisialisasi ketika sebuah objek Java dibuat?",
      {"A": "Static initializer superclass -> static initializer subclass -> instance initializer superclass -> constructor superclass -> instance initializer subclass -> constructor subclass",
       "B": "Constructor subclass -> constructor superclass -> static initializer",
       "C": "Instance initializer subclass -> static initializer subclass -> constructor",
       "D": "Urutan acak tergantung penjadwalan thread JVM"},
      "A",
      "Saat class di-load, static block superclass dijalankan, diikuti static block subclass. Saat instansiasi objek, instance initializer dan constructor superclass dijalankan terlebih dahulu sebelum instance initializer dan constructor subclass.",
      "Opsi A benar karena merefleksikan urutan class loading dan object instantiation di JVM.",
      "Opsi B salah karena superclass selalu diinisialisasi sebelum subclass.",
      "Opsi C salah karena static initializer dijalankan saat class loading jauh sebelum instance dibuat.",
      "Opsi D salah karena urutan inisialisasi class dan objek bersifat deterministik di Java.")

add_q(64, "Java Core",
      "Koleksi Set manakah yang menjamin elemen tersimpan secara terurut berdasarkan urutan alami (natural ordering) atau Comparator?",
      {"A": "TreeSet",
       "B": "HashSet",
       "C": "LinkedHashSet",
       "D": "ConcurrentSkipListSet"},
      "A",
      "TreeSet mengimplementasikan NavigableSet berbasis Red-Black Tree, yang menjamin elemen-elemennya terurut menaik (ascending) secara alami (Comparable) atau berdasarkan Comparator kustom.",
      "Opsi A benar karena TreeSet menyortir elemen secara terurut otomatis.",
      "Opsi B salah karena HashSet tidak menjamin urutan elemen sama sekali.",
      "Opsi C salah karena LinkedHashSet hanya menjaga urutan penyisipan (insertion order), bukan natural ordering.",
      "Opsi D salah meskipun terurut dan concurrent, TreeSet adalah implementasi standar non-concurrent paling fundamental.")

add_q(65, "Java Core",
      "Apa fungsi dari method 'equals()' dan 'hashCode()' dalam kontrak (contract) objek Java?",
      {"A": "Jika dua objek bernilai sama menurut equals(), keduanya wajib menghasilkan hashCode() yang sama",
       "B": "Jika dua objek memiliki hashCode() yang sama, keduanya selalu bernilai sama menurut equals()",
       "C": "equals() hanya untuk String, sedangkan hashCode() untuk angka primitif",
       "D": "Keduanya tidak memiliki relasi atau dependensi apapun"},
      "A",
      "Kontrak equals dan hashCode menyatakan bahwa jika a.equals(b) bernilai true, maka a.hashCode() harus sama dengan b.hashCode(). Sebaliknya, dua objek dengan hashCode sama belum tentu equals (disebut hash collision).",
      "Opsi A benar karena menyatakan aturan mandatory dari Java Object contract.",
      "Opsi B salah karena hash collision memungkinkan objek berbeda menghasilkan hashCode yang sama.",
      "Opsi C salah karena keduanya adalah method class java.lang.Object untuk semua objek.",
      "Opsi D salah karena koleksi berbasis hash seperti HashMap bergantung mutlak pada konsistensi keduanya.")

add_q(66, "Java Core",
      "Manakah tipe data primitif berikut yang bernilai default 'false' ketika dideklarasikan sebagai field kelas?",
      {"A": "boolean",
       "B": "byte",
       "C": "char",
       "D": "Boolean"},
      "A",
      "Variabel tipe data primitif boolean yang dideklarasikan sebagai member class (field) akan otomatis diinisialisasi dengan nilai default 'false'.",
      "Opsi A benar karena default primitif boolean adalah false.",
      "Opsi B salah karena nilai default byte adalah 0.",
      "Opsi C salah karena nilai default char adalah '\\u0000'.",
      "Opsi D salah karena Boolean adalah wrapper class (objek) yang default-nya bernilai null.")

add_q(67, "Java Core",
      "Apa fungsi dari keyword 'transient' pada deklarasi variabel di Java?",
      {"A": "Menandai bahwa variabel tersebut tidak boleh disertakan saat proses serialisasi objek (Serialization)",
       "B": "Menandai bahwa variabel nilainya dapat diakses oleh beberapa thread secara langsung",
       "C": "Membuat variabel hanya bisa dibaca satu kali lalu terhapus otomatis",
       "D": "Menjadikan variabel sebagai konstanta global"},
      "A",
      "Keyword transient mencegah serialisasi suatu atribut objek saat objek dikonversi menjadi byte stream (misalnya saat disimpan ke file atau dikirim lewat network).",
      "Opsi A benar karena transient mengecualikan field dari serialisasi.",
      "Opsi B salah karena akses langsung dari main memory pada multithreading menggunakan keyword volatile.",
      "Opsi C salah karena Java tidak memiliki modifier seperti itu.",
      "Opsi D salah karena konstanta dibuat dengan public static final.")

add_q(68, "Java Core",
      "Bagaimana cara menangani resource seperti FileInputStream agar otomatis tertutup tanpa memanggil .close() secara manual di blok finally?",
      {"A": "Menggunakan sintaks try-with-resources (Java 7+)",
       "B": "Menambahkan anotasi @AutoClose pada variabel",
       "C": "Membiarkan Garbage Collector menutupnya saat objek dihancurkan",
       "D": "Menggunakan keyword synchronized pada blok try"},
      "A",
      "Try-with-resources memastikan semua resource yang mengimplementasikan java.lang.AutoCloseable akan otomatis ditutup di akhir blok try, bahkan ketika terjadi exception.",
      "Opsi A benar karena try-with-resources adalah standar penutupan resource otomatis di Java.",
      "Opsi B salah karena @AutoClose bukan anotasi resmi bawaan Java.",
      "Opsi C salah karena GC tidak menjamin penutupan file handle secara tepat waktu dan dapat menimbulkan resource leak.",
      "Opsi D salah karena synchronized untuk thread locking, bukan manajemen file resource.")

add_q(69, "Java Core",
      "Apakah perbedaan utama antara throw dan throws di Java?",
      {"A": "'throw' digunakan untuk melempar exception secara eksplisit di dalam method, sedangkan 'throws' digunakan di deklarasi method untuk menandai kemungkinan exception",
       "B": "'throws' digunakan untuk melempar exception objek, sedangkan 'throw' adalah blok penangkap",
       "C": "Keduanya sinonim dan dapat saling menggantikan",
       "D": "'throw' hanya untuk RuntimeException, sedangkan 'throws' hanya untuk Error"},
      "A",
      "Keyword throw diikuti oleh instance exception (misal: throw new IllegalArgumentException()), sedangkan throws ditulis pada signature method untuk menginformasikan pemanggil tentang checked exception yang mungkin muncul.",
      "Opsi A benar karena menjelaskan letak sintaks dan peruntukan masing-masing keyword.",
      "Opsi B salah karena penangkap exception menggunakan keyword catch.",
      "Opsi C salah karena throw dan throws memiliki fungsi dan posisi sintaks berbeda.",
      "Opsi D salah karena throw dapat melempar semua turunan Throwable.")

add_q(70, "Java Core",
      "Manakah method pada interface Stream yang digunakan untuk mengubah setiap elemen menjadi bentuk baru (transformasi 1:1)?",
      {"A": "map()",
       "B": "filter()",
       "C": "flatMap()",
       "D": "peek()"},
      "A",
      "Method .map() menerima fungsi (Function<T, R>) dan menghasilkan stream baru yang berisi hasil penerapan fungsi tersebut ke tiap elemen stream secara 1:1.",
      "Opsi A benar karena map() melakukan transformasi 1-ke-1 antar elemen.",
      "Opsi B salah karena filter() digunakan untuk menyaring elemen berdasarkan kondisi boolean (Predicate).",
      "Opsi C salah karena flatMap() digunakan untuk meratakan nested stream (transformasi 1-ke-banyak).",
      "Opsi D salah karena peek() digunakan untuk observasi atau debugging efek samping tanpa mengubah data.")

# Spring Boot Fundamentals (71 to 82: 12 questions)
add_q(71, "Spring Boot",
      "Anotasi apakah yang merupakan kombinasi dari @Configuration, @EnableAutoConfiguration, dan @ComponentScan?",
      {"A": "@SpringBootApplication",
       "B": "@EnableConfigurationProperties",
       "C": "@RestController",
       "D": "@SpringBootConfiguration"},
      "A",
      "Anotasi @SpringBootApplication adalah meta-annotation yang menggabungkan tiga anotasi inti: @SpringBootConfiguration, @EnableAutoConfiguration, dan @ComponentScan.",
      "Opsi A benar karena merupakan anotasi standar pada kelas utama Spring Boot.",
      "Opsi B salah karena @EnableConfigurationProperties untuk mengaktifkan binding konfigurasi @ConfigurationProperties.",
      "Opsi C salah karena @RestController digunakan untuk controller API REST.",
      "Opsi D salah karena @SpringBootConfiguration hanyalah alias dari @Configuration.")

add_q(72, "Spring Boot",
      "Apa perbedaan utama antara @Controller dan @RestController di Spring framework?",
      {"A": "@RestController adalah gabungan @Controller dan @ResponseBody, sehingga method otomatis mengembalikan data JSON/XML bukan nama view HTML",
       "B": "@Controller hanya bekerja untuk API JSON, sedangkan @RestController untuk rendering JSP/Thymeleaf",
       "C": "@RestController tidak bisa menangani HTTP POST request",
       "D": "Tidak ada perbedaan, keduanya hanya alias nama yang identik"},
      "A",
      "@RestController merupakan convenience annotation yang dianotasi dengan @Controller dan @ResponseBody. Setiap method di dalamnya otomatis mengembalikan objek data mentah (biasanya JSON) ke HTTP response body.",
      "Opsi A benar karena mendefinisikan integrasi @ResponseBody pada @RestController.",
      "Opsi B salah karena @Controller biasa yang umumnya merender view template seperti Thymeleaf/JSP.",
      "Opsi C salah karena @RestController mendukung semua metode HTTP termasuk POST.",
      "Opsi D salah karena perilaku pengembalian nilai (view vs response body) berbeda.")

add_q(73, "Spring Boot",
      "Anotasi manakah yang digunakan untuk menandai kelas sebagai service layer yang memuat logika bisnis aplikasi?",
      {"A": "@Service",
       "B": "@Component",
       "C": "@Repository",
       "D": "@BusinessLogic"},
      "A",
      "@Service adalah spesialisasi dari @Component yang secara semantik digunakan untuk menandai kelas sebagai penyedia layanan logika bisnis dalam arsitektur aplikasi Spring.",
      "Opsi A benar karena @Service secara eksplisit mengidentifikasi lapisan bisnis.",
      "Opsi B salah meskipun @Service adalah turunan @Component, @Service lebih spesifik secara semantik.",
      "Opsi C salah karena @Repository dikhususkan untuk Data Access Object (DAO) / persistence layer.",
      "Opsi D salah karena @BusinessLogic bukan anotasi bawaan Spring.")

add_q(74, "Spring Boot",
      "Bagaimana cara membaca nilai konfigurasi 'server.port' dari file application.properties ke dalam variabel di kelas Spring?",
      {"A": "@Value(\"${server.port}\")",
       "B": "@Property(\"server.port\")",
       "C": "@Autowired(\"server.port\")",
       "D": "@ConfigValue(\"server.port\")"},
      "A",
      "Anotasi @Value(\"${nama.properti}\") digunakan untuk menginjeksi nilai properti dari environment atau file konfigurasi (application.properties/yml) ke dalam field.",
      "Opsi A benar karena sintaks ${...} di dalam @Value adalah cara standar Spring Expression Language.",
      "Opsi B salah karena @Property bukan anotasi injeksi nilai Spring.",
      "Opsi C salah karena @Autowired digunakan untuk dependency injection antar Spring Bean.",
      "Opsi D salah karena @ConfigValue bukan anotasi standar Spring.")

add_q(75, "Spring Boot",
      "Apakah default scope dari sebuah Spring Bean di ApplicationContext jika tidak didefinisikan secara eksplisit?",
      {"A": "singleton",
       "B": "prototype",
       "C": "request",
       "D": "session"},
      "A",
      "Secara default, semua bean di Spring ber-scope 'singleton', artinya Spring IoC container hanya membuat satu instance tunggal per ID bean untuk seluruh siklus hidup ApplicationContext.",
      "Opsi A benar karena singleton adalah scope default Spring.",
      "Opsi B salah karena scope prototype membuat instance baru setiap kali diinjeksi atau diminta.",
      "Opsi C salah karena scope request hanya ada di web application dan membuat instance per HTTP request.",
      "Opsi D salah karena scope session membuat instance per HTTP session.")

add_q(76, "Spring Boot",
      "Anotasi apakah yang digunakan untuk menandai sebuah method di dalam kelas @Configuration agar menghasilkan objek yang dikelola sebagai Spring Bean?",
      {"A": "@Bean",
       "B": "@Component",
       "C": "@Inject",
       "D": "@Service"},
      "A",
      "Anotasi @Bean ditempatkan pada level method (biasanya di dalam kelas @Configuration) untuk mendaftarkan objek kembalian method tersebut ke dalam Spring IoC container.",
      "Opsi A benar karena @Bean digunakan pada method konfigurasi.",
      "Opsi B salah karena @Component digunakan pada level class.",
      "Opsi C salah karena @Inject adalah anotasi standar JSR-330 untuk injeksi dependensi, bukan pembuatan bean factory method.",
      "Opsi D salah karena @Service digunakan pada level class lapisan bisnis.")

add_q(77, "Spring Boot",
      "Manakah cara dependency injection yang paling direkomendasikan dalam pengembangan modern Spring Boot?",
      {"A": "Constructor Injection",
       "B": "Field Injection menggunakan @Autowired langsung pada atribut private",
       "C": "Setter Injection tanpa constructor",
       "D": "Manual instantiation menggunakan operator 'new'"},
      "A",
      "Constructor injection sangat direkomendasikan karena menjamin immutability (field bisa dibuat final), memudahkan unit testing tanpa refleksi Spring container, dan mencegah NullPointerException saat runtime.",
      "Opsi A benar karena constructor injection adalah best practice resmi Spring framework.",
      "Opsi B salah karena field injection menyulitkan pengujian unit murni dan menyembunyikan dependensi.",
      "Opsi C salah karena setter injection membuat objek mutable dan berpotensi belum terinisialisasi saat method dipanggil.",
      "Opsi D salah karena menggunakan 'new' secara manual melanggar prinsip Inversion of Control.")

add_q(78, "Spring Boot",
      "Modul Spring Boot manakah yang menyediakan fitur monitoring kesiapan aplikasi, health check endpoint (/actuator/health), dan metrik sistem?",
      {"A": "spring-boot-starter-actuator",
       "B": "spring-boot-starter-web",
       "C": "spring-boot-starter-logging",
       "D": "spring-boot-starter-security"},
      "A",
      "Spring Boot Actuator menyediakan endpoint bawaan yang siap pakai untuk monitoring produksi seperti /health, /info, /metrics, dan /env.",
      "Opsi A benar karena Actuator adalah modul resmi Spring untuk observability.",
      "Opsi B salah karena starter web ditujukan untuk membangun REST API dan aplikasi web servlet.",
      "Opsi C salah karena logging sudah otomatis terintegrasi di starter parent.",
      "Opsi D salah karena starter security ditujukan untuk autentikasi dan otorisasi.")

add_q(79, "Spring Boot",
      "Anotasi manakah yang digunakan untuk membedakan (disambiguate) bean ketika terdapat dua atau lebih implementasi dari interface yang sama saat diinjeksi?",
      {"A": "@Qualifier",
       "B": "@Alias",
       "C": "@Select",
       "D": "@Choose"},
      "A",
      "Anotasi @Qualifier digunakan bersamaan dengan @Autowired atau pada parameter konstruktor untuk menentukan secara spesifik nama bean yang harus diinjeksi ketika terdapat kandidat lebih dari satu.",
      "Opsi A benar karena @Qualifier adalah anotasi resmi penyelesai konflik injeksi multi-bean.",
      "Opsi B salah karena @Alias bukan anotasi pemilihan bean Spring.",
      "Opsi C salah karena @Select adalah anotasi MyBatis untuk query SQL.",
      "Opsi D salah karena @Choose bukan anotasi Spring.")

add_q(80, "Spring Boot",
      "Apa fungsi dari anotasi @Profile di Spring Boot?",
      {"A": "Memetakan bean atau konfigurasi agar hanya aktif pada environment tertentu (seperti 'dev', 'test', atau 'prod')",
       "B": "Mengatur hak akses role user saat login ke sistem",
       "C": "Mengukur lama waktu eksekusi method untuk profiling performa",
       "D": "Menyimpan data profil pengguna ke dalam database"},
      "A",
      "Anotasi @Profile memungkinkan komponen atau file konfigurasi hanya didaftarkan ke ApplicationContext jika profil lingkungan yang ditentukan sedang aktif.",
      "Opsi A benar karena @Profile digunakan untuk segregasi konfigurasi antar environment.",
      "Opsi B salah karena otorisasi role diatur dengan @Secured atau @PreAuthorize.",
      "Opsi C salah karena profiling performa menggunakan interceptor atau AOP (Micrometer).",
      "Opsi D salah karena data entitas pengguna disimpan melalui JPA Entity.")

add_q(81, "Spring Boot",
      "File konfigurasi default apakah yang otomatis dibaca oleh Spring Boot saat aplikasi pertama kali dijalankan?",
      {"A": "application.properties atau application.yml di folder src/main/resources",
       "B": "web.xml di folder WEB-INF",
       "C": "pom.xml di root directory",
       "D": "spring-config.xml di folder src/main/resources"},
      "A",
      "Spring Boot secara default mencari file konfigurasi bernama application.properties atau application.yml di dalam classpath (src/main/resources).",
      "Opsi A benar karena merupakan lokasi dan nama file konfigurasi konvensional Spring Boot.",
      "Opsi B salah karena web.xml adalah konfigurasi lawas Java EE/Servlet yang tidak wajib di Spring Boot.",
      "Opsi C salah karena pom.xml adalah file dependensi Maven.",
      "Opsi D salah karena XML-based configuration sudah digantikan oleh konfigurasi berbasis anotasi dan YAML/properties.")

add_q(82, "Spring Boot",
      "Anotasi apakah yang digunakan untuk menandai kelas Data Access Object (DAO) dan mengaktifkan translasi exception database ke Spring DataAccessException?",
      {"A": "@Repository",
       "B": "@Database",
       "C": "@CrudService",
       "D": "@DaoComponent"},
      "A",
      "@Repository adalah spesialisasi dari @Component yang ditujukan untuk lapisan persistensi dan secara otomatis mengaktifkan DataAccessResourceFailureException translation.",
      "Opsi A benar karena @Repository adalah anotasi resmi Spring untuk DAO.",
      "Opsi B salah karena @Database bukan anotasi standar Spring.",
      "Opsi C salah karena @CrudService bukan anotasi Spring.",
      "Opsi D salah karena @DaoComponent bukan anotasi Spring.")

# RESTful API (83 to 92: 10 questions)
add_q(83, "RESTful API",
      "HTTP method manakah yang digunakan untuk membuat resource baru pada RESTful API dan bersifat NON-idempotent?",
      {"A": "POST",
       "B": "GET",
       "C": "PUT",
       "D": "DELETE"},
      "A",
      "POST digunakan untuk submit data baru dan bersifat non-idempotent, artinya memanggil POST berkali-kali dengan payload yang sama akan menghasilkan multiple resource baru yang berbeda.",
      "Opsi A benar karena POST dirancang untuk kreasi resource dan tidak idempotent.",
      "Opsi B salah karena GET hanya membaca data dan bersifat safe serta idempotent.",
      "Opsi C salah karena PUT menggantikan seluruh representasi resource dan bersifat idempotent.",
      "Opsi D salah karena DELETE menghapus resource dan bersifat idempotent.")

add_q(84, "RESTful API",
      "HTTP Status Code manakah yang menandakan bahwa request berhasil dibuat dan resource baru telah tersimpan di server?",
      {"A": "201 Created",
       "B": "200 OK",
       "C": "204 No Content",
       "D": "202 Accepted"},
      "A",
      "HTTP 201 Created menunjukkan bahwa permintaan telah berhasil dipenuhi dan menghasilkan satu atau lebih resource baru di server, biasanya disertai header 'Location'.",
      "Opsi A benar karena 201 Created adalah status standar saat resource baru tercipta.",
      "Opsi B salah karena 200 OK adalah status sukses umum tanpa indikasi spesifik pembuatan resource.",
      "Opsi C salah karena 204 No Content digunakan saat operasi sukses namun tidak ada response body.",
      "Opsi D salah karena 202 Accepted berarti permintaan telah diterima untuk diproses secara asynchronous namun belum tentu selesai.")

add_q(85, "RESTful API",
      "Anotasi Spring Web manakah yang digunakan untuk mengekstrak variabel dari URL path (contoh: /users/{id})?",
      {"A": "@PathVariable",
       "B": "@RequestParam",
       "C": "@RequestBody",
       "D": "@RequestHeader"},
      "A",
      "@PathVariable digunakan untuk mengikat (bind) nilai parameter dari pola URI template ke variabel argumen method pada controller.",
      "Opsi A benar karena @PathVariable mengekstrak variabel dari path segmen URL.",
      "Opsi B salah karena @RequestParam mengekstrak query string (contoh: /users?id=10).",
      "Opsi C salah karena @RequestBody memetakan body payload HTTP (JSON/XML) ke objek Java DTO.",
      "Opsi D salah karena @RequestHeader mengambil nilai dari HTTP header request.")

add_q(86, "RESTful API",
      "Apa perbedaan utama antara method HTTP PUT dan PATCH dalam operasi pembaruan data resource?",
      {"A": "PUT mengganti seluruh representasi resource (full update), sedangkan PATCH hanya memperbarui sebagian atribut resource (partial update)",
       "B": "PUT hanya digunakan untuk menghapus data, sedangkan PATCH untuk membuat data baru",
       "C": "PATCH bersifat idempotent sedangkan PUT non-idempotent",
       "D": "Keduanya persis sama dan hanya variasi penamaan dari spesifikasi RFC"},
      "A",
      "Sesuai spesifikasi RFC, PUT menggantikan seluruh representasi resource (jika field dihilangkan, nilainya akan di-reset ke default/null), sedangkan PATCH hanya memodifikasi field-field yang dikirimkan dalam payload.",
      "Opsi A benar karena menjelaskan perbedaan formal antara full update (PUT) dan partial update (PATCH).",
      "Opsi B salah karena operasi penghapusan menggunakan DELETE.",
      "Opsi C salah karena PUT wajib bersifat idempotent, sedangkan PATCH tidak selalu dijamin idempotent.",
      "Opsi D salah karena PUT dan PATCH memiliki semantik yang berbeda secara spesifikasi HTTP.")

add_q(87, "RESTful API",
      "HTTP Status Code manakah yang tepat dikembalikan ketika klien belum melakukan autentikasi (kredensial tidak ada atau tidak valid)?",
      {"A": "401 Unauthorized",
       "B": "403 Forbidden",
       "C": "404 Not Found",
       "D": "400 Bad Request"},
      "A",
      "HTTP 401 Unauthorized secara semantik berarti 'Unauthenticated' (klien belum terotentikasi dan harus menyertakan kredensial valid). Jika klien sudah terotentikasi tetapi tidak memiliki hak izin, status yang tepat adalah 403 Forbidden.",
      "Opsi A benar karena 401 mengindikasikan kegagalan autentikasi.",
      "Opsi B salah karena 403 menandakan klien sudah terautentikasi namun ditolak hak aksesnya (otorisasi).",
      "Opsi C salah karena 404 menunjukkan resource URL tidak ditemukan.",
      "Opsi D salah karena 400 mengindikasikan kesalahan sintaks atau format pada request klien.")

add_q(88, "RESTful API",
      "Header HTTP apakah yang dikirimkan oleh klien untuk menginformasikan kepada server format data yang diharapkan dalam balasan response?",
      {"A": "Accept",
       "B": "Content-Type",
       "C": "Authorization",
       "D": "User-Agent"},
      "A",
      "Header 'Accept' (misalnya: Accept: application/json) dikirim klien untuk menegosiasikan konten (Content Negotiation) yang diinginkan dari server. Sementara 'Content-Type' memberitahukan format body yang dikirim oleh pengirim saat itu.",
      "Opsi A benar karena Accept menentukan format yang diinginkan klien.",
      "Opsi B salah karena Content-Type menginformasikan tipe data body yang sedang dikirim.",
      "Opsi C salah karena Authorization membawa kredensial autentikasi.",
      "Opsi D salah karena User-Agent mengidentifikasi aplikasi browser atau HTTP client.")

add_q(89, "RESTful API",
      "Anotasi apakah yang digunakan pada method controller Spring Boot untuk menangani exception secara terpusat dalam satu kelas controller?",
      {"A": "@ExceptionHandler",
       "B": "@CatchException",
       "C": "@ErrorMapping",
       "D": "@HandleFault"},
      "A",
      "@ExceptionHandler digunakan untuk mendeklarasikan method penanganan exception spesifik yang terjadi saat pemrosesan request di controller.",
      "Opsi A benar karena @ExceptionHandler adalah anotasi resmi penanganan error di Spring MVC.",
      "Opsi B salah karena @CatchException bukan anotasi Spring.",
      "Opsi C salah karena @ErrorMapping bukan anotasi Spring.",
      "Opsi D salah karena @HandleFault bukan anotasi Spring.")

add_q(90, "RESTful API",
      "Anotasi apakah yang digunakan bersama @ControllerAdvice untuk menangani exception secara global di seluruh REST controller aplikasi?",
      {"A": "@RestControllerAdvice",
       "B": "@GlobalExceptionManager",
       "C": "@MasterErrorHandler",
       "D": "@ApplicationAdvice"},
      "A",
      "@RestControllerAdvice adalah kombinasi dari @ControllerAdvice dan @ResponseBody, menjadikannya standar arsitektur untuk penanganan exception global pada API RESTful.",
      "Opsi A benar karena @RestControllerAdvice mengembalikan response body JSON untuk semua error controller.",
      "Opsi B salah karena bukan komponen Spring.",
      "Opsi C salah karena bukan komponen Spring.",
      "Opsi D salah karena bukan komponen Spring.")

add_q(91, "RESTful API",
      "HTTP Status Code manakah yang tepat digunakan saat endpoint DELETE berhasil menghapus resource dan tidak perlu mengembalikan konten body?",
      {"A": "204 No Content",
       "B": "200 OK",
       "C": "202 Accepted",
       "D": "301 Moved Permanently"},
      "A",
      "Status 204 No Content menunjukkan server berhasil menyelesaikan request dan tidak perlu mengirimkan representasi data di body response.",
      "Opsi A benar karena 204 adalah standar respons sukses tanpa body.",
      "Opsi B salah karena 200 OK biasanya menyertakan body respons.",
      "Opsi C salah karena 202 berarti tugas penghapusan ditunda/diantrekan.",
      "Opsi D salah karena 301 adalah status pengalihan (redirection).")

add_q(92, "RESTful API",
      "Apakah yang dimaksud dengan konsep 'Idempotent' pada method HTTP?",
      {"A": "Melakukan pemanggilan berulang kali dengan request yang sama akan menghasilkan status dan efek samping yang sama pada server",
       "B": "Method yang tidak pernah mengubah data di server sama sekali",
       "C": "Method yang selalu membutuhkan token otentikasi Bearer",
       "D": "Method yang hanya boleh dijalankan satu kali seumur hidup aplikasi"},
      "A",
      "Idempotensi berarti memanggil request yang sama N kali memiliki efek samping yang identik dengan memanggilnya 1 kali (contoh method: GET, PUT, DELETE, HEAD, OPTIONS).",
      "Opsi A benar karena mendefinisikan prinsip matematis idempotensi dalam protokol HTTP.",
      "Opsi B salah karena method yang tidak mengubah data sama sekali disebut 'Safe' (seperti GET).",
      "Opsi C salah karena idempotensi tidak berkaitan dengan mekanisme token otentikasi.",
      "Opsi D salah karena request idempotent bebas dipanggil berkali-kali tanpa khawatir duplikasi efek samping.")

# JPA & Hibernate (93 to 100: 8 questions)
add_q(93, "JPA & Hibernate",
      "Anotasi apakah yang wajib diletakkan pada kelas Java agar dipetakan sebagai tabel database oleh JPA?",
      {"A": "@Entity",
       "B": "@TableOnly",
       "C": "@Model",
       "D": "@DataClass"},
      "A",
      "@Entity menandakan bahwa kelas tersebut adalah entitas JPA yang siklus hidupnya dikelola oleh EntityManager dan dipetakan ke baris tabel database.",
      "Opsi A benar karena @Entity adalah anotasi wajib untuk entitas JPA.",
      "Opsi B salah karena @TableOnly bukan anotasi JPA.",
      "Opsi C salah karena @Model bukan anotasi JPA standar.",
      "Opsi D salah karena @DataClass bukan anotasi JPA.")

add_q(94, "JPA & Hibernate",
      "Anotasi apakah yang digunakan untuk menentukan primary key dari sebuah entitas JPA?",
      {"A": "@Id",
       "B": "@Key",
       "C": "@PrimaryKey",
       "D": "@UniqueId"},
      "A",
      "@Id menandai field atau properti sebagai primary key dari entitas database tersebut.",
      "Opsi A benar karena @Id adalah anotasi resmi JPA untuk primary key.",
      "Opsi B salah karena @Key bukan anotasi JPA.",
      "Opsi C salah karena @PrimaryKey bukan anotasi standar JPA.",
      "Opsi D salah karena @UniqueId bukan anotasi JPA.")

add_q(95, "JPA & Hibernate",
      "Apa fungsi dari anotasi @GeneratedValue(strategy = GenerationType.IDENTITY) di JPA?",
      {"A": "Menyerahkan pembuatan nilai auto-increment primary key kepada mekanisme bawaan database",
       "B": "Menghasilkan string acak UUID secara otomatis di level aplikasi Java",
       "C": "Membuat tabel urutan terpisah (sequence table) di database",
       "D": "Mengharuskan programmer mengisi ID secara manual sebelum save"},
      "A",
      "GenerationType.IDENTITY memanfaatkan kolom auto-increment bawaan database (seperti AUTO_INCREMENT di MySQL atau SERIAL/IDENTITY di PostgreSQL) untuk mengisi nilai ID saat row di-insert.",
      "Opsi A benar karena IDENTITY mengandalkan auto-increment database.",
      "Opsi B salah karena UUID diatur dengan generator UUID atau GenerationType.AUTO.",
      "Opsi C salah karena penggunaan tabel terpisah menggunakan GenerationType.TABLE.",
      "Opsi D salah karena tidak mengisi manual adalah esensi dari @GeneratedValue.")

add_q(96, "JPA & Hibernate",
      "Interface dari Spring Data JPA manakah yang menyediakan method standar CRUD seperti save(), findById(), findAll(), dan deleteById()?",
      {"A": "JpaRepository atau CrudRepository",
       "B": "SqlSessionManager",
       "C": "HibernateTemplate",
       "D": "JdbcDaoSupport"},
      "A",
      "Spring Data JPA menyediakan CrudRepository dan JpaRepository yang secara otomatis menyediakan implementasi method CRUD tanpa perlu menulis kode SQL secara manual.",
      "Opsi A benar karena JpaRepository dan CrudRepository adalah interface standar Spring Data.",
      "Opsi B salah karena SqlSessionManager adalah komponen MyBatis.",
      "Opsi C salah karena HibernateTemplate adalah helper lama Spring.",
      "Opsi D salah karena JdbcDaoSupport adalah helper berbasis JDBC template.")

add_q(97, "JPA & Hibernate",
      "Kapan query database dieksekusi saat mengakses relasi dengan FetchType.LAZY di JPA?",
      {"A": "Hanya saat getter relasi tersebut pertama kali dipanggil di dalam transaksi aktif",
       "B": "Seketika saat entitas utama di-load dari database",
       "C": "Tidak pernah dieksekusi sama sekali",
       "D": "Hanya saat aplikasi Spring pertama kali booting"},
      "A",
      "FetchType.LAZY menunda (defers) loading data relasi hingga data tersebut benar-benar diakses pertama kali melalui method getter di dalam konteks sesi/transaksi yang masih terbuka.",
      "Opsi A benar karena menjelaskan sifat lazy loading.",
      "Opsi B salah karena mengambil seketika adalah karakteristik FetchType.EAGER.",
      "Opsi C salah karena data tetap di-load saat dipanggil.",
      "Opsi D salah karena fetch relasi terjadi saat runtime data diakses.")

add_q(98, "JPA & Hibernate",
      "Exception apakah yang lazim terjadi jika mengakses atribut FetchType.LAZY di luar batas transaksi atau setelah EntityManager tertutup?",
      {"A": "LazyInitializationException",
       "B": "NullPointerException",
       "C": "EntityNotFoundException",
       "D": "TransactionSystemException"},
      "A",
      "LazyInitializationException dilempar oleh Hibernate ketika kode mencoba menginisialisasi proxy lazy-loaded tanpa adanya sesi Hibernate (EntityManager) yang aktif.",
      "Opsi A benar karena merupakan exception khas Hibernate terkait lazy loading.",
      "Opsi B salah karena proxy lazy bukanlah null melainkan objek proxy yang uninitialized.",
      "Opsi C salah karena terjadi jika entitas dengan ID tertentu tidak ada di database.",
      "Opsi D salah karena berkaitan dengan kegagalan commit pada transaksi.")

add_q(99, "JPA & Hibernate",
      "Anotasi Spring apakah yang digunakan untuk mengelola transaksi database secara deklaratif pada method service?",
      {"A": "@Transactional",
       "B": "@TransactionManagement",
       "C": "@DatabaseTransaction",
       "D": "@CommitOnSuccess"},
      "A",
      "@Transactional membuka transaksi database sebelum method dieksekusi, dan otomatis melakukan commit jika sukses atau rollback jika terjadi RuntimeException.",
      "Opsi A benar karena @Transactional adalah anotasi deklaratif resmi Spring.",
      "Opsi B salah karena bukan anotasi method Spring.",
      "Opsi C salah karena bukan anotasi Spring.",
      "Opsi D salah karena bukan anotasi Spring.")

add_q(100, "JPA & Hibernate",
      "Apakah kepanjangan dari JPQL dalam konteks JPA?",
      {"A": "Java Persistence Query Language",
       "B": "Java Postgres Query Link",
       "C": "Joint Protocol Query Language",
       "D": "JSON Processing Query Library"},
      "A",
      "JPQL singkatan dari Java Persistence Query Language, yaitu bahasa kueri berorientasi objek yang beroperasi pada entitas Java dan atributnya, bukan langsung pada tabel dan kolom database.",
      "Opsi A benar karena merupakan kepanjangan resmi JPQL.",
      "Opsi B salah karena JPQL tidak terikat pada database PostgreSQL.",
      "Opsi C salah karena bukan singkatan JPQL.",
      "Opsi D salah karena JPQL bukan library pemrosesan JSON.")

# Testing (101 to 106: 6 questions)
add_q(101, "Testing",
      "Anotasi apakah di JUnit 5 yang menandai suatu method sebagai method pengujian?",
      {"A": "@Test",
       "B": "@TestCase",
       "C": "@UnitTest",
       "D": "@ExecuteTest"},
      "A",
      "Di JUnit 5 (Jupiter), anotasi org.junit.jupiter.api.Test digunakan untuk menandai method sebagai test case yang dapat dijalankan oleh test runner.",
      "Opsi A benar karena @Test adalah anotasi pengujian resmi JUnit 5.",
      "Opsi B salah karena @TestCase bukan anotasi JUnit 5.",
      "Opsi C salah karena @UnitTest bukan anotasi JUnit 5.",
      "Opsi D salah karena @ExecuteTest bukan anotasi JUnit 5.")

add_q(102, "Testing",
      "Anotasi JUnit 5 manakah yang dijalankan sebelum SETIAP method @Test di dalam kelas pengujian dieksekusi?",
      {"A": "@BeforeEach",
       "B": "@BeforeAll",
       "C": "@SetUp",
       "D": "@PreTest"},
      "A",
      "@BeforeEach di JUnit 5 dijalankan sebelum setiap method pengujian dieksekusi, menggantikan anotasi @Before dari JUnit 4.",
      "Opsi A benar karena @BeforeEach berjalan sebelum setiap test method.",
      "Opsi B salah karena @BeforeAll dijalankan sekali untuk seluruh kelas sebelum semua test dimulai.",
      "Opsi C salah karena @SetUp bukan anotasi JUnit 5.",
      "Opsi D salah karena @PreTest bukan anotasi JUnit 5.")

add_q(103, "Testing",
      "Di Mockito, anotasi apakah yang digunakan untuk membuat objek tiruan (mock) dari sebuah dependensi?",
      {"A": "@Mock",
       "B": "@Fake",
       "C": "@Dummy",
       "D": "@Stub"},
      "A",
      "@Mock digunakan untuk membuat objek tiruan (mock) dari interface atau class tanpa perlu implementasi nyata.",
      "Opsi A benar karena @Mock adalah anotasi standar Mockito.",
      "Opsi B salah karena @Fake bukan anotasi Mockito bawaan.",
      "Opsi C salah karena @Dummy bukan anotasi Mockito bawaan.",
      "Opsi D salah karena @Stub bukan anotasi Mockito bawaan.")

add_q(104, "Testing",
      "Anotasi Mockito manakah yang digunakan untuk menginjeksi semua dependensi @Mock ke dalam objek yang sedang diuji?",
      {"A": "@InjectMocks",
       "B": "@Autowired",
       "C": "@InjectTarget",
       "D": "@MockContainer"},
      "A",
      "@InjectMocks menandai instance target pengujian dan secara otomatis menginjeksi mock objects ke dalam field atau constructor-nya.",
      "Opsi A benar karena @InjectMocks menginjeksi mock dependency ke target pengujian.",
      "Opsi B salah karena @Autowired adalah anotasi Spring Framework untuk dependency injection di container runtime.",
      "Opsi C salah karena @InjectTarget bukan anotasi Mockito.",
      "Opsi D salah karena @MockContainer bukan anotasi Mockito.")

add_q(105, "Testing",
      "Method assertion JUnit 5 manakah yang digunakan untuk memverifikasi bahwa dua nilai (expected dan actual) adalah sama?",
      {"A": "assertEquals(expected, actual)",
       "B": "assertSameValue(expected, actual)",
       "C": "verifyEquals(expected, actual)",
       "D": "checkIdentical(expected, actual)"},
      "A",
      "Method org.junit.jupiter.api.Assertions.assertEquals(expected, actual) digunakan untuk membandingkan kesamaan nilai menggunakan method .equals().",
      "Opsi A benar karena assertEquals adalah method assertion standar JUnit.",
      "Opsi B salah karena tidak ada method assertSameValue.",
      "Opsi C salah karena verify adalah sintaks verifikasi interaksi milik Mockito.",
      "Opsi D salah karena checkIdentical bukan method JUnit.")

add_q(106, "Testing",
      "Anotasi Spring Boot Test manakah yang digunakan untuk pengujian lapisan Controller saja secara terisolasi tanpa memuat seluruh ApplicationContext?",
      {"A": "@WebMvcTest",
       "B": "@SpringBootTest",
       "C": "@DataJpaTest",
       "D": "@RestClientTest"},
      "A",
      "@WebMvcTest hanya memuat komponen web layer (Controller, ControllerAdvice, Filter) dan MockMvc, sehingga tes berjalan sangat cepat dan terisolasi.",
      "Opsi A benar karena @WebMvcTest mengisolasi slice pengujian controller.",
      "Opsi B salah karena @SpringBootTest memuat full ApplicationContext yang lebih berat.",
      "Opsi C salah karena @DataJpaTest hanya memuat slice persistence database.",
      "Opsi D salah karena @RestClientTest menguji klien REST/RestTemplate.")

# Clean Code & SOLID (107 to 112: 6 questions)
add_q(107, "Clean Code & SOLID",
      "Apakah prinsip 'S' dalam akronim SOLID design principles?",
      {"A": "Single Responsibility Principle: sebuah class hanya boleh memiliki satu alasan untuk berubah",
       "B": "Static Binding Principle: method harus dideklarasikan static jika memungkinkan",
       "C": "Simple Syntax Principle: kode harus ditulis seringkas mungkin dalam satu baris",
       "D": "Sequential Execution Principle: kode harus dieksekusi secara linear tanpa threading"},
      "A",
      "Single Responsibility Principle (SRP) menyatakan bahwa setiap modul atau class harus bertanggung jawab atas satu fungsionalitas tunggal yang spesifik sehingga hanya memiliki satu alasan untuk berubah.",
      "Opsi A benar karena SRP mendefinisikan batas tanggung jawab tunggal per class.",
      "Opsi B salah karena bukan bagian dari SOLID.",
      "Opsi C salah karena bukan bagian dari SOLID.",
      "Opsi D salah karena bukan bagian dari SOLID.")

add_q(108, "Clean Code & SOLID",
      "Prinsip apakah dalam Clean Code yang menyarankan agar kita tidak mengulang-ulang logika kode yang sama di beberapa tempat?",
      {"A": "DRY (Don't Repeat Yourself)",
       "B": "KISS (Keep It Simple, Stupid)",
       "C": "YAGNI (You Aren't Gonna Need It)",
       "D": "Boy Scout Rule"},
      "A",
      "DRY (Don't Repeat Yourself) menekankan pentingnya abstraksi agar setiap potong pengetahuan atau logika sistem memiliki representasi tunggal yang tidak ambigu di dalam sistem.",
      "Opsi A benar karena DRY menolak duplikasi kode.",
      "Opsi B salah karena KISS berfokus pada kesederhanaan desain.",
      "Opsi C salah karena YAGNI melarang penulisan fitur yang belum benar-benar dibutuhkan saat ini.",
      "Opsi D salah karena Boy Scout Rule menyarankan untuk meninggalkan kode dalam kondisi lebih bersih daripada saat pertama kali membacanya.")

add_q(109, "Clean Code & SOLID",
      "Apakah inti dari prinsip 'O' (Open/Closed Principle) dalam SOLID?",
      {"A": "Entitas software harus terbuka untuk ekstensi (open for extension), tetapi tertutup untuk modifikasi (closed for modification)",
       "B": "Semua file class harus bersifat open source dan tidak boleh diproteksi password",
       "C": "Method harus selalu membuka koneksi database dan langsung menutupnya",
       "D": "Class turunan harus dapat mengubah logika parent class secara radikal"},
      "A",
      "Open/Closed Principle (OCP) menganjurkan agar perilaku sistem dapat diperluas (misalnya dengan membuat subclass baru atau implementasi interface baru) tanpa harus mengedit kode sumber yang sudah berjalan dan teruji.",
      "Opsi A benar karena mendefinisikan esensi OCP.",
      "Opsi B salah karena OCP tidak berkaitan dengan lisensi software.",
      "Opsi C salah karena OCP bukan tentang koneksi I/O database.",
      "Opsi D salah karena mengubah logika parent class melanggar Liskov Substitution Principle.")

add_q(110, "Clean Code & SOLID",
      "Prinsip apakah yang mengingatkan pengembang: 'Jangan menambahkan fitur spekulatif yang belum ada kebutuhan nyatanya saat ini'?",
      {"A": "YAGNI (You Aren't Gonna Need It)",
       "B": "DRY (Don't Repeat Yourself)",
       "C": "KISS (Keep It Simple, Stupid)",
       "D": "TDD (Test Driven Development)"},
      "A",
      "YAGNI adalah prinsip agile/extreme programming yang melarang developer membangun kode berdasarkan asumsi masa depan yang belum diminta, demi menghemat waktu dan menjaga kesederhanaan codebase.",
      "Opsi A benar karena YAGNI mencegah over-engineering fitur yang belum tentu terpakai.",
      "Opsi B salah karena DRY tentang menghindari duplikasi kode.",
      "Opsi C salah karena KISS tentang menjaga solusi tetap sederhana.",
      "Opsi D salah karena TDD adalah metodologi menulis test sebelum kode produksi.")

add_q(111, "Clean Code & SOLID",
      "Menurut prinsip Liskov Substitution Principle (LSP), apa aturan mendasar mengenai subclass?",
      {"A": "Subclass harus dapat menggantikan superclass-nya tanpa merusak fungsionalitas dan kebenaran program",
       "B": "Subclass wajib melempar UnsupportedOperationException jika method superclass tidak dibutuhkan",
       "C": "Subclass harus selalu berukuran baris kode lebih kecil daripada superclass",
       "D": "Subclass tidak boleh memiliki method tambahan selain yang ada di superclass"},
      "A",
      "Liskov Substitution Principle menyatakan bahwa jika S adalah subclass dari T, maka objek bertipe T harus dapat digantikan oleh objek bertipe S tanpa mengubah kebenaran perilaku program.",
      "Opsi A benar karena mendefinisikan LSP secara formal.",
      "Opsi B salah karena melempar UnsupportedOperationException pada method kontrak adalah pelanggaran nyata terhadap LSP.",
      "Opsi C salah karena ukuran baris kode tidak relevan dengan LSP.",
      "Opsi D salah karena subclass bebas menambahkan method spesifik baru.")

add_q(112, "Clean Code & SOLID",
      "Manakah praktik penamaan variabel yang sesuai dengan kaidah Clean Code di Java?",
      {"A": "Menggunakan camelCase yang deskriptif dan mencerminkan maksud/arti data (misal: 'totalActiveUsers')",
       "B": "Menggunakan singkatan satu huruf untuk field kelas (misal: 'int u;') agar hemat memori",
       "C": "Menggunakan huruf besar semua dengan garis bawah untuk variabel lokal (misal: 'int JUMLAH_USER;')",
       "D": "Menambahkan tipe data ke nama variabel (Hungarian notation, misal: 'int iTotal')"},
      "A",
      "Clean Code menganjurkan penggunaan nama variabel yang jelas, bermakna, mudah diucapkan, dan mengikuti konvensi Java (camelCase untuk variabel/method).",
      "Opsi A benar karena mencerminkan best practice Java Clean Code.",
      "Opsi B salah karena singkatan satu huruf menyulitkan pemahaman kode.",
      "Opsi C salah karena UPPER_SNAKE_CASE dikhususkan untuk konstanta static final.",
      "Opsi D salah karena Hungarian notation tidak direkomendasikan di bahasa strongly-typed modern seperti Java.")

# SQL & Database (113 to 118: 6 questions)
add_q(113, "SQL & Database",
      "Klausul SQL manakah yang digunakan untuk menyaring baris data berdasarkan kondisi tertentu?",
      {"A": "WHERE",
       "B": "GROUP BY",
       "C": "ORDER BY",
       "D": "HAVING"},
      "A",
      "Klausul WHERE digunakan untuk menyaring rekaman sebelum pengelompokan (grouping) dilakukan.",
      "Opsi A benar karena WHERE adalah perintah filter baris standar SQL.",
      "Opsi B salah karena GROUP BY digunakan untuk mengelompokkan baris berdasarkan nilai kolom yang sama.",
      "Opsi C salah karena ORDER BY digunakan untuk mengurutkan hasil query.",
      "Opsi D salah karena HAVING digunakan untuk menyaring hasil setelah agregasi GROUP BY.")

add_q(114, "SQL & Database",
      "Apa perbedaan mendasar antara klausa WHERE dan HAVING di SQL?",
      {"A": "WHERE memfilter baris data sebelum agregasi, sedangkan HAVING memfilter hasil fungsi agregat setelah GROUP BY",
       "B": "WHERE hanya untuk tabel relasional, sedangkan HAVING untuk NoSQL",
       "C": "HAVING hanya bisa digunakan bersama klausa ORDER BY",
       "D": "Tidak ada perbedaan, keduanya memiliki fungsi identik"},
      "A",
      "WHERE mengevaluasi baris per baris sebelum pengelompokan dan tidak bisa menerima fungsi agregat (seperti COUNT, SUM). HAVING mengevaluasi hasil grup setelah agregasi dijalankan.",
      "Opsi A benar karena membedakan tahapan evaluasi sebelum vs sesudah agregasi.",
      "Opsi B salah karena keduanya adalah klausul SQL relasional.",
      "Opsi C salah karena HAVING berpasangan dengan GROUP BY, bukan ORDER BY.",
      "Opsi D salah karena fase eksekusi dan kapabilitas keduanya berbeda.")

add_q(115, "SQL & Database",
      "Jenis JOIN SQL apakah yang hanya mengembalikan baris yang memiliki kecocokan di kedua tabel yang digabungkan?",
      {"A": "INNER JOIN",
       "B": "LEFT JOIN",
       "C": "RIGHT JOIN",
       "D": "FULL OUTER JOIN"},
      "A",
      "INNER JOIN hanya mengembalikan baris jika kondisi pencocokan terpenuhi di kedua tabel (irisan).",
      "Opsi A benar karena INNER JOIN mengambil irisan data yang cocok di kedua sisi.",
      "Opsi B salah karena LEFT JOIN mempertahankan semua baris dari tabel kiri meskipun di tabel kanan tidak ada yang cocok.",
      "Opsi C salah karena RIGHT JOIN mempertahankan semua baris dari tabel kanan.",
      "Opsi D salah karena FULL OUTER JOIN mengembalikan semua baris dari kedua tabel.")

add_q(116, "SQL & Database",
      "Perintah SQL apakah yang digunakan untuk menambahkan baris data baru ke dalam tabel?",
      {"A": "INSERT INTO",
       "B": "UPDATE",
       "C": "ALTER TABLE",
       "D": "ADD ROW"},
      "A",
      "Perintah INSERT INTO digunakan untuk menyisipkan satu atau beberapa baris data baru ke dalam tabel.",
      "Opsi A benar karena INSERT INTO adalah sintaks resmi DML untuk membuat baris data.",
      "Opsi B salah karena UPDATE digunakan untuk mengubah baris data yang sudah ada.",
      "Opsi C salah karena ALTER TABLE digunakan untuk mengubah struktur skema tabel (DDL).",
      "Opsi D salah karena ADD ROW bukan sintaks SQL standar.")

add_q(117, "SQL & Database",
      "Apa karakteristik utama dari PRIMARY KEY pada tabel database relasional?",
      {"A": "Nilainya harus unik untuk setiap baris dan tidak boleh bernilai NULL",
       "B": "Boleh bernilai NULL asalkan unik",
       "C": "Satu tabel diperbolehkan memiliki lebih dari satu primary key",
       "D": "Hanya boleh bertipe data integer dan tidak bisa composite key"},
      "A",
      "Primary key secara otomatis menerapkan batasan UNIQUE dan NOT NULL untuk mengidentifikasi setiap rekaman baris secara unik.",
      "Opsi A benar karena primary key wajib unik dan tidak boleh null.",
      "Opsi B salah karena primary key secara mutlak dilarang bernilai NULL.",
      "Opsi C salah karena satu tabel hanya boleh memiliki tepat satu primary key (walaupun bisa terdiri dari beberapa kolom / composite).",
      "Opsi D salah karena primary key dapat bertipe string (misal UUID) atau composite key.")

add_q(118, "SQL & Database",
      "Apakah tujuan utama dari pembuatan Index pada kolom tabel database?",
      {"A": "Mempercepat operasi pencarian dan pembacaan query SELECT",
       "B": "Mengurangi ukuran penyimpanan tabel di hard disk",
       "C": "Mempercepat operasi INSERT dan UPDATE secara signifikan",
       "D": "Menghapus duplikasi data secara otomatis"},
      "A",
      "Index (biasanya berstruktur B-Tree) mempercepat pencarian data dengan menyediakan struktur pohon terurut, mengurangi kebutuhan full table scan.",
      "Opsi A benar karena index mengoptimasi performa retrieval data SELECT.",
      "Opsi B salah karena index justru menambah konsumsi ruang disk.",
      "Opsi C salah karena index sedikit memperlambat INSERT/UPDATE karena pohon index harus diperbarui.",
      "Opsi D salah karena penghapusan duplikasi adalah tugas constraint UNIQUE.")

# Spring Security & JWT (119 to 121: 3 questions)
add_q(119, "Spring Security & JWT",
      "Apakah perbedaan mendasar antara konsep Autentikasi (Authentication) dan Otorisasi (Authorization)?",
      {"A": "Autentikasi memverifikasi identitas pengguna ('siapa Anda?'), sedangkan Otorisasi menentukan hak akses pengguna ('apa yang boleh Anda lakukan?')",
       "B": "Autentikasi menentukan izin akses, sedangkan Otorisasi memverifikasi password",
       "C": "Autentikasi hanya berjalan di frontend, sedangkan Otorisasi di database",
       "D": "Keduanya adalah istilah yang dapat dipertukarkan tanpa perbedaan makna"},
      "A",
      "Autentikasi adalah pembuktian identitas (misal login dengan email & password). Otorisasi adalah pemeriksaan izin/wewenang apakah user berhak mengakses resource tertentu (misal role ADMIN vs USER).",
      "Opsi A benar karena membedakan verifikasi identitas vs pembatasan wewenang.",
      "Opsi B salah karena membalik definisi autentikasi dan otorisasi.",
      "Opsi C salah karena keduanya adalah proses keamanan level backend.",
      "Opsi D salah karena memiliki tanggung jawab yang berbeda dalam arsitektur keamanan.")

add_q(120, "Spring Security & JWT",
      "Komponen PasswordEncoder apakah yang menjadi standar rekomendasi Spring Security untuk mengenkripsi/menghash password dengan algoritma adaptif?",
      {"A": "BCryptPasswordEncoder",
       "B": "Md5PasswordEncoder",
       "C": "Sha1PasswordEncoder",
       "D": "PlainTextPasswordEncoder"},
      "A",
      "BCryptPasswordEncoder menggunakan algoritma hashing satu arah BCrypt dengan penambahan salt otomatis dan work factor yang adaptif terhadap peningkatan kekuatan komputasi.",
      "Opsi A benar karena BCrypt adalah standar de-facto password hashing di Spring Security.",
      "Opsi B salah karena MD5 sudah tidak aman (vulnerable to collision).",
      "Opsi C salah karena SHA-1 sudah deprecated dan rentan serangan brute-force.",
      "Opsi D salah karena menyimpan password dalam plain text adalah pelanggaran fatal keamanan.")

add_q(121, "Spring Security & JWT",
      "Bagian apakah yang membentuk sebuah struktur token JSON Web Token (JWT)?",
      {"A": "Header, Payload, dan Signature (dipisahkan oleh tanda titik)",
       "B": "Username, Password, dan ExpiredDate",
       "C": "Public Key, Private Key, dan Certificate",
       "D": "XML Body, SoapAction, dan Timestamp"},
      "A",
      "JWT terdiri dari tiga bagian terpisah yang di-encode Base64Url: Header (algoritma & tipe token), Payload (claims data), dan Signature (verifikasi integritas token).",
      "Opsi A benar karena merinci 3 komponen pembentuk JWT standar RFC 7519.",
      "Opsi B salah karena password tidak pernah boleh dimasukkan ke dalam token JWT.",
      "Opsi C salah karena itu adalah komponen sertifikat TLS/PKI.",
      "Opsi D salah karena itu adalah format pesan protokol SOAP.")

# Design Patterns (122 to 124: 3 questions)
add_q(122, "Design Patterns",
      "Design pattern apakah yang memastikan sebuah kelas hanya memiliki satu instance tunggal dan menyediakan titik akses global ke instance tersebut?",
      {"A": "Singleton Pattern",
       "B": "Factory Method Pattern",
       "C": "Builder Pattern",
       "D": "Prototype Pattern"},
      "A",
      "Singleton pattern membatasi instansiasi sebuah kelas menjadi satu objek saja di memori dan menyediakan method statis (misal: getInstance()) untuk mengaksesnya.",
      "Opsi A benar karena merupakan definisi tepat dari Singleton pattern.",
      "Opsi B salah karena Factory Method mendelegasikan pembuatan objek ke subclass/factory.",
      "Opsi C salah karena Builder digunakan untuk merakit objek kompleks langkah demi langkah.",
      "Opsi D salah karena Prototype membuat objek baru dengan cara mengkloning objek yang sudah ada.")

add_q(123, "Design Patterns",
      "Design pattern apakah yang sangat cocok digunakan untuk membuat objek kompleks yang memiliki banyak parameter opsional agar kode lebih terbaca tanpa telescoping constructor?",
      {"A": "Builder Pattern",
       "B": "Singleton Pattern",
       "C": "Decorator Pattern",
       "D": "Adapter Pattern"},
      "A",
      "Builder pattern memisahkan konstruksi objek dari representasinya, memungkinkan pembuatan objek yang fleksibel dengan method chaining (misal: User.builder().name(...).age(...).build()).",
      "Opsi A benar karena Builder pattern menyelesaikan masalah antipattern telescoping constructor.",
      "Opsi B salah karena Singleton hanya memastikan satu objek tunggal.",
      "Opsi C salah karena Decorator menambahkan tanggung jawab pada objek secara dinamis.",
      "Opsi D salah karena Adapter menjembatani dua interface yang tidak kompatibel.")

add_q(124, "Design Patterns",
      "Design pattern apakah yang mendelegasikan proses instansiasi objek ke method atau subclass sehingga kode klien tidak terikat langsung pada kelas konkretnya?",
      {"A": "Factory Method Pattern",
       "B": "Observer Pattern",
       "C": "Strategy Pattern",
       "D": "Proxy Pattern"},
      "A",
      "Factory Method pattern mendefinisikan interface pembuatan objek tetapi membiarkan subclass atau method pabrik menentukan kelas konkret mana yang diinstansiasi.",
      "Opsi A benar karena Factory pattern mengisolasi proses pembuatan objek konkret.",
      "Opsi B salah karena Observer adalah pattern behavioural untuk notifikasi event 1-ke-banyak.",
      "Opsi C salah karena Strategy adalah pattern behavioural untuk menukar algoritma secara dinamis.",
      "Opsi D salah karena Proxy adalah pattern struktural untuk mengontrol akses ke objek lain.")

# Git & SDLC (125 to 126: 2 questions)
add_q(125, "Git & SDLC",
      "Perintah Git manakah yang digunakan untuk mendownload salinan repository remote beserta riwayat commit-nya ke komputer lokal untuk pertama kali?",
      {"A": "git clone <url>",
       "B": "git init",
       "C": "git pull",
       "D": "git checkout"},
      "A",
      "'git clone' menduplikasi seluruh repository Git remote ke direktori lokal baru, termasuk semua branch, commit, dan konfigurasi origin.",
      "Opsi A benar karena git clone adalah perintah download repo remote pertama kali.",
      "Opsi B salah karena git init membuat repository lokal baru yang masih kosong.",
      "Opsi C salah karena git pull mengambil pembaruan commit dari remote pada repo lokal yang sudah ada.",
      "Opsi D salah karena git checkout berpindah branch atau restore file kerja.")

add_q(126, "Git & SDLC",
      "Apa fungsi utama dari proses Pull Request (PR) atau Merge Request dalam siklus pengembangan perangkat lunak (SDLC)?",
      {"A": "Memungkinkan tim melakukan code review, diskusi, dan automated testing sebelum perubahan kode digabungkan ke branch utama",
       "B": "Menghapus commit yang salah secara otomatis tanpa jejak",
       "C": "Mengubah kode Java menjadi file .jar atau .war di server",
       "D": "Menonaktifkan pengujian unit agar deployment lebih cepat"},
      "A",
      "Pull Request adalah mekanisme kolaborasi di mana developer mengajukan perubahan kode agar dapat direview oleh rekan tim (peer review), diverifikasi oleh CI pipeline, dan dipastikan mematuhi standar sebelum dimerge ke branch target.",
      "Opsi A benar karena code review dan verifikasi kualitas adalah esensi utama Pull Request.",
      "Opsi B salah karena PR tidak bertujuan menghapus jejak commit.",
      "Opsi C salah karena kompilasi/packaging adalah tugas build tool (Maven/Gradle).",
      "Opsi D salah karena CI/CD pada PR justru menjalankan unit test secara otomatis demi menjaga stabilitas.")

print(f"Total beginner generated: {len(questions)}")
with open("scripts/data_java_beginner.json", "w", encoding="utf-8") as f:
    json.dump(questions, f, ensure_ascii=False, indent=2)
