import json

questions = []

def add_q(id_num, topic, q, opts, ans, exp_corr, exp_a, exp_b, exp_c, exp_d):
    qid = f"JI-{id_num:03d}"
    questions.append({
        "id": qid,
        "level": "intermediate",
        "topic": topic,
        "question": q,
        "options": opts,
        "answer": ans,
        "explanation": {
            "correct": exp_corr,
            "A": exp_a,
            "B": exp_b,
            "C": exp_c,
            "D": exp_d
        }
    })

# Part 1: Java Core Intermediate (51 to 85 = 35 questions)
add_q(51, "Java Core",
      "Bagaimana HashMap di Java 8+ menangani collision ketika jumlah elemen dalam satu bucket melebihi batas ambang (TREEIFY_THRESHOLD = 8)?",
      {"A": "Mengubah struktur linked list di dalam bucket menjadi Red-Black Tree (TreeNode) untuk menurunkan kompleksitas pencarian menjadi O(log n)",
       "B": "Secara otomatis membuang elemen terlama (FIFO) agar kapasitas bucket tetap 8",
       "C": "Melemparkan exception HashCollisionException ke pemanggil",
       "D": "Memperbesar ukuran bucket menjadi dua kali lipat tanpa mengubah struktur list"},
      "A",
      "Di Java 8+, ketika sebuah bucket HashMap memiliki lebih dari 8 node (TREEIFY_THRESHOLD) dan kapasitas total tabel minimal 64, linked list pada bucket tersebut akan diubah menjadi Red-Black Tree seimbang, sehingga performa lookup membaik dari O(n) menjadi O(log n).",
      "Opsi A benar karena menjelaskan mekanisme treeification Red-Black Tree di Java 8.",
      "Opsi B salah karena HashMap bukan LRU cache (LinkedHashMap memiliki mekanisme penggusuran, tetapi bukan dengan membuang elemen secara sembarangan).",
      "Opsi C salah karena hash collision adalah fenomena normal dan tidak melempar exception.",
      "Opsi D salah karena ekspansi array (rehashing) terjadi berdasarkan load factor keseluruhan, bukan hanya per bucket.")

add_q(52, "Java Core",
      "Mengapa ConcurrentHashMap jauh lebih scalable dan berkinerja tinggi dalam lingkungan multi-threading dibandingkan Collections.synchronizedMap()?",
      {"A": "ConcurrentHashMap menggunakan segment locking atau CAS (Compare-And-Swap) dan synchronized hanya pada level node/bucket individual, sedangkan synchronizedMap mengunci seluruh tabel map untuk setiap operasi",
       "B": "ConcurrentHashMap menyimpan semua datanya di CPU cache L1 tanpa menyentuh RAM",
       "C": "ConcurrentHashMap tidak mengizinkan operasi read secara bersamaan",
       "D": "ConcurrentHashMap menonaktifkan mekanisme garbage collection untuk entry-nya"},
      "A",
      "Collections.synchronizedMap menggunakan mutex lock tunggal untuk seluruh instance map (setiap operasi write/read bersaing memperebutkan lock yang sama). ConcurrentHashMap menggunakan fine-grained lock per bucket node dan operasi non-blocking CAS untuk pembacaan bersamaan (concurrent reads).",
      "Opsi A benar karena lock striping/bucket-level locking dan CAS memungkinkan throughput konkurensi tinggi.",
      "Opsi B salah karena memori Java heap selalu berada di RAM.",
      "Opsi C salah karena ConcurrentHashMap justru mendukung pembacaan paralel non-blocking tanpa lock.",
      "Opsi D salah karena entry ConcurrentHashMap tetap dikelola oleh Garbage Collector secara normal.")

add_q(53, "Java Core",
      "Diberikan operasi Stream berikut: list.stream().flatMap(List::stream). Apakah fungsi utama dari flatMap() di sini?",
      {"A": "Meratakan (flatten) nested collection atau Stream<List<T>> menjadi satu Stream<T> datar",
       "B": "Menghapus elemen duplikat di dalam nested list",
       "C": "Menyortir list secara descending sebelum diproses",
       "D": "Mengonversi list menjadi Map key-value pair"},
      "A",
      "flatMap() menerima fungsi yang memetakan setiap elemen menjadi sebuah Stream terpisah, lalu menggabungkan semua stream parsial tersebut menjadi satu stream tunggal yang rata (flattening).",
      "Opsi A benar karena flatMap menggabungkan nested stream menjadi single flattened stream.",
      "Opsi B salah karena penghapusan duplikasi dilakukan oleh operasi .distinct().",
      "Opsi C salah karena pengurutan dilakukan oleh .sorted().",
      "Opsi D salah karena konversi ke Map dilakukan oleh Collectors.toMap().")

add_q(54, "Java Core",
      "Perhatikan kode: List<? extends Number> numbers = new ArrayList<Integer>();. Manakah pernyataan yang benar mengenai batas wildcard (bounded wildcard) ini?",
      {"A": "numbers aman untuk dibaca (read) sebagai Number, tetapi tidak dapat ditambahkan elemen baru (kecuali null) karena compiler tidak tahu tipe konkret elemennya",
       "B": "numbers bebas ditambahkan elemen bertipe Integer maupun Double secara bersamaan",
       "C": "Kode di atas menghasilkan compile error karena Integer bukan subclass dari Number",
       "D": "numbers hanya dapat dibaca sebagai tipe Object murni"},
      "A",
      "Menurut prinsip PECS (Producer Extends, Consumer Super), wildcard '? extends T' bertindak sebagai Producer (hanya bisa dibaca). Compiler melarang penambahan elemen (kecuali null) karena tipe konkret yang tersimpan bisa berupa Long, Double, atau subclass Number lain yang tidak kompatibel.",
      "Opsi A benar sesuai aturan covariance dan pembatasan penulisan pada '? extends'.",
      "Opsi B salah karena penambahan elemen tipe konkret dilarang oleh compiler untuk mencegah runtime type violation.",
      "Opsi C salah karena Integer adalah subclass langsung dari java.lang.Number.",
      "Opsi D salah karena elemen yang dibaca aman di-cast dan diperlakukan sebagai Number.")

add_q(55, "Java Core",
      "Apakah perbedaan prinsip PECS antara 'List<? super Integer>' dan 'List<? extends Number>'?",
      {"A": "'? super Integer' adalah Consumer (dapat menerima penambahan Integer), sedangkan '? extends Number' adalah Producer (hanya dapat dibaca sebagai Number)",
       "B": "'? super' hanya bisa membaca data, sedangkan '? extends' hanya bisa menulis data",
       "C": "Keduanya identik dan hanya perbedaan gaya penulisan",
       "D": "'? super' membatasi tipe ke level superclass paling atas (Object saja)"},
      "A",
      "PECS (Producer Extends, Consumer Super) menjelaskan: jika struktur data menghasilkan data (Producer), gunakan extends. Jika struktur data mengonsumsi data (Consumer/menulis), gunakan super (kita aman menambahkan instance Integer ke dalam List<? super Integer>).",
      "Opsi A benar karena merangkum prinsip utama PECS.",
      "Opsi B salah karena membalik konsep Producer dan Consumer.",
      "Opsi C salah karena extends dan super memiliki aturan variance yang berlawanan (covariance vs contravariance).",
      "Opsi D salah karena '? super Integer' dapat memegang List<Integer>, List<Number>, atau List<Object>.")

add_q(56, "Java Core",
      "Apa fungsi utama dari keyword 'volatile' pada variabel yang diakses oleh banyak thread di Java?",
      {"A": "Menjamin 'visibility' dengan memaksa pembacaan dan penulisan variabel langsung ke main memory (bukan CPU cache thread), serta mencegah instruction reordering",
       "B": "Menjadikan operasi increment (seperti i++) bersifat atomic",
       "C": "Mengunci variabel sehingga hanya satu thread yang bisa membacanya pada satu waktu",
       "D": "Menyimpan variabel di memori disk agar persisten setelah JVM mati"},
      "A",
      "Keyword volatile memastikan nilai terbaru yang ditulis oleh satu thread langsung terlihat (visible) oleh semua thread lain karena menonaktifkan caching variabel pada register CPU lokal thread dan mencegah reordering compiler/CPU.",
      "Opsi A benar karena volatile menjamin visibility dan ordering tanpa locking.",
      "Opsi B salah karena volatile TIDAK menjamin atomicity operasi majemuk seperti read-modify-write (i++).",
      "Opsi C salah karena volatile tidak melakukan blocking atau mutual exclusion locking.",
      "Opsi D salah karena volatile tidak berhubungan dengan persistensi disk.")

add_q(57, "Java Core",
      "Mengapa operasi 'count++' tidak thread-safe meskipun variabel 'count' telah dideklarasikan sebagai 'volatile'?",
      {"A": "Karena operasi 'count++' terdiri dari tiga langkah instruksi terpisah: read, modify, dan write yang tidak bersifat atomic",
       "B": "Karena tipe data primitif tidak mendukung multi-threading",
       "C": "Karena volatile hanya bekerja pada objek class, bukan integer primitif",
       "D": "Karena compiler Java otomatis menghapus volatile pada operasi matematika"},
      "A",
      "Operasi 'count++' adalah kombinasi: (1) membaca nilai count, (2) menambah 1, (3) menulis kembali ke memori. Di antara ketiga langkah ini, thread lain dapat menginterupsi, menimbulkan race condition (lost update). Untuk atomicitas gunakan AtomicInteger.",
      "Opsi A benar karena mengidentifikasi non-atomic read-modify-write cycle.",
      "Opsi B salah karena tipe primitif didukung di multithreading dengan atomic classes atau sinkronisasi.",
      "Opsi C salah karena volatile dapat diterapkan pada tipe data primitif.",
      "Opsi D salah karena compiler mempertahankan semantics volatile.")

add_q(58, "Java Core",
      "Dalam interface CompletableFuture di Java 8+, method manakah yang digunakan untuk merangkai tugas asynchronous lanjutan yang menerima hasil dari tugas sebelumnya dan mengembalikan CompletableFuture baru?",
      {"A": "thenCompose()",
       "B": "thenApply()",
       "C": "thenAccept()",
       "D": "join()"},
      "A",
      "thenCompose() digunakan untuk monadic composition (serupa flatMap), di mana fungsi callback mengembalikan CompletableFuture lain, menghindari bersarangnya Future (CompletableFuture<CompletableFuture<T>>).",
      "Opsi A benar karena thenCompose meratakan asynchronous pipeline.",
      "Opsi B salah karena thenApply (seperti map) untuk fungsi transformasi synchronous biasa yang mengembalikan nilai langsung.",
      "Opsi C salah karena thenAccept hanya mengonsumsi hasil (Consumer) tanpa mengembalikan nilai (mengembalikan CompletableFuture<Void>).",
      "Opsi D salah karena join() adalah operasi blocking untuk menunggu dan mengambil hasil.")

add_q(59, "Java Core",
      "Apa keuntungan utama menggunakan ReentrantLock dibandingkan blok 'synchronized' bawaan Java?",
      {"A": "Mendukung fitur tryLock() dengan batas timeout, interruptible lock acquisition, dan keadilan penjadwalan (fairness policy)",
       "B": "Tidak perlu dipanggil di dalam blok finally untuk melepaskan kuncinya",
       "C": "Bisa mengunci objek di JVM yang berbeda melalui network",
       "D": "Memiliki konsumsi memori nol dan tidak memerlukan objek instance"},
      "A",
      "ReentrantLock dari package java.util.concurrent.locks menawarkan fleksibilitas tingkat lanjut yang tidak dimiliki blok synchronized, seperti tryLock() dengan timeout, lockInterruptibly(), fair lock policy, dan multiple Condition per lock.",
      "Opsi A benar karena merangkum fitur unggulan ReentrantLock.",
      "Opsi B salah karena ReentrantLock justru WAJIB dilepaskan secara manual di dalam blok finally (lock.unlock()).",
      "Opsi C salah karena ReentrantLock hanya bekerja lokal pada satu proses JVM (untuk distributed lock gunakan Redis/Redisson atau Zookeeper).",
      "Opsi D salah karena ReentrantLock adalah objek biasa di heap.")

add_q(60, "Java Core",
      "Apa yang terjadi ketika dua objek memiliki nilai 'hashCode()' yang sama, tetapi 'equals()' mengembalikan false saat dimasukkan ke dalam HashMap?",
      {"A": "Keduanya akan disimpan di bucket yang sama sebagai node berantai (collision list atau tree node)",
       "B": "Objek kedua akan menimpa (overwrite) objek pertama",
       "C": "HashMap akan melempar exception DuplicateKeyException",
       "D": "Objek kedua akan dibuang tanpa peringatan"},
      "A",
      "Kondisi ini disebut hash collision. HashMap akan menempatkan entry baru ke dalam bucket yang sama dengan entry lama, membentuk linked list (atau tree jika sudah melebihi ambang batas) tanpa menimpa entry lama karena equals() bernilai false.",
      "Opsi A benar karena mendeskripsikan mekanisme resolusi hash collision pada separate chaining.",
      "Opsi B salah karena penimpaan hanya terjadi jika equals() bernilai true.",
      "Opsi C salah karena HashMap mengizinkan collision dan tidak melempar exception.",
      "Opsi D salah karena kedua entry tetap tersimpan dengan selamat di map.")

add_q(61, "Java Core",
      "Dalam Stream API, collector apakah yang digunakan untuk mengelompokkan koleksi objek berdasarkan atribut tertentu menjadi Map<K, List<V>>?",
      {"A": "Collectors.groupingBy()",
       "B": "Collectors.partitioningBy()",
       "C": "Collectors.toMap()",
       "D": "Collectors.summarizingInt()"},
      "A",
      "Collectors.groupingBy() mengelompokkan elemen stream berdasarkan fungsi klasifikasi dan menghasilkan Map dengan kunci berupa hasil klasifikasi dan nilai berupa List elemen yang cocok.",
      "Opsi A benar karena groupingBy adalah collector standar untuk SQL-like GROUP BY.",
      "Opsi B salah karena partitioningBy mengelompokkan khusus menjadi dua grup berdasarkan kondisi boolean (Map<Boolean, List<V>>).",
      "Opsi C salah karena toMap memetakan elemen 1:1 dan akan melempar IllegalStateException jika ada duplikasi key.",
      "Opsi D salah karena summarizingInt menghasilkan ringkasan statistik (count, sum, min, max, average).")

add_q(62, "Java Core",
      "Apa tujuan utama dari fitur Record (diperkenalkan sebagai fitur standar di Java 16)?",
      {"A": "Menyediakan cara ringkas untuk mendefinisikan kelas pembawa data immutable dengan getter, equals(), hashCode(), dan toString() otomatis",
       "B": "Menggantikan seluruh fungsionalitas database relasional di memori Java",
       "C": "Membuat kelas yang dapat mewarisi (extend) banyak superclass",
       "D": "Mengotomatisasi mapping REST API ke controller"},
      "A",
      "Java Record (record Point(int x, int y) {}) adalah kelas pembawa data transparan dan immutable, di mana compiler secara otomatis menghasilkan private final field, canonical constructor, accessor method, equals, hashCode, dan toString.",
      "Opsi A benar karena merangkum esensi dan keuntungan Java Records.",
      "Opsi B salah karena Record bukan sistem database.",
      "Opsi C salah karena Record secara implisit meng-extend java.lang.Record dan tidak boleh meng-extend class lain.",
      "Opsi D salah karena Record adalah fitur bahasa inti, bukan framework web.")

add_q(63, "Java Core",
      "Perhatikan method: list.parallelStream().forEach(System.out::println);. Masalah apa yang paling mungkin terjadi dibandingkan stream serial?",
      {"A": "Urutan pencetakan elemen tidak terjamin dan dapat berantakan",
       "B": "Stream otomatis gagal dengan UnsupportedOperationException",
       "C": "Semua elemen akan dicetak dua kali",
       "D": "JVM akan kehabisan memori seketika"},
      "A",
      "parallelStream() membagi pekerjaan ke thread pool ForkJoinPool.commonPool(). Karena thread mengeksekusi elemen secara paralel dan tanpa sinkronisasi urutan, forEach() akan mencetak elemen tanpa urutan yang pasti. Jika urutan penting, gunakan forEachOrdered().",
      "Opsi A benar karena paralelisme tidak menjamin traversal order.",
      "Opsi B salah karena parallelStream didukung penuh.",
      "Opsi C salah karena elemen diproses tepat sekali.",
      "Opsi D salah karena ForkJoinPool menggunakan thread yang proporsional dengan jumlah core CPU.")

add_q(64, "Java Core",
      "Struktur data koleksi apakah yang mengimplementasikan antrean prioritas berbasis binary heap di Java?",
      {"A": "PriorityQueue",
       "B": "ArrayDeque",
       "C": "LinkedList",
       "D": "TreeSet"},
      "A",
      "PriorityQueue adalah implementasi Queue berbasis min-heap tak terbatas, di mana elemen dengan prioritas tertinggi (atau nilai terendah menurut natural ordering / Comparator) selalu berada di kepala antrean (head) dan diambil dengan poll() dalam O(log n).",
      "Opsi A benar karena PriorityQueue mengimplementasikan heap-based priority queue.",
      "Opsi B salah karena ArrayDeque adalah double-ended queue berbasis resizable circular array tanpa prioritas.",
      "Opsi C salah karena LinkedList adalah linear FIFO queue biasa.",
      "Opsi D salah karena TreeSet adalah Set berbasis Red-Black Tree, bukan antrean Queue.")

add_q(65, "Java Core",
      "Apakah perbedaan utama antara thread-safe collection CopyOnWriteArrayList dan Collections.synchronizedList()?",
      {"A": "CopyOnWriteArrayList membuat salinan array baru setiap kali terjadi operasi mutasi (add/set/remove), sehingga sangat cepat untuk pembacaan bersamaan tanpa lock",
       "B": "CopyOnWriteArrayList mengunci list saat proses pembacaan iterator",
       "C": "synchronizedList tidak memerlukan sinkronisasi saat iterasi dengan for-each",
       "D": "CopyOnWriteArrayList melempar ConcurrentModificationException saat diiterasi sambil dimodifikasi"},
      "A",
      "CopyOnWriteArrayList menyalin seluruh array underlying saat ada penulisan data. Iterator-nya bekerja pada snapshot array saat iterator dibuat, sehingga iterator tidak pernah melempar ConcurrentModificationException dan operasi read berjalan bebas lock.",
      "Opsi A benar karena snapshot array memungkinkan concurrent reading dengan throughput maksimal.",
      "Opsi B salah karena operasi read pada CopyOnWriteArrayList sama sekali tidak membutuhkan lock.",
      "Opsi C salah karena iterasi pada synchronizedList WAJIB disinkronkan secara manual di dalam blok synchronized(list).",
      "Opsi D salah karena iterator CopyOnWriteArrayList tidak pernah melempar ConcurrentModificationException.")

add_q(66, "Java Core",
      "Apa kegunaan dari class AtomicInteger dibandingkan variabel integer biasa di Java?",
      {"A": "Menyediakan operasi atomik seperti incrementAndGet() dan compareAndSet() berbasis hardware CPU CAS (Compare-And-Swap) tanpa overhead lock",
       "B": "Menyimpan angka bilangan bulat dengan kapasitas tak terbatas melampaui 64-bit",
       "C": "Menjamin angka selalu positif",
       "D": "Mengonversi angka menjadi string JSON secara otomatis"},
      "A",
      "AtomicInteger memanfaatkan instruksi tingkat CPU Compare-And-Swap (CAS) untuk melakukan modifikasi nilai secara thread-safe tanpa menggunakan blocking lock (lock-free thread-safety).",
      "Opsi A benar karena atomic operations didasarkan pada mekanisme CAS non-blocking.",
      "Opsi B salah karena kapasitas tak terbatas adalah fungsi dari BigInteger.",
      "Opsi C salah karena AtomicInteger dapat menampung nilai negatif layaknya integer biasa.",
      "Opsi D salah karena konversi JSON dilakukan oleh library seperti Jackson.")

add_q(67, "Java Core",
      "Di Java, mengapa method wait(), notify(), dan notifyAll() didefinisikan di class java.lang.Object dan bukan di class Thread?",
      {"A": "Karena mekanisme wait dan notify terikat pada monitor lock yang dimiliki oleh setiap objek di Java, bukan pada thread itu sendiri",
       "B": "Karena class Thread tidak memiliki akses ke memori heap",
       "C": "Hanya karena alasan historis tanpa dasar arsitektural",
       "D": "Agar method tersebut dapat di-override di interface"},
      "A",
      "Di Java, setiap objek memiliki monitor/intrinsic lock. Thread melepaskan atau menunggu giliran pada monitor lock objek tertentu (shared resource), sehingga method sinkronisasi ini melekat pada objek yang dipantau (Object monitor).",
      "Opsi A benar karena intrinsic lock berada pada level instance Object.",
      "Opsi B salah karena instance Thread adalah objek Java normal di heap.",
      "Opsi C salah karena ini adalah keputusan desain fundamental arsitektur monitor Java.",
      "Opsi D salah karena method ini final dan tidak boleh di-override.")

add_q(68, "Java Core",
      "Apa fungsi dari ThreadLocal di Java?",
      {"A": "Menyediakan variabel yang nilainya terisolasi dan mandiri untuk setiap thread yang mengaksesnya",
       "B": "Mengirim variabel antar JVM melalui jaringan lokal",
       "C": "Mengubah thread biasa menjadi Daemon thread",
       "D": "Membatasi eksekusi thread hanya pada satu core CPU lokal"},
      "A",
      "ThreadLocal mengikat nilai variabel ke thread saat ini (Current Thread). Setiap thread memiliki salinan independennya sendiri dari variabel tersebut, sangat berguna untuk menyimpan context seperti UserContext atau TransactionContext dalam request-per-thread model.",
      "Opsi A benar karena ThreadLocal menyediakan per-thread variable storage.",
      "Opsi B salah karena ThreadLocal hanya ada di dalam memori satu proses JVM.",
      "Opsi C salah karena daemon status diatur via thread.setDaemon(true).",
      "Opsi D salah karena alokasi core CPU dikontrol oleh OS scheduler.")

add_q(69, "Java Core",
      "Perhatikan kode: Optional<User> opt = ...; Apa perbedaan antara opt.orElse(createUser()) dan opt.orElseGet(this::createUser)?",
      {"A": "orElse() selalu mengevaluasi argumen createUser() terlepas dari apakah Optional bernilai kosong atau tidak, sedangkan orElseGet() hanya mengeksekusi supplier createUser secara lazy saat Optional kosong",
       "B": "orElse() melempar NoSuchElementException jika kosong, orElseGet tidak",
       "C": "orElseGet() mengeksekusi method di thread terpisah",
       "D": "Keduanya persis sama karena compiler Java mengoptimasi keduanya menjadi bytecode identik"},
      "A",
      "orElse(T other) adalah pemanggilan method biasa yang mengevaluasi parameter 'other' secara eager. orElseGet(Supplier<? extends T>) menerima functional interface yang hanya dipanggil (lazy evaluation) ketika Optional benar-benar kosong, menghindari kalkulasi atau operasi I/O yang tidak perlu.",
      "Opsi A benar karena eager evaluation pada orElse dapat menyebabkan efek samping dan penurunan performa jika nilainya mahal untuk dibuat.",
      "Opsi B salah karena orElseThrow yang melempar exception.",
      "Opsi C salah karena orElseGet berjalan sinkron di thread pemanggil.",
      "Opsi D salah karena perilaku eksekusinya berbeda secara fundamental.")

add_q(70, "Java Core",
      "Apa dampak dari menangkap (catching) Throwable atau Error di blok catch aplikasi bisnis?",
      {"A": "Sangat tidak dianjurkan karena Error (seperti OutOfMemoryError, StackOverflowError) menandakan kondisi fatal JVM yang tidak seharusnya dipulihkan oleh kode aplikasi",
       "B": "Merupakan best practice agar aplikasi tidak pernah crash di server produksi",
       "C": "Wajib dilakukan untuk semua method yang mengakses koneksi database",
       "D": "Mempercepat waktu kompilasi program"},
      "A",
      "java.lang.Error dirancang untuk kondisi abnormal serius yang tidak boleh ditangani oleh aplikasi normal. Menangkap Error dapat membuat JVM berada dalam kondisi state rusak (corrupted state) yang berbahaya.",
      "Opsi A benar karena aplikasi seharusnya hanya menangani Exception dan turunannya.",
      "Opsi B salah karena menyembunyikan Error fatal justru memperparah kegagalan sistem.",
      "Opsi C salah karena koneksi database melempar SQLException (turunan Exception), bukan Error.",
      "Opsi D salah karena catch block dievaluasi saat runtime, tidak mempercepat kompilasi.")

add_q(71, "Java Core",
      "Dalam konsep Java Memory Model, di manakah objek hasil instansiasi 'new Object()' dan variabel referensi lokalnya masing-masing dialokasikan?",
      {"A": "Objek dialokasikan di Heap Memory, sedangkan variabel referensi lokal dialokasikan di Stack Memory thread pemanggil",
       "B": "Keduanya dialokasikan di Stack Memory",
       "C": "Keduanya dialokasikan di Metaspace",
       "D": "Objek di Stack dan referensi di Heap"},
      "A",
      "Di Java, semua objek dialokasikan di Heap Memory (dan dibersihkan oleh Garbage Collector), sedangkan primitive local variables dan referensi pointer objek dialokasikan di Stack frame dari thread yang mengeksekusi method.",
      "Opsi A benar karena membedakan alokasi Heap (objek) vs Stack (stack frame method & local reference).",
      "Opsi B salah karena objek tidak disimpan langsung di stack (kecuali jika ada optimasi escape analysis oleh JIT).",
      "Opsi C salah karena Metaspace menyimpan metadata class dan static variables.",
      "Opsi D salah karena posisi alokasi terbalik.")

add_q(72, "Java Core",
      "Fitur Sealed Classes (diperkenalkan di Java 17) digunakan untuk:",
      {"A": "Membatasi class atau interface mana saja yang diizinkan untuk meng-extend atau mengimplementasikannya secara eksplisit menggunakan keyword 'permits'",
       "B": "Mengenkripsi file .class dengan algoritma AES-256",
       "C": "Mencegah class diakses oleh unit test",
       "D": "Menonaktifkan refleksi runtime pada class tersebut"},
      "A",
      "Sealed Classes memungkinkan pengembang mengontrol pewarisan hierarki dengan mendeklarasikan secara eksplisit subclass mana yang diizinkan meng-extend-nya (contoh: public sealed class Shape permits Circle, Square).",
      "Opsi A benar karena Sealed Classes memberikan kontrol kepemilikan hierarki class.",
      "Opsi B salah karena Sealed Classes tidak mengenkripsi bytecode.",
      "Opsi C salah karena unit test tetap dapat mengakses class sesuai visibilitasnya.",
      "Opsi D salah karena refleksi tetap berfungsi pada sealed classes.")

add_q(73, "Java Core",
      "Manakah pernyataan yang BENAR mengenai method 'intern()' pada class String di Java?",
      {"A": "Memastikan string tersebut dimasukkan ke dalam String Constant Pool dan mengembalikan referensi kanonikal dari pool",
       "B": "Menghapus spasi di awal dan akhir string",
       "C": "Mengonversi string menjadi array byte UTF-8",
       "D": "Mengunci string agar tidak bisa dibaca oleh thread lain"},
      "A",
      "Method str.intern() mencari string dengan konten identik di String Constant Pool. Jika ditemukan, referensi pool dikembalikan; jika belum, string ditambahkan ke pool dan referensinya dikembalikan.",
      "Opsi A benar karena menjelaskan fungsi interning String ke pool memori JVM.",
      "Opsi B salah karena menghapus spasi menggunakan method .trim() atau .strip().",
      "Opsi C salah karena konversi byte menggunakan .getBytes(StandardCharsets.UTF_8).",
      "Opsi D salah karena string sudah immutable secara inheren.")

add_q(74, "Java Core",
      "Apa perbedaan mendasar antara fail-fast iterator dan fail-safe (weakly consistent) iterator di Java Collections?",
      {"A": "Fail-fast iterator melempar ConcurrentModificationException jika koleksi diubah secara struktural saat iterasi berjalan, sedangkan fail-safe iterator bekerja pada kloningan/snapshot data",
       "B": "Fail-fast mengulang pembacaan dari awal jika ada error",
       "C": "Fail-safe tidak bisa membaca data bernilai null",
       "D": "Fail-fast hanya digunakan untuk koleksi berbasis array berukuran tetap"},
      "A",
      "Fail-fast iterator (seperti pada ArrayList, HashMap) memeriksa flag modCount dan langsung melempar ConcurrentModificationException jika terdeteksi mutasi selama iterasi. Fail-safe iterator (seperti pada CopyOnWriteArrayList, ConcurrentHashMap) tidak melempar exception karena membaca snapshot data.",
      "Opsi A benar karena membedakan mekanisme modCount check vs snapshot iteration.",
      "Opsi B salah karena fail-fast tidak melakukan retry.",
      "Opsi C salah karena fail-safe mendukung pembacaan data sesuai spesifikasi tipe koleksinya.",
      "Opsi D salah karena fail-fast berlaku di berbagai tipe koleksi umum Java.")

add_q(75, "Java Core",
      "Apa fungsi dari method 'Thread.join()' dalam pemrograman concurrent Java?",
      {"A": "Menahan eksekusi thread pemanggil hingga thread target yang dipanggil .join() selesai dieksekusi",
       "B": "Menggabungkan dua thread menjadi satu thread bersama",
       "C": "Menyambungkan koneksi socket jaringan",
       "D": "Memaksa thread target untuk langsung berhenti seketika"},
      "A",
      "thread.join() membuat thread yang sedang berjalan (misal main thread) menunggu (state WAITING) sampai thread target selesai menyelesaikan pekerjaannya.",
      "Opsi A benar karena join() berfungsi menyinkronkan penyelesaian thread target.",
      "Opsi B salah karena thread tidak dapat dimerge secara fisik.",
      "Opsi C salah karena join bukan operasi socket.",
      "Opsi D salah karena penghentian thread menggunakan mekanisme interruption (thread.interrupt()).")

add_q(76, "Java Core",
      "Dalam arsitektur ThreadPoolExecutor, apa yang terjadi ketika work queue sudah penuh dan jumlah thread aktif telah mencapai 'maximumPoolSize'?",
      {"A": "Task baru akan ditolak oleh RejectedExecutionHandler sesuai policy (misal: AbortPolicy melempar RejectedExecutionException)",
       "B": "Aplikasi akan crash seketika dengan Segmentation Fault",
       "C": "Task baru akan otomatis menghapus task terlama di queue tanpa notifikasi apapun",
       "D": "ThreadPool akan membuat thread tak terbatas melebihi batas maksimum"},
      "A",
      "Ketika pool threads = maximumPoolSize dan antrean tugas (workQueue) berkapasitas penuh, penambahan task baru akan ditangani oleh RejectedExecutionHandler yang terpasang (default: AbortPolicy yang melempar RejectedExecutionException).",
      "Opsi A benar karena menjelaskan siklus penolakan task pada ThreadPoolExecutor.",
      "Opsi B salah karena JVM menangani kondisi ini di level aplikasi Java secara terkendali.",
      "Opsi C salah karena penghapusan task terlama hanya terjadi jika policy secara eksplisit diset ke DiscardOldestPolicy.",
      "Opsi D salah karena batas maximumPoolSize dihormati secara ketat.")

add_q(77, "Java Core",
      "Manakah antarmuka (interface) di package java.util.concurrent yang memiliki method 'V call() throws Exception' dan mengembalikan nilai hasil eksekusi?",
      {"A": "Callable<V>",
       "B": "Runnable",
       "C": "Supplier<V>",
       "D": "Consumer<V>"},
      "A",
      "Callable<V> mirip dengan Runnable tetapi method call()-nya dapat mengembalikan sebuah nilai bertipe V dan diperbolehkan mendeklarasikan checked exception.",
      "Opsi A benar karena Callable dirancang untuk asynchronous task yang mengembalikan nilai.",
      "Opsi B salah karena method run() milik Runnable mengembalikan void dan tidak boleh melempar checked exception.",
      "Opsi C salah karena Supplier adalah functional interface tanpa deklarasi throws Exception dan bukan primitif task executor concurrency secara langsung.",
      "Opsi D salah karena Consumer menerima argumen dan tidak mengembalikan nilai.")

add_q(78, "Java Core",
      "Apa fungsi dari keyword 'default' pada method di dalam sebuah interface Java (sejak Java 8)?",
      {"A": "Menyediakan implementasi method bawaan pada interface tanpa memaksa semua kelas yang sudah ada untuk meng-overridenya",
       "B": "Menjadikan method tersebut hanya dapat diakses di dalam package yang sama",
       "C": "Membuat method otomatis mengembalikan nilai null",
       "D": "Menjadikan interface tersebut sebagai FunctionalInterface"},
      "A",
      "Default method diperkenalkan di Java 8 untuk memungkinkan evolusi interface (seperti penambahan method stream() pada Collection) dengan backward-compatibility tanpa merusak ribuan library kelas pihak ketiga yang mengimplementasikannya.",
      "Opsi A benar karena default method menjaga kompatibilitas mundur saat interface ditambahkan method baru.",
      "Opsi B salah karena default method di interface selalu ber-modifier public.",
      "Opsi C salah karena default method memiliki body implementasi konkret yang ditentukan pembuat interface.",
      "Opsi D salah karena FunctionalInterface hanya boleh memiliki tepat satu abstract method, bukan karena adanya default method.")

add_q(79, "Java Core",
      "Perhatikan kode berikut: List<String> list = List.of(\"a\", \"b\"); list.add(\"c\");. Apa yang terjadi saat kode dijalankan?",
      {"A": "Melemparkan UnsupportedOperationException karena List.of() menghasilkan unmodifiable / immutable list",
       "B": "Elemen \"c\" berhasil ditambahkan sehingga list berukuran 3",
       "C": "Menghasilkan compile error karena method .add() tidak ada di interface List",
       "D": "Elemen pertama \"a\" akan digantikan oleh \"c\""},
      "A",
      "Factory method List.of(), Set.of(), dan Map.of() (diperkenalkan di Java 9) menghasilkan koleksi yang benar-benar immutable. Setiap pemanggilan method mutasi seperti add(), remove(), atau set() akan melempar java.lang.UnsupportedOperationException.",
      "Opsi A benar karena List.of() mengembalikan koleksi unmodifiable.",
      "Opsi B salah karena elemen tidak dapat ditambahkan.",
      "Opsi C salah karena method add() dideklarasikan di interface List.",
      "Opsi D salah karena tidak terjadi penggantian nilai.")

add_q(80, "Java Core",
      "Apakah tujuan utama dari metode 'System.identityHashCode(Object x)' di Java?",
      {"A": "Mengembalikan hashcode asli berdasarkan alamat memori bawaan JVM dari objek tersebut, terlepas dari apakah method hashCode() dioverride atau tidak",
       "B": "Menghasilkan string identitas KTP/Paspor pengguna",
       "C": "Menghitung hash SHA-256 dari seluruh atribut objek",
       "D": "Memastikan dua objek selalu dianggap sama oleh garbage collector"},
      "A",
      "System.identityHashCode(obj) mengembalikan nilai yang sama dengan apa yang dihasilkan oleh implementasi default java.lang.Object.hashCode(), mengabaikan kustomisasi method hashCode() yang mungkin dibuat pada kelas tersebut.",
      "Opsi A benar karena mengambil default identity hashcode asli objek.",
      "Opsi B salah karena bukan fungsi bisnis identitas personal.",
      "Opsi C salah karena bukan cryptographic hash.",
      "Opsi D salah karena tidak mempengaruhi algoritma GC.")

add_q(81, "Java Core",
      "Apa fungsi dari pattern matching for instanceof yang distandarisasi pada Java 16?",
      {"A": "Mengizinkan deklarasi variabel pola secara langsung tanpa perlu melakukan explicit casting manual (contoh: if (obj instanceof String s) { s.length(); })",
       "B": "Membuat objek baru bertipe String secara otomatis",
       "C": "Memvalidasi string format JSON",
       "D": "Mempercepat alokasi memori di heap"},
      "A",
      "Pattern matching for instanceof menyederhanakan kode idiomatik dengan menggabungkan pemeriksaan tipe dan casting dalam satu langkah deklarasi variabel pola (binding variable).",
      "Opsi A benar karena mengeliminasi boilerplate casting manual.",
      "Opsi B salah karena tidak membuat objek baru.",
      "Opsi C salah karena bukan parser JSON.",
      "Opsi D salah karena ini adalah fitur sintaksis compiler dan bytecode, bukan pengubah alokasi memori.")

add_q(82, "Java Core",
      "Pada mekanisme Exception Handling, apa yang dimaksud dengan 'Suppressed Exceptions' di try-with-resources?",
      {"A": "Exception sekunder yang terjadi saat penutupan otomatis resource (close()), yang disematkan ke exception primer blok try melalui method addSuppressed()",
       "B": "Exception yang sengaja diabaikan oleh compiler tanpa logging",
       "C": "Exception yang diubah menjadi peringatan compiler (warning)",
       "D": "Exception yang hanya terjadi pada level OS kernel"},
      "A",
      "Jika terjadi exception di dalam blok try dan terjadi lagi exception saat method close() dari resource dipanggil, exception dari close() tidak akan menimpa exception utama melainkan ditandai sebagai 'suppressed' dan dapat diakses melalui e.getSuppressed().",
      "Opsi A benar karena menjelaskan preservasi jejak exception sekunder oleh try-with-resources.",
      "Opsi B salah karena suppressed exception tidak diabaikan melainkan dicatat.",
      "Opsi C salah karena suppressed exception tetap berwujud objek Throwable.",
      "Opsi D salah karena berada di level runtime JVM.")

add_q(83, "Java Core",
      "Manakah pernyataan yang benar mengenai interface java.lang.AutoCloseable?",
      {"A": "Hanya memiliki satu method: 'void close() throws Exception' dan merupakan prasyarat tipe objek yang dapat digunakan di blok try-with-resources",
       "B": "Harus diimplementasikan bersamaan dengan Serializable",
       "C": "Hanya boleh digunakan untuk manipulasi file fisik di hard drive",
       "D": "Otomatis mematikan thread saat method close dipanggil"},
      "A",
      "AutoCloseable adalah interface dasar untuk semua resource yang harus ditutup saat tidak lagi digunakan, dan didesain khusus untuk mendukung sintaks try-with-resources Java 7+.",
      "Opsi A benar karena merupakan kontrak interface resmi AutoCloseable.",
      "Opsi B salah karena Serializable dan AutoCloseable independen.",
      "Opsi C salah karena dapat digunakan untuk socket jaringan, koneksi database, dan resource memori lainnya.",
      "Opsi D salah karena tidak bertugas mematikan thread.")

add_q(84, "Java Core",
      "Dalam operasi Stream API, apa perbedaan antara 'findFirst()' dan 'findAny()'?",
      {"A": "'findFirst()' selalu mengembalikan elemen pertama sesuai urutan encounter order, sedangkan 'findAny()' bebas mengembalikan elemen apa saja yang ditemukan lebih dulu terutama pada parallel stream untuk performa maksimal",
       "B": "'findFirst()' hanya bekerja pada Set, sedangkan 'findAny()' pada List",
       "C": "'findAny()' mengembalikan koleksi List, sedangkan 'findFirst()' mengembalikan Optional",
       "D": "Keduanya persis sama dalam segala kondisi baik serial maupun paralel"},
      "A",
      "Pada stream serial keduanya sering menghasilkan elemen yang sama, tetapi pada parallel stream 'findAny()' jauh lebih cepat karena thread yang pertama kali menemukan elemen yang cocok dapat langsung mengembalikannya tanpa harus menunggu thread yang memproses elemen awal.",
      "Opsi A benar karena membedakan determinisme urutan vs optimasi paralelisme non-deterministik.",
      "Opsi B salah karena keduanya bekerja pada sembarang Stream.",
      "Opsi C salah karena keduanya mengembalikan tipe Optional<T>.",
      "Opsi D salah karena perilakunya berbeda signifikan pada parallel stream.")

add_q(85, "Java Core",
      "Bagaimanakah cara mencegah terjadinya Deadlock dalam aplikasi multi-threaded di Java?",
      {"A": "Memastikan semua thread selalu mengakuisisi multiple lock dengan urutan hierarki yang sama persis (lock ordering konsisten) atau menggunakan tryLock() dengan timeout",
       "B": "Menghapus semua blok synchronized dari seluruh kode aplikasi",
       "C": "Menambah jumlah core CPU di server",
       "D": "Membuat semua method menjadi static"},
      "A",
      "Deadlock terjadi ketika terjadi siklus ketergantungan saling tunggu antar lock (Circular Wait). Cara pencegahan paling fundamental adalah memaksakan urutan penguncian yang konsisten secara global atau menggunakan timeout saat meminta lock.",
      "Opsi A benar karena memutus kondisi Circular Wait dari kriteria Coffman deadlock.",
      "Opsi B salah karena menghapus sinkronisasi akan menyebabkan race condition fatal dan korupsi data.",
      "Opsi C salah karena menambah core CPU tidak mencegah deadlock logika perangkat lunak.",
      "Opsi D salah karena method static tetap memiliki class monitor lock yang bisa menyebabkan deadlock jika saling memanggil.")

print(f"Total so far: {len(questions)}")
with open("scripts/data_java_intermediate.json", "w", encoding="utf-8") as f:
    json.dump(questions, f, ensure_ascii=False, indent=2)
