import json

questions = []

def add_q(id_num, level, topic, qtype, q, opts, ans, exp_corr, exp_a, exp_b, exp_c, exp_d, code=None):
    qid = f"FT-{id_num:03d}"
    item = {
        "id": qid,
        "level": level,
        "topic": topic,
        "questionType": qtype,
        "question": q,
        "options": opts,
        "answer": ans,
        "explanation": {
            "correct": exp_corr,
            "A": exp_a,
            "B": exp_b,
            "C": exp_c,
            "D": exp_d
        },
        "mode": "test",
        "jobId": "fullstack"
    }
    if code:
        item["code"] = code
    questions.append(item)

# -------------------------------------------------------------
# 1. BEGINNER TEST QUESTIONS (FT-001 to FT-030: 30 questions)
# -------------------------------------------------------------
add_q(1, "beginner", "TypeScript", "concept",
      "Manakah yang BUKAN merupakan tipe data primitif bawaan di JavaScript/TypeScript?",
      {"A": "string", "B": "number", "C": "array", "D": "boolean"},
      "C",
      "Tipe primitif di TypeScript adalah string, number, boolean, null, undefined, symbol, dan bigint. Array adalah tipe referensi (objek).",
      "Opsi A salah karena string adalah tipe data primitif.",
      "Opsi B salah karena number adalah tipe data primitif.",
      "Opsi C benar karena array adalah tipe data non-primitif (objek referensi).",
      "Opsi D salah karena boolean adalah tipe data primitif.")

add_q(2, "beginner", "TypeScript", "output",
      "Apa tipe data hasil kompilasi dari ekspresi `typeof []` di TypeScript/JavaScript?",
      {"A": "\"object\"", "B": "\"array\"", "C": "\"list\"", "D": "\"undefined\""},
      "A",
      "Operator typeof pada array di JavaScript selalu mengembalikan string 'object' karena array merupakan turunan dari prototipe Object.",
      "Opsi A benar karena array dievaluasi sebagai tipe objek oleh operator typeof.",
      "Opsi B salah karena tidak ada tipe kembalian 'array' pada operator typeof bawaan.",
      "Opsi C salah karena 'list' bukan tipe pengembalian typeof.",
      "Opsi D salah karena array yang diinisialisasi bukan undefined.",
      code="const arr = [1, 2, 3];\nconsole.log(typeof arr);")

add_q(3, "beginner", "TypeScript", "completion",
      "Lengkapi tipe parameter fungsi berikut agar menerima angka atau string (Union Type):",
      {"A": "id: string | number", "B": "id: string & number", "C": "id: string or number", "D": "id: (string, number)"},
      "A",
      "Union Type menggunakan operator pipa (`|`) untuk mengizinkan suatu variabel menerima salah satu dari beberapa tipe data yang didefinisikan.",
      "Opsi A benar karena `string | number` adalah sintaks resmi Union Type di TypeScript.",
      "Opsi B salah karena `&` adalah Intersection Type.",
      "Opsi C salah karena 'or' bukan operator tipe di TypeScript.",
      "Opsi D salah karena tanda kurung koma bukan sintaks union.",
      code="function printId(___) {\n  console.log(id);\n}")

add_q(4, "beginner", "TypeScript", "debug",
      "Kode berikut menghasilkan compile error di TypeScript: 'Type number is not assignable to type string'. Bagian mana yang harus diperbaiki?",
      {"A": "Ubah tipe variabel `code` menjadi `string | number` atau konversi angka menjadi string",
       "B": "Ganti keyword const menjadi var",
       "C": "Hapus tanda titik koma",
       "D": "Ubah nama variabel menjadi number"},
      "A",
      "Variabel `code` diberi tipe `string`, sehingga memasukkan nilai angka `404` ditolak oleh static type checker. Solusinya adalah mengubah tipe menjadi union atau mengubah nilai menjadi `'404'`.",
      "Opsi A benar karena mengatasi ketidakcocokan tipe antara string dan number.",
      "Opsi B salah karena jenis deklarasi variabel tidak mengubah type checking.",
      "Opsi C salah karena titik koma tidak berpengaruh pada error tipe.",
      "Opsi D salah karena nama variabel tidak menentukan tipe datanya.",
      code="let code: string = \"200\";\ncode = 404; // Error")

add_q(5, "beginner", "TypeScript", "best-practice",
      "Manakah cara yang paling direkomendasikan untuk mendeklarasikan tipe bentuk objek (object shape) terbuka di TypeScript?",
      {"A": "Menggunakan `interface`", "B": "Menggunakan tipe `any`", "C": "Menggunakan string literal", "D": "Tanpa deklarasi tipe sama sekali"},
      "A",
      "Interface adalah cara standar dan paling direkomendasikan untuk mendefinisikan bentuk objek karena mendukung ekstensibilitas (`extends`) dan deklarasi merging.",
      "Opsi A benar karena interface adalah standar deklarasi bentuk objek.",
      "Opsi B salah karena any menghilangkan manfaat type safety.",
      "Opsi C salah karena string literal tidak mendefinisikan struktur objek.",
      "Opsi D salah karena ketiadaan tipe berisiko menimbulkan runtime error.",
      code="interface UserProfile {\n  id: number;\n  name: string;\n  email: string;\n}")

add_q(6, "beginner", "React + TypeScript", "concept",
      "Apa fungsi utama dari hook `useState` di React?",
      {"A": "Menyimpan dan mengelola state lokal pada functional component serta memicu re-render saat nilai state diperbarui",
       "B": "Menghubungkan aplikasi ke database MySQL secara langsung",
       "C": "Menjalankan kompilasi TypeScript di browser",
       "D": "Mengatur konfigurasi server backend"},
      "A",
      "`useState` adalah hook dasar React yang memungkinkan functional component memiliki internal state yang reaktif terhadap interaksi pengguna.",
      "Opsi A benar sesuai definisi dan tujuan hook useState.",
      "Opsi B salah karena React tidak terhubung langsung ke database tanpa API.",
      "Opsi C salah karena kompilasi dilakukan oleh bundler build tool.",
      "Opsi D salah karena React berjalan di sisi klien (frontend).")

add_q(7, "beginner", "React + TypeScript", "output",
      "Apa yang ditampilkan di layar oleh komponen Counter berikut saat tombol diklik sekali?",
      {"A": "\"Total: 1\"", "B": "\"Total: 0\"", "C": "\"Total: 2\"", "D": "Tampilan kosong"},
      "A",
      "Klik tombol memicu `setCount(prev => prev + 1)` yang mengubah nilai count dari 0 menjadi 1, memicu render ulang dengan tampilan 'Total: 1'.",
      "Opsi A benar karena 0 + 1 = 1.",
      "Opsi B salah karena state telah diperbarui.",
      "Opsi C salah karena fungsi updater hanya menambahkan 1.",
      "Opsi D salah karena komponen me-return JSX yang valid.",
      code="function Counter() {\n  const [count, setCount] = useState(0);\n  return <button onClick={() => setCount(c => c + 1)}>Total: {count}</button>;\n}")

add_q(8, "beginner", "React + TypeScript", "completion",
      "Lengkapi tipe props komponen Button berikut agar menerima prop `label` berupa teks dan `disabled` opsional berupa boolean:",
      {"A": "interface ButtonProps { label: string; disabled?: boolean; }",
       "B": "interface ButtonProps { label: text; disabled: optional; }",
       "C": "type ButtonProps = { label: any; disabled: any };",
       "D": "interface ButtonProps { label: String; disabled: Boolean; }"},
      "A",
      "Di TypeScript, tipe primitif menggunakan huruf kecil (`string`, `boolean`) dan properti opsional ditandai dengan tanda tanya (`?:`).",
      "Opsi A benar sesuai standar penulisan interface props di React + TypeScript.",
      "Opsi B salah karena text dan optional bukan tipe data di TypeScript.",
      "Opsi C salah karena any menghilangkan type safety.",
      "Opsi D salah karena pembungkus objek String/Boolean tidak disarankan untuk tipe props primitif.",
      code="interface ButtonProps {\n  ___\n}\nexport const Button: React.FC<ButtonProps> = ({ label, disabled = false }) => ...")

add_q(9, "beginner", "React + TypeScript", "debug",
      "Komponen berikut tidak memperbarui angka saat tombol diklik. Apa penyebab bug tersebut?",
      {"A": "Variabel count adalah variabel lokal biasa dan bukan state React, sehingga mutasi `count++` tidak memicu re-render komponen",
       "B": "Tombol tidak memiliki ID",
       "C": "Sintaks JSX div salah",
       "D": "Fungsi handleClick harus berjenis async"},
      "A",
      "Di React, pembaruan tampilan hanya dipicu oleh pembaruan state (`useState`) atau props. Memodifikasi variabel lokal biasa tidak akan pernah memicu siklus re-render.",
      "Opsi A benar karena variabel biasa tidak reaktif di siklus render React.",
      "Opsi B salah karena atribut ID tidak memengaruhi reaktifitas.",
      "Opsi C salah karena JSX valid.",
      "Opsi D salah karena handler tidak memerlukan async untuk kalkulasi angka.",
      code="function BrokenCounter() {\n  let count = 0;\n  const handleClick = () => { count++; };\n  return <button onClick={handleClick}>{count}</button>;\n}")

add_q(10, "beginner", "React + TypeScript", "best-practice",
      "Manakah cara yang benar untuk merender daftar array di React dengan atribut `key` yang stabil?",
      {"A": "users.map(u => <li key={u.id}>{u.name}</li>)",
       "B": "users.map((u, i) => <li key={Math.random()}>{u.name}</li>)",
       "C": "users.map(u => <li>{u.name}</li>)",
       "D": "users.forEach(u => <li key={u.id}>{u.name}</li>)"},
      "A",
      "Menggunakan ID unik permanen dari database (`u.id`) sebagai prop `key` memberikan stabilitas pada algoritma rekonsiliasi DOM React.",
      "Opsi A benar karena menggunakan identifier stabil dari data model.",
      "Opsi B salah karena Math.random() menghasilkan key baru di setiap render yang merusak DOM state.",
      "Opsi C salah karena ketiadaan key memicu warning di console browser.",
      "Opsi D salah karena forEach tidak mengembalikan array elemen JSX.",
      code="const users = [{ id: 1, name: 'Ali' }, { id: 2, name: 'Budi' }];\nreturn <ul>{___}</ul>;")

add_q(11, "beginner", "Java Spring Boot", "concept",
      "Anotasi apakah di Spring Boot yang menandai sebuah kelas sebagai Controller sekaligus menyematkan `@ResponseBody` pada seluruh method-nya?",
      {"A": "@RestController", "B": "@Controller", "C": "@Service", "D": "@Component"},
      "A",
      "`@RestController` adalah anotasi gabungan dari `@Controller` dan `@ResponseBody` untuk membangun RESTful web service yang mengembalikan data JSON/XML.",
      "Opsi A benar karena @RestController mengotomatisasi serialisasi response body.",
      "Opsi B salah karena @Controller biasa membutuhkan @ResponseBody manual pada tiap method jika ingin return data JSON.",
      "Opsi C salah karena @Service untuk business logic layer.",
      "Opsi D salah karena @Component adalah stereotype umum.")

add_q(12, "beginner", "Java Spring Boot", "output",
      "Apa status code HTTP default yang dikembalikan oleh method Controller Spring Boot jika method mengembalikan objek berhasil tanpa kustomisasi response status?",
      {"A": "200 OK", "B": "201 Created", "C": "204 No Content", "D": "202 Accepted"},
      "A",
      "Secara default di Spring Web MVC, method endpoint yang sukses dieksekusi akan mengembalikan HTTP Status Code 200 OK.",
      "Opsi A benar karena 200 OK adalah status bawaan HTTP respon sukses di Spring MVC.",
      "Opsi B salah karena 201 harus ditentukan secara eksplisit.",
      "Opsi C salah karena 204 untuk respon tanpa body konten.",
      "Opsi D salah karena 202 untuk request yang diterima untuk pemrosesan asinkron.")

add_q(13, "beginner", "Java Spring Boot", "completion",
      "Lengkapi anotasi Spring Web berikut untuk menangani HTTP GET request pada path `/api/products`:",
      {"A": "@GetMapping(\"/api/products\")", "B": "@PostMapping(\"/api/products\")", "C": "@FetchMapping(\"/api/products\")", "D": "@ReadMapping(\"/api/products\")"},
      "A",
      "`@GetMapping` adalah shortcut annotation resmi Spring untuk menangani HTTP GET requests.",
      "Opsi A benar karena @GetMapping menangani request HTTP GET.",
      "Opsi B salah karena @PostMapping untuk HTTP POST.",
      "Opsi C salah karena bukan anotasi Spring.",
      "Opsi D salah karena bukan anotasi resmi.")

add_q(14, "beginner", "Java Spring Boot", "debug",
      "Aplikasi melempar `NullPointerException` saat memanggil service di controller. Kode yang ditulis: `private UserService service;`. Anotasi atau konstruktor apa yang lupa dibuat?",
      {"A": "Constructor Injection dengan `public UserController(UserService service) { this.service = service; }` atau anotasi `@Autowired`",
       "B": "Anotasi @Entity pada controller",
       "C": "Keyword static pada UserService",
       "D": "Method harus bertipe void"},
      "A",
      "Field dependensi tidak boleh dibiarkan null. Developer harus menyuntikkan dependensi menggunakan Constructor Injection (rekomendasi) atau `@Autowired` agar Spring IoC mengisinya dengan instance bean yang valid.",
      "Opsi A benar karena menginisialisasi dependency injection dengan tepat.",
      "Opsi B salah karena controller bukan entitas database.",
      "Opsi C salah karena static field membypass container injection.",
      "Opsi D salah karena return type tidak memengaruhi inisialisasi bean.",
      code="@RestController\npublic class UserController {\n  private UserService service; // Null! Belum di-inject\n}")

add_q(15, "beginner", "Java Spring Boot", "best-practice",
      "Manakah pendekatan Dependency Injection yang PALING direkomendasikan di Spring Boot modern?",
      {"A": "Constructor Injection dengan field bertipe `private final`",
       "B": "Field Injection menggunakan `@Autowired` langsung pada private field",
       "C": "Setter Injection tanpa verifikasi null",
       "D": "Membuat objek secara manual dengan keyword `new` di dalam controller"},
      "A",
      "Constructor Injection menjamin immutability (`final`), mempermudah unit testing (dapat memasukkan mock tanpa reflection), dan mencegah NullPointerException.",
      "Opsi A benar karena Constructor Injection adalah standar resmi Spring.",
      "Opsi B salah karena field injection menyulitkan unit test murni.",
      "Opsi C salah karena setter injection membuat dependensi dapat diubah (mutable).",
      "Opsi D salah karena keyword new menghilangkan manajemen bean oleh Spring IoC.")

add_q(16, "beginner", "JPA & Hibernate", "concept",
      "Anotasi JPA apakah yang digunakan untuk menandai kolom Primary Key pada sebuah kelas `@Entity`?",
      {"A": "@Id", "B": "@PrimaryKey", "C": "@Key", "D": "@ColumnId"},
      "A",
      "Anotasi `@Id` adalah anotasi standar JPA untuk menetapkan field sebagai identifier utama / primary key suatu entitas.",
      "Opsi A benar karena @Id adalah anotasi resmi JPA untuk primary key.",
      "Opsi B salah karena bukan anotasi standar JPA.",
      "Opsi C salah karena bukan anotasi JPA.",
      "Opsi D salah karena bukan anotasi resmi.")

add_q(17, "beginner", "JPA & Hibernate", "output",
      "Apa hasil kembalian dari method `userRepository.findById(1L)` jika data dengan ID 1 tidak ditemukan di database?",
      {"A": "Optional.empty()", "B": "null", "C": "Exception EntityNotFoundException", "D": "Objek User kosong"},
      "A",
      "Spring Data JPA mengembalikan `Optional.empty()` jika record tidak ditemukan, memungkinkan penanganan null-safe tanpa melempar exception secara langsung.",
      "Opsi A benar karena Optional.empty() merepresentasikan ketiadaan data pada findById.",
      "Opsi B salah karena findById tidak mengembalikan nilai null mentah.",
      "Opsi C salah karena findById tidak langsung melempar exception saat data absen.",
      "Opsi D salah karena tidak membuat objek dummy.")

add_q(18, "beginner", "JPA & Hibernate", "completion",
      "Lengkapi deklarasi interface repository berikut agar mengelola entitas User dengan primary key bertipe Long:",
      {"A": "public interface UserRepository extends JpaRepository<User, Long>",
       "B": "public interface UserRepository implements JpaRepository<User, Long>",
       "C": "public interface UserRepository extends JpaRepository<Long, User>",
       "D": "public class UserRepository extends JpaRepository<User, Long>"},
      "A",
      "Di Java, interface mewarisi interface lain menggunakan kata kunci `extends`, dengan parameter generic `<Entity, IdType>`.",
      "Opsi A benar karena menggunakan kata kunci extends dengan urutan generic yang tepat.",
      "Opsi B salah karena interface tidak menggunakan kata kunci implements.",
      "Opsi C salah karena urutan generic terbalik.",
      "Opsi D salah karena repository Spring Data dideklarasikan sebagai interface, bukan class.")

add_q(19, "beginner", "JPA & Hibernate", "debug",
      "Entitas Book berikut melempar exception saat aplikasi dijalankan: 'No identifier specified for entity'. Apa perbaikannya?",
      {"A": "Tambahkan anotasi `@Id` pada field `id`",
       "B": "Ubah tipe id menjadi String",
       "C": "Ganti nama kelas menjadi TblBook",
       "D": "Tambahkan method toString()"},
      "A",
      "Spesifikasi JPA mewajibkan setiap kelas yang dianotasi `@Entity` memiliki setidaknya satu atribut pengenal unik yang ditandai dengan `@Id`.",
      "Opsi A benar karena setiap entitas JPA wajib memiliki @Id.",
      "Opsi B salah karena tipe Long adalah tipe ID yang valid.",
      "Opsi C salah karena nama kelas bebas.",
      "Opsi D salah karena method toString tidak memengaruhi mapping JPA.",
      code="@Entity\npublic class Book {\n  private Long id;\n  private String title;\n}")

add_q(20, "beginner", "JPA & Hibernate", "best-practice",
      "Strategi pembuatan ID otomatis manakah yang paling direkomendasikan untuk database MySQL yang menggunakan AUTO_INCREMENT?",
      {"A": "GenerationType.IDENTITY", "B": "GenerationType.SEQUENCE", "C": "GenerationType.TABLE", "D": "GenerationType.UUID"},
      "A",
      "`GenerationType.IDENTITY` mengandalkan fitur kolom auto-increment database secara langsung, yang merupakan fitur bawaan MySQL.",
      "Opsi A benar karena IDENTITY adalah pemetaan alami kolom auto-increment MySQL.",
      "Opsi B salah karena MySQL tidak memiliki objek sequence bawaan pra-versi 8.",
      "Opsi C salah karena TABLE generation memiliki overhead I/O tinggi.",
      "Opsi D salah karena UUID adalah strategi nilai acak non-numerik.")

add_q(21, "beginner", "PostgreSQL/MySQL", "concept",
      "Perintah SQL manakah yang digunakan untuk mengambil data dari tabel?",
      {"A": "SELECT", "B": "GET", "C": "FETCH", "D": "READ"},
      "A",
      "`SELECT` adalah perintah inti Data Query Language (DQL) di SQL standar untuk membaca dan menampilkan data dari tabel database.",
      "Opsi A benar karena SELECT adalah perintah standar pembacaan data SQL.",
      "Opsi B salah karena GET adalah kata kerja HTTP, bukan SQL.",
      "Opsi C salah karena FETCH adalah klausul paginasi / cursor di SQL.",
      "Opsi D salah karena READ bukan perintah SQL.")

add_q(22, "beginner", "PostgreSQL/MySQL", "output",
      "Berapa banyak baris yang dihasilkan oleh query `SELECT COUNT(*) FROM users;` jika tabel users memiliki 15 baris data?",
      {"A": "1 baris berisi angka 15", "B": "15 baris", "C": "0 baris", "D": "Error"},
      "A",
      "Fungsi agregat `COUNT(*)` merangkum seluruh baris tabel menjadi satu baris hasil tunggal yang berisi jumlah total record (yaitu 15).",
      "Opsi A benar karena fungsi agregasi mengembalikan 1 baris hasil ringkasan.",
      "Opsi B salah karena fungsi agregasi meremukkan baris menjadi satu nilai total.",
      "Opsi C salah karena ada 15 baris data.",
      "Opsi D salah karena sintaks COUNT(*) valid.")

add_q(23, "beginner", "PostgreSQL/MySQL", "completion",
      "Lengkapi klausa SQL berikut untuk menyaring produk dengan harga lebih besar dari 50.000:",
      {"A": "WHERE price > 50000", "B": "HAVING price > 50000", "C": "FILTER price > 50000", "D": "IF price > 50000"},
      "A",
      "Klausa `WHERE` digunakan untuk menyaring baris individual sebelum pengelompokan atau agregasi.",
      "Opsi A benar karena WHERE adalah filter baris standar di SQL.",
      "Opsi B salah karena HAVING digunakan untuk memfilter hasil agregasi setelah GROUP BY.",
      "Opsi C salah karena FILTER bukan klausa pengganti WHERE di ANSI SQL.",
      "Opsi D salah karena IF bukan klausul filter query SQL.")

add_q(24, "beginner", "PostgreSQL/MySQL", "debug",
      "Query berikut bermaksud mencari user dengan nama 'Andi', tetapi melempar syntax error di database. Apa kesalahannya?",
      {"A": "Nilai string literal 'Andi' harus diapit tanda petik satu (single quote), bukan tanda petik dua",
       "B": "Nama tabel harus huruf besar",
       "C": "Klausa WHERE harus diganti SELECT",
       "D": "Operator '=' harus diganti '=='"},
      "A",
      "Di SQL standar, tanda petik ganda (`\"`) digunakan untuk identifier nama tabel/kolom, sedangkan literal teks string WAJIB diapit tanda petik tunggal (`'`).",
      "Opsi A benar karena string literal di SQL menggunakan tanda petik tunggal.",
      "Opsi B salah karena SQL standar case-insensitive untuk keyword dan nama tabel.",
      "Opsi C salah karena WHERE adalah klausa filter yang tepat.",
      "Opsi D salah karena operator kesetaraan SQL adalah tunggal '=', bukan '=='.",
      code="SELECT * FROM users WHERE name = \"Andi\"; -- Syntax error di standar SQL")

add_q(25, "beginner", "PostgreSQL/MySQL", "best-practice",
      "Mengapa sebaiknya menghindari `SELECT *` dan menyebutkan kolom secara eksplisit (`SELECT id, name`) pada aplikasi backend produksi?",
      {"A": "Mengurangi bandwidth jaringan, menghemat memori server, dan menjaga kode tetap stabil saat ada perubahan skema kolom di database",
       "B": "SELECT * selalu ditolak oleh database PostgreSQL",
       "C": "SELECT * membuat query otomatis rollback",
       "D": "Agar query menjadi lebih lambat"},
      "A",
      "Menyebutkan kolom secara spesifik mencegah transfer data yang tidak perlu (seperti kolom teks panjang atau blob) dan memungkinkan database memanfaatkan Index-Only Scan.",
      "Opsi A benar karena mengoptimalkan efisiensi I/O dan stabilitas kontrak data.",
      "Opsi B salah karena SELECT * legal di SQL.",
      "Opsi C salah karena SELECT tidak memicu rollback.",
      "Opsi D salah karena tujuannya justru mempercepat performa.")

add_q(26, "beginner", "REST API & HTTP", "concept",
      "Metode HTTP manakah yang secara semantik digunakan untuk membuat resource baru di server?",
      {"A": "POST", "B": "GET", "C": "PUT", "D": "DELETE"},
      "A",
      "Metode HTTP `POST` dirancang untuk mengirimkan payload data baru ke server guna membuat entitas/resource baru di database.",
      "Opsi A benar karena POST adalah metode standar pembuatan resource REST.",
      "Opsi B salah karena GET untuk membaca data.",
      "Opsi C salah karena PUT untuk menggantikan resource secara keseluruhan.",
      "Opsi D salah karena DELETE untuk menghapus resource.")

add_q(27, "beginner", "REST API & HTTP", "output",
      "Status code HTTP berapakah yang secara standar dikembalikan oleh server jika resource yang diminta oleh klien tidak ditemukan?",
      {"A": "404 Not Found", "B": "200 OK", "C": "500 Internal Server Error", "D": "401 Unauthorized"},
      "A",
      "HTTP 404 Not Found menandakan bahwa server tidak dapat menemukan resource yang cocok dengan Request-URI yang dikirimkan.",
      "Opsi A benar karena 404 adalah standar ketiadaan resource.",
      "Opsi B salah karena 200 adalah respon sukses.",
      "Opsi C salah karena 500 adalah crash internal server.",
      "Opsi D salah karena 401 adalah ketiadaan autentikasi login.")

add_q(28, "beginner", "REST API & HTTP", "completion",
      "Lengkapi header HTTP berikut untuk memberitahu server bahwa klien mengirimkan data berformat JSON:",
      {"A": "Content-Type: application/json", "B": "Accept: text/plain", "C": "Type: json", "D": "Data-Format: json"},
      "A",
      "Header `Content-Type: application/json` adalah header standar MIME type untuk mendefinisikan format payload JSON.",
      "Opsi A benar sesuai standar HTTP header Content-Type.",
      "Opsi B salah karena Accept adalah format yang diharapkan klien pada respon.",
      "Opsi C salah karena bukan header standar.",
      "Opsi D salah karena bukan header resmi.")

add_q(29, "beginner", "Git & SDLC", "concept",
      "Perintah Git manakah yang digunakan untuk membuat repositori Git baru di direktori lokal saat ini?",
      {"A": "git init", "B": "git start", "C": "git create", "D": "git new"},
      "A",
      "`git init` menginisialisasi repositori Git baru dengan membuat folder tersembunyi `.git` yang berisi seluruh struktur database version control.",
      "Opsi A benar karena git init adalah perintah inisialisasi repositori resmi.",
      "Opsi B salah karena bukan perintah Git.",
      "Opsi C salah karena bukan perintah Git.",
      "Opsi D salah karena bukan perintah resmi Git.")

add_q(30, "beginner", "GIS Dasar", "concept",
      "Dalam format standar GeoJSON, urutan koordinat untuk sebuah titik (Point) adalah:",
      {"A": "[Longitude, Latitude] (Bujur lalu Lintang)",
       "B": "[Latitude, Longitude] (Lintang lalu Bujur)",
       "C": "[Altitude, Latitude]",
       "D": "[North, South]"},
      "A",
      "Spesifikasi RFC 7946 GeoJSON menetapkan urutan koordinat sebagai `[x, y]` yaitu `[longitude, latitude]`.",
      "Opsi A benar karena spesifikasi GeoJSON mewajibkan urutan Longitude lalu Latitude.",
      "Opsi B salah karena urutan Lintang lalu Bujur adalah format Leaflet UI, bukan GeoJSON murni.",
      "Opsi C salah karena altitude berada di posisi ketiga.",
      "Opsi D salah karena bukan notasi koordinat GeoJSON.")

print("Part 1 FT: 30 beginner test questions written")

# -------------------------------------------------------------
# 2. INTERMEDIATE TEST QUESTIONS (FT-031 to FT-080: 50 questions)
# -------------------------------------------------------------
add_q(31, "intermediate", "TypeScript", "concept",
      "Apa fungsi dari utility type `Partial<T>` pada TypeScript?",
      {"A": "Mengubah seluruh properti dari tipe T menjadi bersifat opsional",
       "B": "Menghapus properti yang bernilai null",
       "C": "Mengambil sebagian properti acak",
       "D": "Mengubah properti menjadi readonly"},
      "A",
      "`Partial<T>` memetakan semua properti tipe T dan menambahkan modifier optional `?:`.",
      "Opsi A benar karena Partial menjadikan semua properti opsional.",
      "Opsi B salah karena tidak membuang nilai null.",
      "Opsi C salah karena bukan pemilihan acak.",
      "Opsi D salah karena bukan pengubah readonly.",
      code="type UserUpdate = Partial<User>;")

add_q(32, "intermediate", "TypeScript", "output",
      "Perhatikan kode berikut. Properti apa saja yang ada pada tipe `UserSummary` yang dibuat dengan `Pick`?",
      {"A": "Hanya 'id' dan 'name'", "B": "Hanya 'email'", "C": "Semua properti User", "D": "Tidak ada"},
      "A",
      "`Pick<T, K>` mengkonstruksi tipe dengan hanya memilih kumpulan kunci K dari tipe T.",
      "Opsi A benar karena Pick hanya memilih field 'id' dan 'name'.",
      "Opsi B salah karena email diabaikan.",
      "Opsi C salah karena bukan tipe penuh.",
      "Opsi D salah karena tipe memiliki 2 properti.",
      code="interface User {\n  id: number;\n  name: string;\n  email: string;\n}\ntype UserSummary = Pick<User, 'id' | 'name'>;")

add_q(33, "intermediate", "TypeScript", "completion",
      "Lengkapi utility type berikut untuk membuang properti 'password' dari tipe User:",
      {"A": "type SafeUser = Omit<User, 'password'>;",
       "B": "type SafeUser = Exclude<User, 'password'>;",
       "C": "type SafeUser = Remove<User, 'password'>;",
       "D": "type SafeUser = Drop<User, 'password'>;"},
      "A",
      "`Omit<T, K>` digunakan untuk membuang properti K dari suatu tipe objek T.",
      "Opsi A benar karena Omit membuang properti objek yang ditentukan.",
      "Opsi B salah karena Exclude untuk union types, bukan tipe objek.",
      "Opsi C salah karena bukan utility type bawaan.",
      "Opsi D salah karena bukan utility type resmi.",
      code="interface User {\n  id: number;\n  password: string;\n}\ntype SafeUser = ___;")

add_q(34, "intermediate", "TypeScript", "debug",
      "Fungsi generic berikut menghasilkan error: 'Property length does not exist on type T'. Bagaimana cara menambahkan generic constraint agar T wajib memiliki properti length?",
      {"A": "function getLength<T extends { length: number }>(item: T): number",
       "B": "function getLength<T: { length: number }>(item: T): number",
       "C": "function getLength<T implements HasLength>(item: T): number",
       "D": "function getLength(item: any): number"},
      "A",
      "Generic constraint `T extends { length: number }` membatasi argumen agar harus memiliki properti `length` bertipe number.",
      "Opsi A benar karena `extends` adalah sintaks constraint generic di TypeScript.",
      "Opsi B salah karena titik dua bukan sintaks generic constraint.",
      "Opsi C salah karena implements untuk class.",
      "Opsi D salah karena any menghilangkan type safety.",
      code="function getLength<T>(item: T): number {\n  return item.length; // Error\n}")

add_q(35, "intermediate", "TypeScript", "best-practice",
      "Mengapa Discriminated Unions (Tagged Unions) sangat dianjurkan untuk pemodelan response API (Success vs Error) di TypeScript?",
      {"A": "Memberikan penanda (literal discriminator) yang memungkinkan compiler mempersempit tipe data secara otomatis di blok if/switch tanpa type casting manual",
       "B": "Mengurangi pemakaian memori RAM browser",
       "C": "Menghapus kebutuhan async/await",
       "D": "Membuat kode berjalan lebih cepat di browser"},
      "A",
      "Discriminated Unions menggunakan properti pembeda literal (seperti `status: 'success' | 'error'`) yang memicu automatic type narrowing di TypeScript.",
      "Opsi A benar karena discriminated unions menyediakan type narrowing yang elegan dan aman.",
      "Opsi B salah karena tidak memengaruhi alokasi RAM.",
      "Opsi C salah karena tidak berhubungan dengan asinkronisitas.",
      "Opsi D salah karena tipe dihilangkan saat runtime.",
      code="type ApiResponse =\n  | { status: 'success'; data: User }\n  | { status: 'error'; message: string };")

add_q(36, "intermediate", "React + TypeScript", "concept",
      "Apa fungsi utama dari hook `useCallback` di React?",
      {"A": "Meng-cache definisi referensi fungsi di antara siklus render agar referensinya tidak berubah kecuali dependensinya berubah",
       "B": "Menjalankan fungsi callback di background thread",
       "C": "Menyimpan data di localStorage",
       "D": "Mengubah fungsi synchronous menjadi asynchronous"},
      "A",
      "`useCallback(fn, deps)` mengembalikan fungsi ter-memoize untuk mencegah re-render komponen anak yang dioptimasi dengan `React.memo`.",
      "Opsi A benar sesuai tujuan utama memoization referensi fungsi useCallback.",
      "Opsi B salah karena tidak membuat background thread.",
      "Opsi C salah karena tidak terhubung ke localStorage.",
      "Opsi D salah karena bukan pengubah sifat async.")

add_q(37, "intermediate", "React + TypeScript", "output",
      "Berapa nilai `doubled` yang dihasilkan oleh `useMemo` berikut jika `count` bernilai 5?",
      {"A": "10", "B": "5", "C": "25", "D": "0"},
      "A",
      "`useMemo(() => count * 2, [count])` menghitung nilai kalkulasi: 5 * 2 = 10 dan menyimpannya di cache sampai `count` berubah.",
      "Opsi A benar karena 5 * 2 = 10.",
      "Opsi B salah karena tidak dikalikan 2.",
      "Opsi C salah karena bukan operasi kuadrat.",
      "Opsi D salah karena kalkulasi menghasilkan angka 10.",
      code="const doubled = useMemo(() => count * 2, [count]);")

add_q(38, "intermediate", "React + TypeScript", "completion",
      "Lengkapi tipe generic `useRef` berikut untuk menyimpan referensi ke elemen input teks HTML:",
      {"A": "const inputRef = useRef<HTMLInputElement>(null);",
       "B": "const inputRef = useRef<HTMLElement>(null);",
       "C": "const inputRef = useRef<InputType>(null);",
       "D": "const inputRef = useRef<string>(null);"},
      "A",
      "`HTMLInputElement` adalah antarmuka DOM spesifik untuk elemen `<input />`.",
      "Opsi A benar karena HTMLInputElement menyediakan autocompletion properti elemen input seperti `.focus()` dan `.value`.",
      "Opsi B salah karena HTMLElement terlalu umum.",
      "Opsi C salah karena InputType bukan antarmuka DOM standar.",
      "Opsi D salah karena ref elemen DOM bukan string primitif.",
      code="const inputRef = ___;\nreturn <input ref={inputRef} />;")

add_q(39, "intermediate", "React + TypeScript", "debug",
      "Komponen berikut mengalami bug stale state pada timer: nilai count yang dicetak selalu 0. Bagaimana cara memperbaikinya?",
      {"A": "Gunakan functional updater: `setCount(prev => prev + 1)` di dalam interval callback",
       "B": "Ubah state count menjadi variabel global",
       "C": "Hapus fungsi cleanup",
       "D": "Ganti setInterval dengan requestAnimationFrame"},
      "A",
      "Closure timer menangkap snapshot `count = 0`. Menggunakan functional updater `setCount(prev => prev + 1)` memastikan update selalu menerima nilai state terbaru.",
      "Opsi A benar karena functional updater memecahkan masalah stale closure.",
      "Opsi B salah karena variabel global merusak isolasi komponen.",
      "Opsi C salah karena ketiadaan cleanup menimbulkan memory leak.",
      "Opsi D salah karena requestAnimationFrame bukan pengganti interval detik.",
      code="useEffect(() => {\n  const id = setInterval(() => {\n    setCount(count + 1); // Stale state\n  }, 1000);\n  return () => clearInterval(id);\n}, []);")

add_q(40, "intermediate", "React + TypeScript", "best-practice",
      "Bagaimana cara terbaik mengonsumsi React Context agar aman dari nilai `null` saat di luar Provider?",
      {"A": "Membuat Custom Hook pembungkus yang memvalidasi `if (!context) throw new Error(...)` sebelum me-return context",
       "B": "Melakukan type assertion `as ContextType` tanpa validasi",
       "C": "Mengembalikan objek kosong `{}` jika null",
       "D": "Menggunakan tipe `any` pada context"},
      "A",
      "Guard clause di dalam custom hook (misal `useAuth`) menjamin nilai return selalu non-null dan memberikan error informatif jika Provider lupa dipasang.",
      "Opsi A benar karena menjamin type safety non-null dan dokumentasi error yang jelas.",
      "Opsi B salah karena type assertion menyamarkan potensi runtime error.",
      "Opsi C salah karena fallback objek kosong dapat memicu undefined property access.",
      "Opsi D salah karena any mematikan type checking.")

add_q(41, "intermediate", "Java Spring Boot", "concept",
      "Apa perilaku default transaksi `@Transactional` di Spring Boot jika terjadi Checked Exception?",
      {"A": "Secara default TIDAK rollback; transaksi hanya auto-rollback untuk Unchecked Exception (RuntimeException / Error)",
       "B": "Transaksi selalu otomatis rollback untuk semua Exception",
       "C": "Transaksi langsung melempar error kompilasi",
       "D": "Transaksi tidak pernah rollback sama sekali"},
      "A",
      "Spring Transaction Manager secara default hanya membatalkan transaksi untuk unchecked exceptions (`RuntimeException` dan `Error`). Checked exception membutuhkan `rollbackFor = Exception.class`.",
      "Opsi A benar karena menjelaskan perilaku selektif rollback default Spring.",
      "Opsi B salah karena Checked Exception tidak memicu auto-rollback default.",
      "Opsi C salah karena bukan kesalahan waktu kompilasi.",
      "Opsi D salah karena unchecked exception memicu rollback.",
      code="@Transactional(rollbackFor = Exception.class)\npublic void updateData() throws IOException { ... }")

add_q(42, "intermediate", "Java Spring Boot", "output",
      "Apa output dari eksekusi Stream Java berikut saat menyaring angka genap dan mengalikannya dengan 2?",
      {"A": "12", "B": "6", "C": "10", "D": "20"},
      "A",
      "Angka genap dari [1, 2, 3, 4] adalah [2, 4]. Dikalikan 2 menjadi [4, 8]. Jumlahnya = 4 + 8 = 12.",
      "Opsi A benar karena 4 + 8 = 12.",
      "Opsi B salah karena penjumlahan tanpa pengali adalah 6.",
      "Opsi C salah karena bukan jumlah total.",
      "Opsi D salah karena bukan 20.",
      code="List<Integer> list = List.of(1, 2, 3, 4);\nint sum = list.stream().filter(n -> n % 2 == 0).mapToInt(n -> n * 2).sum();\nSystem.out.println(sum);")

add_q(43, "intermediate", "Java Spring Boot", "completion",
      "Lengkapi anotasi pada method repository berikut agar Spring Data JPA mengizinkan query UPDATE atau DELETE kustom:",
      {"A": "@Modifying", "B": "@Mutate", "C": "@DmlQuery", "D": "@Executable"},
      "A",
      "Anotasi `@Modifying` menginstruksikan Spring Data JPA untuk mengeksekusi query melalui `executeUpdate()` alih-alih `executeQuery()`.",
      "Opsi A benar karena @Modifying adalah anotasi wajib untuk DML query kustom.",
      "Opsi B salah karena bukan anotasi Spring.",
      "Opsi C salah karena bukan anotasi resmi.",
      "Opsi D salah karena bukan anotasi Spring Data.",
      code="@___\n@Transactional\n@Query(\"UPDATE User u SET u.active = false WHERE u.lastLogin < :date\")\nint deactivateOldUsers(@Param(\"date\") LocalDateTime date);")

add_q(44, "intermediate", "Java Spring Boot", "debug",
      "Method controller melempar error: 'MethodArgumentNotValidException' saat payload tidak valid, tetapi tidak ada respon JSON yang rapi ke klien. Bagaimana cara menanganinya secara terpusat?",
      {"A": "Membuat kelas `@RestControllerAdvice` dengan method `@ExceptionHandler(MethodArgumentNotValidException.class)`",
       "B": "Menghapus anotasi @Valid dari controller",
       "C": "Mengubah DTO menjadi HashMap",
       "D": "Menangkap exception di setiap baris service"},
      "A",
      "`@RestControllerAdvice` menangani exception validasi secara terpusat dan mengembalikan format error JSON yang seragam (seperti field mana yang error dan pesannya).",
      "Opsi A benar karena @RestControllerAdvice adalah penanganan error terpusat standar.",
      "Opsi B salah karena menghapus @Valid akan meloloskan data korup ke database.",
      "Opsi C salah karena HashMap tidak memiliki validasi terstruktur.",
      "Opsi D salah karena duplikasi try-catch menyalahi Clean Code.")

add_q(45, "intermediate", "Java Spring Boot", "best-practice",
      "Mengapa anotasi `@ConfigurationProperties` lebih direkomendasikan daripada menyematkan banyak `@Value` untuk membaca konfigurasi aplikasi yang hierarkis?",
      {"A": "Menyediakan binding konfigurasi yang terstruktur, type-safe, mendukung validasi JSR-380, dan memudahkan autocompletion di IDE",
       "B": "Menghapus kebutuhan file application.properties",
       "C": "Membuat aplikasi otomatis berjalan di HTTPS",
       "D": "@Value sudah dihapus di Spring Boot 3"},
      "A",
      "`@ConfigurationProperties` mengelompokkan konfigurasi terkait ke dalam satu class POJO yang type-safe, mencegah typo nama properti.",
      "Opsi A benar karena @ConfigurationProperties meningkatkan keteraturan dan type safety konfigurasi.",
      "Opsi B salah karena file konfigurasi tetap digunakan sebagai sumber data.",
      "Opsi C salah karena tidak mengontrol SSL secara otomatis.",
      "Opsi D salah karena @Value masih tersedia untuk injeksi nilai tunggal sederhana.",
      code="@ConfigurationProperties(prefix = \"app.security\")\npublic record SecurityConfig(String jwtSecret, long expiration) {}")

add_q(46, "intermediate", "JPA & Hibernate", "concept",
      "Apa solusi paling efektif di JPQL untuk memecahkan masalah N+1 Select Problem pada relasi `@ManyToOne` atau `@OneToMany`?",
      {"A": "Menggunakan klausa `JOIN FETCH` pada query JPQL",
       "B": "Mengubah semua fetch mode menjadi EAGER secara permanen",
       "C": "Menghapus relasi dari entitas",
       "D": "Menonaktifkan database cache"},
      "A",
      "`JOIN FETCH` menginstruksikan Hibernate untuk mengambil entitas induk dan koleksi/entitas relasinya dalam satu query SQL JOIN tunggal.",
      "Opsi A benar karena JOIN FETCH mengeliminasi query tambahan N+1 secara efisien.",
      "Opsi B salah karena EAGER global justru memicu pemborosan memori.",
      "Opsi C salah karena relasi data dibutuhkan oleh model domain.",
      "Opsi D salah karena bukan masalah cache.",
      code="SELECT u FROM User u JOIN FETCH u.orders WHERE u.active = true")

add_q(47, "intermediate", "JPA & Hibernate", "output",
      "Berapa jumlah query SQL yang dieksekusi oleh Hibernate pada pemanggilan kedua jika entitas sudah berada di L1 Cache?",
      {"A": "0 query (diambil dari First-Level Cache)", "B": "1 query", "C": "2 query", "D": "Error"},
      "A",
      "First-Level Cache (Persistence Context) menyimpan instance entitas selama transaksi aktif. Pemanggilan kedua dengan ID yang sama dilayani dari memori tanpa SQL.",
      "Opsi A benar karena L1 cache hit meniadakan eksekusi query ke database.",
      "Opsi B salah karena tidak ada query kedua yang dikirim.",
      "Opsi C salah karena Hibernate tidak melakukan query berulang untuk entitas terkelola.",
      "Opsi D salah karena operasi cache hit berjalan normal.",
      code="User u1 = userRepo.findById(1L).get(); // Query 1\nUser u2 = userRepo.findById(1L).get(); // Query ke-2?")

add_q(48, "intermediate", "JPA & Hibernate", "completion",
      "Lengkapi anotasi pada field enum status berikut agar disimpan sebagai teks string di kolom database:",
      {"A": "@Enumerated(EnumType.STRING)", "B": "@Enumerated(EnumType.ORDINAL)", "C": "@EnumText", "D": "@StringEnum"},
      "A",
      "`EnumType.STRING` menyimpan nama literal enum (seperti 'ACTIVE') alih-alih angka indeks, menjaga konsistensi data jika urutan enum berubah.",
      "Opsi A benar karena EnumType.STRING adalah pemetaan teks aman di JPA.",
      "Opsi B salah karena ORDINAL menyimpan indeks angka yang rentan rusak.",
      "Opsi C salah karena bukan anotasi JPA.",
      "Opsi D salah karena bukan anotasi resmi.",
      code="@___\nprivate UserStatus status;")

add_q(49, "intermediate", "JPA & Hibernate", "debug",
      "Aplikasi melempar `LazyInitializationException` saat mengakses relasi `user.getOrders()` di layer Controller. Apa penyebabnya?",
      {"A": "Hibernate Session/EntityManager sudah ditutup saat transaksi service berakhir sebelum koleksi LAZY diakses",
       "B": "Relasi orders tidak memiliki anotasi @OneToMany",
       "C": "Tabel orders kosong",
       "D": "User tidak memiliki ID"},
      "A",
      "Proxy koleksi LAZY hanya dapat dimuat saat sesi transaksi Hibernate masih terbuka. Solusinya: fetch data di service menggunakan DTO atau `JOIN FETCH`.",
      "Opsi A benar karena akses proxy di luar transaksi aktif memicu LazyInitializationException.",
      "Opsi B salah karena mapping ada.",
      "Opsi C salah karena tabel kosong menghasilkan list kosong, bukan exception.",
      "Opsi D salah karena bukan masalah identifier entitas.")

add_q(50, "intermediate", "JPA & Hibernate", "best-practice",
      "Mengapa atribut `orphanRemoval = true` sangat berguna pada relasi `@OneToMany`?",
      {"A": "Menghapus baris anak secara otomatis dari database ketika objek anak tersebut dihapus dari koleksi list di parent entity",
       "B": "Menghapus seluruh database saat parent dihapus",
       "C": "Membuat tabel anak menjadi read-only",
       "D": "Menghapus koneksi database"},
      "A",
      "`orphanRemoval = true` memastikan bahwa memutuskan hubungan objek anak dari parent (`orders.remove(order)`) akan otomatis menghapus record anak dari tabel database.",
      "Opsi A benar karena orphanRemoval membersihkan baris yatim piatu secara otomatis.",
      "Opsi B salah karena hanya menghapus entitas anak terkait.",
      "Opsi C salah karena bukan proteksi read-only.",
      "Opsi D salah karena tidak mematikan koneksi pool.",
      code="@OneToMany(mappedBy = \"user\", cascade = CascadeType.ALL, orphanRemoval = true)\nprivate List<Address> addresses = new ArrayList<>();")

add_q(51, "intermediate", "PostgreSQL/MySQL", "concept",
      "Apa jenis JOIN di SQL yang mengembalikan semua baris dari tabel kiri, dan baris yang cocok dari tabel kanan (atau NULL jika tidak ada kecocokan)?",
      {"A": "LEFT JOIN (LEFT OUTER JOIN)", "B": "INNER JOIN", "C": "RIGHT JOIN", "D": "CROSS JOIN"},
      "A",
      "`LEFT JOIN` menjamin seluruh baris dari tabel kiri selalu tampil dalam hasil query, dengan nilai NULL pada kolom tabel kanan jika tidak ditemukan kecocokan relasi.",
      "Opsi A benar karena mendefinisikan perilaku resmi LEFT JOIN.",
      "Opsi B salah karena INNER JOIN membuang baris yang tidak memiliki kecocokan di kedua tabel.",
      "Opsi C salah karena RIGHT JOIN mempertahankan tabel kanan.",
      "Opsi D salah karena CROSS JOIN menghasilkan perkalian kartesian.")

add_q(52, "intermediate", "PostgreSQL/MySQL", "output",
      "Berapa jumlah baris yang dihasilkan dari query `SELECT DISTINCT status FROM orders;` jika tabel berisi 100 pesanan dengan status 'PENDING', 'PAID', dan 'CANCELLED'?",
      {"A": "3 baris", "B": "100 baris", "C": "1 baris", "D": "0 baris"},
      "A",
      "`DISTINCT` mengeliminasi baris duplikat, hanya mengembalikan variasi nilai unik yang ada (yaitu 3 nilai unik: PENDING, PAID, CANCELLED).",
      "Opsi A benar karena ada 3 nilai status unik.",
      "Opsi B salah karena duplikasi disaring oleh DISTINCT.",
      "Opsi C salah karena ada 3 kategori status.",
      "Opsi D salah karena ada data di tabel.",
      code="SELECT DISTINCT status FROM orders;")

add_q(53, "intermediate", "PostgreSQL/MySQL", "completion",
      "Lengkapi klausa SQL berikut untuk mengelompokkan baris berdasarkan departemen dan memfilter hanya departemen dengan total karyawan lebih dari 5:",
      {"A": "GROUP BY department HAVING COUNT(*) > 5",
       "B": "GROUP BY department WHERE COUNT(*) > 5",
       "C": "ORDER BY department HAVING COUNT(*) > 5",
       "D": "PARTITION BY department WHERE COUNT(*) > 5"},
      "A",
      "Klausa `HAVING` digunakan khusus untuk memfilter hasil agregasi setelah baris dikelompokkan oleh `GROUP BY`.",
      "Opsi A benar karena kombinasi GROUP BY dan HAVING adalah standar SQL untuk agregasi bersyarat.",
      "Opsi B salah karena WHERE tidak dapat mengevaluasi fungsi agregasi secara langsung.",
      "Opsi C salah karena ORDER BY untuk pengurutan.",
      "Opsi D salah karena PARTITION BY adalah klausa window function.")

add_q(54, "intermediate", "PostgreSQL/MySQL", "debug",
      "Query pencarian berikut sangat lambat: `SELECT * FROM users WHERE phone = NULL;` dan tidak mengembalikan hasil apa pun. Apa perbaikannya?",
      {"A": "Ganti operator `= NULL` dengan `IS NULL`",
       "B": "Ganti NULL dengan 0",
       "C": "Ganti SELECT dengan UPDATE",
       "D": "Tambahkan tanda petik pada phone"},
      "A",
      "Di SQL, nilai `NULL` tidak dapat dibandingkan dengan operator kesetaraan `=`. Pemeriksaan nilai null wajib menggunakan operator `IS NULL`.",
      "Opsi A benar karena IS NULL adalah sintaks resmi pengecekan ketiadaan nilai di SQL.",
      "Opsi B salah karena 0 adalah nilai angka, bukan NULL.",
      "Opsi C salah karena query bertujuan membaca data.",
      "Opsi D salah karena identifier kolom tidak memerlukan tanda petik tunggal.",
      code="SELECT * FROM users WHERE phone IS NULL;")

add_q(55, "intermediate", "PostgreSQL/MySQL", "best-practice",
      "Bagaimana aturan 'Leftmost Prefix' bekerja pada Composite Index `(col_a, col_b, col_c)`?",
      {"A": "Indeks hanya digunakan oleh query jika kondisi filter menyertakan `col_a`, atau `(col_a, col_b)`, atau `(col_a, col_b, col_c)`; query yang hanya memfilter `col_b` tidak bisa memakai indeks ini",
       "B": "Indeks bisa digunakan secara acak pada kolom mana saja",
       "C": "Indeks hanya bisa dipakai untuk pengurutan descending",
       "D": "Indeks otomatis membagi tabel menjadi 3 bagian"},
      "A",
      "B-Tree multi-kolom diurutkan berdasarkan kolom pertama dari kiri ke kanan. Melewati kolom paling kiri (`col_a`) mencegah database menggunakan struktur pohon indeks.",
      "Opsi A benar sesuai aturan resmi Leftmost Prefixing pada B-Tree Composite Index.",
      "Opsi B salah karena struktur hierarki B-Tree membutuhkan prefix paling kiri.",
      "Opsi C salah karena mendukung pengurutan ASC maupun DESC.",
      "Opsi D salah karena bukan partisi tabel fisik.",
      code="CREATE INDEX idx_user_search ON users(city, age, name);")

add_q(56, "intermediate", "REST API & HTTP", "concept",
      "Apa perbedaan utama antara status code HTTP 401 Unauthorized dan 403 Forbidden?",
      {"A": "401 mengindikasikan masalah autentikasi (klien belum login atau token invalid), sedangkan 403 mengindikasikan otorisasi (klien terotentikasi tetapi tidak punya izin akses)",
       "B": "401 untuk error server, 403 untuk error browser",
       "C": "401 untuk HTTP, 403 untuk HTTPS",
       "D": "Keduanya persis sama"},
      "A",
      "401 menuntut autentikasi ulang (Unauthenticated). 403 menolak akses terlepas dari siapa penggunanya karena role tidak memadai (Unauthorized/Forbidden).",
      "Opsi A benar karena membedakan autentikasi identitas (401) vs otorisasi hak akses (403).",
      "Opsi B salah karena keduanya adalah client error 4xx.",
      "Opsi C salah karena tidak terikat protokol TLS.",
      "Opsi D salah karena maknanya berbeda.")

add_q(57, "intermediate", "REST API & HTTP", "output",
      "Klien mengirim request HTTP DELETE ke `/api/items/10` dan server berhasil menghapusnya tanpa mengembalikan payload body. Status code apa yang dikembalikan?",
      {"A": "204 No Content", "B": "200 OK", "C": "404 Not Found", "D": "201 Created"},
      "A",
      "HTTP 204 No Content adalah status code standar yang menandakan operasi pemrosesan sukses dan server sengaja tidak menyertakan response body.",
      "Opsi A benar karena 204 No Content adalah respon standar operasi DELETE tanpa payload balikan.",
      "Opsi B salah jika server tidak mengirimkan body.",
      "Opsi C salah karena penghapusan berhasil.",
      "Opsi D salah karena 201 untuk creation.")

add_q(58, "intermediate", "REST API & HTTP", "completion",
      "Lengkapi format skema otentikasi header HTTP Authorization saat membawa token JWT:",
      {"A": "Authorization: Bearer <token>", "B": "Authorization: Basic <token>", "C": "Authorization: Token <token>", "D": "Authorization: JWT <token>"},
      "A",
      "Format standar OAuth 2.0 / RFC 6750 untuk bearer token adalah `Authorization: Bearer <token>`.",
      "Opsi A benar karena skema Bearer adalah standar resmi JWT.",
      "Opsi B salah karena Basic untuk username:password ter-encode base64.",
      "Opsi C salah karena Token bukan skema standar RFC.",
      "Opsi D salah karena bukan nama skema otentikasi resmi.")

add_q(59, "intermediate", "REST API & HTTP", "debug",
      "Permintaan AJAX dari browser diblokir dengan error CORS saat mengakses endpoint POST dengan JSON body. Metode HTTP apakah yang dikirim browser pada tahap Preflight?",
      {"A": "OPTIONS", "B": "GET", "C": "HEAD", "D": "PUT"},
      "A",
      "Browser mengirim preflight request menggunakan metode HTTP `OPTIONS` untuk memverifikasi izin header dan origin sebelum request aktual dikirimkan.",
      "Opsi A benar karena OPTIONS adalah metode resmi preflight CORS.",
      "Opsi B salah karena GET bukan metode preflight.",
      "Opsi C salah karena bukan request verifikasi CORS.",
      "Opsi D salah karena PUT adalah operasi update data.")

add_q(60, "intermediate", "REST API & HTTP", "best-practice",
      "Mengapa metode HTTP GET harus selalu bersifat 'Safe' dan 'Idempotent'?",
      {"A": "Agar web crawler atau browser prefetching dapat membaca resource secara bebas tanpa khawatir memicu perubahan data atau efek samping yang merusak di server",
       "B": "Agar kecepatan kompresi meningkat",
       "C": "Karena GET tidak mendukung parameter query",
       "D": "Karena GET hanya bisa dijalankan satu kali per hari"},
      "A",
      "Metode safe tidak memodifikasi data. Idempotent berarti pemanggilan berulang tidak mengubah state akhir, memungkinkan caching dan perayapan aman oleh mesin pencari.",
      "Opsi A benar karena keamanan semantik GET melindungi integritas data dari crawler dan prefetching.",
      "Opsi B salah karena tidak terkait algoritma kompresi.",
      "Opsi C salah karena GET mendukung query parameters.",
      "Opsi D salah karena tidak ada batasan waktu pemanggilan.")

add_q(61, "intermediate", "Git & SDLC", "concept",
      "Perintah Git manakah yang digunakan untuk mengaplikasikan satu commit spesifik dari branch lain ke branch aktif saat ini?",
      {"A": "git cherry-pick <commit-hash>", "B": "git merge --single <hash>", "C": "git copy <hash>", "D": "git graft <hash>"},
      "A",
      "`git cherry-pick` menyalin perubahan dari commit terpilih dan menerapkannya sebagai commit baru di branch yang sedang aktif.",
      "Opsi A benar karena cherry-pick adalah perintah resmi pengambilan commit tunggal.",
      "Opsi B salah karena bukan opsi git merge.",
      "Opsi C salah karena git copy bukan perintah bawaan.",
      "Opsi D salah karena bukan perintah standar Git.")

add_q(62, "intermediate", "Git & SDLC", "completion",
      "Lengkapi perintah Git berikut untuk membatalkan commit terakhir tetapi tetap mempertahankan seluruh perubahan kode di Staging Area:",
      {"A": "git reset --soft HEAD~1", "B": "git reset --hard HEAD~1", "C": "git revert HEAD", "D": "git checkout HEAD~1"},
      "A",
      "`--soft` hanya memundurkan pointer commit HEAD tanpa memodifikasi Index (Staging Area) maupun file kerja di disk.",
      "Opsi A benar karena git reset --soft mempertahankan perubahan di Staging Area.",
      "Opsi B salah karena --hard menghapus seluruh perubahan dari disk.",
      "Opsi C salah karena git revert membuat commit pembalik baru.",
      "Opsi D salah karena checkout berpindah commit (detached HEAD).")

add_q(63, "intermediate", "Git & SDLC", "best-practice",
      "Mengapa melakukan `git rebase` pada branch bersama (shared/public branch seperti main) dianggap sebagai praktik berbahaya?",
      {"A": "Rebase menulis ulang riwayat commit (rewrites history) yang menyebabkan konflik parah dan commit duplikat bagi developer lain yang bercabang dari branch tersebut",
       "B": "Rebase menghapus akun GitHub",
       "C": "Rebase memformat harddisk",
       "D": "Rebase dilarang oleh terminal Linux"},
      "A",
      "Aturan Emas Rebase: Jangan pernah me-rebase branch publik yang digunakan bersama oleh anggota tim lain karena mengubah hash commit yang sudah disinkronkan.",
      "Opsi A benar karena penulisan ulang history mengacaukan sinkronisasi anggota tim.",
      "Opsi B salah karena tidak memengaruhi akun remote.",
      "Opsi C salah karena bukan operasi disk format.",
      "Opsi D salah karena perintah git rebase sepenuhnya legal di shell.")

add_q(64, "intermediate", "GIS Dasar", "concept",
      "Fungsi PostGIS manakah yang digunakan untuk mengonversi geometri database ke dalam string format GeoJSON?",
      {"A": "ST_AsGeoJSON(geom)", "B": "ST_ToGeoJSON(geom)", "C": "ST_MakeGeoJSON(geom)", "D": "ST_ParseJSON(geom)"},
      "A",
      "`ST_AsGeoJSON(geometry geom)` mengonversi objek geometri PostGIS menjadi format representasi teks GeoJSON.",
      "Opsi A benar karena ST_AsGeoJSON adalah nama fungsi resmi PostGIS.",
      "Opsi B salah karena bukan fungsi PostGIS.",
      "Opsi C salah karena bukan fungsi resmi.",
      "Opsi D salah karena bukan fungsi PostGIS.",
      code="SELECT id, name, ST_AsGeoJSON(geom) as geojson FROM locations;")

add_q(65, "intermediate", "GIS Dasar", "completion",
      "Lengkapi inisialisasi peta Leaflet.js berikut agar mengatur koordinat pusat pada latitude -6.2 dan longitude 106.8 dengan zoom level 12:",
      {"A": "map.setView([-6.2, 106.8], 12);", "B": "map.setCenter([106.8, -6.2], 12);", "C": "map.panTo([12, -6.2, 106.8]);", "D": "map.locate([-6.2, 106.8]);"},
      "A",
      "`setView([lat, lng], zoom)` adalah method resmi Leaflet untuk menentukan posisi tampilan dan tingkat perbesaran peta.",
      "Opsi A benar karena setView menerima pasangan koordinat [lat, lng] dan level zoom.",
      "Opsi B salah karena urutan koordinat dan nama method bukan standar Leaflet.",
      "Opsi C salah karena panTo tidak mengatur zoom level.",
      "Opsi D salah karena locate untuk geolocation browser.")

add_q(66, "intermediate", "TypeScript", "concept",
      "Apa fungsi dari utility type `Record<K, T>` di TypeScript?",
      {"A": "Membangun tipe objek dengan kumpulan properti bertipe K yang nilainya bertipe T",
       "B": "Merekam log konsol",
       "C": "Menyimpan data di audio recorder",
       "D": "Membuat tabel database baru"},
      "A",
      "`Record<K, T>` adalah mapped type resmi untuk membuat kamus (dictionary/map) tipe dengan key K dan value T.",
      "Opsi A benar sesuai fungsi dan definisi Record<K, T>.",
      "Opsi B salah karena bukan perekam log.",
      "Opsi C salah karena bukan perekam audio.",
      "Opsi D salah karena bukan DDL database.",
      code="type PageNav = Record<'home' | 'about' | 'contact', { title: string; url: string }>;")

add_q(67, "intermediate", "React + TypeScript", "output",
      "Perhatikan kode berikut. Berapa kali string 'Running' dicetak jika komponen re-render karena perubahan `otherVal`?",
      {"A": "0 kali (hanya berjalan jika `userId` berubah)", "B": "1 kali", "C": "2 kali", "D": "Error"},
      "A",
      "Karena dependency array `useEffect` hanya memantau `[userId]`, perubahan pada state `otherVal` tidak akan memicu eksekusi ulang callback efek tersebut.",
      "Opsi A benar karena efek diisolasi ke perubahan userId.",
      "Opsi B salah karena efek tidak dijalankan ulang jika dependensinya tidak berubah.",
      "Opsi C salah karena tidak ada eksekusi ganda.",
      "Opsi D salah karena kode valid.",
      code="useEffect(() => {\n  console.log('Running');\n}, [userId]);")

add_q(68, "intermediate", "Java Spring Boot", "debug",
      "Aplikasi gagal menemukan bean saat startup: 'No qualifying bean of type EmailService available: expected single matching bean but found 2: SmtpEmailService, SendgridEmailService'. Anotasi apa yang dapat digunakan pada titik injeksi untuk memilih salah satu bean secara spesifik?",
      {"A": "@Qualifier(\"smtpEmailService\")", "B": "@Choose(\"smtpEmailService\")", "C": "@Select(\"smtpEmailService\")", "D": "@SingleBean"},
      "A",
      "`@Qualifier(\"beanName\")` digunakan bersama `@Autowired` untuk mengeliminasi ambiguitas ketika ada beberapa kandidat bean dengan antarmuka yang sama.",
      "Opsi A benar karena @Qualifier adalah anotasi resmi Spring untuk pemilihan bean spesifik.",
      "Opsi B salah karena bukan anotasi Spring.",
      "Opsi C salah karena bukan anotasi IoC.",
      "Opsi D salah karena bukan anotasi resmi.",
      code="public UserController(@Qualifier(\"smtpEmailService\") EmailService emailService) { ... }")

add_q(69, "intermediate", "PostgreSQL/MySQL", "output",
      "Apa hasil dari query `SELECT COALESCE(NULL, NULL, 'Default', 'Other');`?",
      {"A": "\"Default\"", "B": "NULL", "C": "\"Other\"", "D": "Error"},
      "A",
      "`COALESCE` mengembalikan nilai non-null pertama dari daftar argumen yang diberikan (yaitu 'Default').",
      "Opsi A benar karena 'Default' adalah ekspresi non-null pertama.",
      "Opsi B salah karena ada nilai non-null.",
      "Opsi C salah karena 'Other' berada setelah 'Default'.",
      "Opsi D salah karena sintaks SQL valid.",
      code="SELECT COALESCE(NULL, NULL, 'Default', 'Other');")

add_q(70, "intermediate", "REST API & HTTP", "concept",
      "Apa arti dari sifat 'Stateless' pada arsitektur REST?",
      {"A": "Server tidak menyimpan konteks sesi klien di antara request; setiap request wajib memuat seluruh informasi yang diperlukan untuk memprosesnya",
       "B": "Server tidak memiliki database",
       "C": "Aplikasi tidak memiliki negara asal",
       "D": "Aplikasi tidak bisa menyimpan file"},
      "A",
      "Prinsip Statelessness memastikan setiap request bersifat mandiri, memungkinkan penskalaan horizontal server secara bebas tanpa session affinity.",
      "Opsi A benar sesuai definisi formal arsitektur REST Statelessness.",
      "Opsi B salah karena database persistensi tetap digunakan.",
      "Opsi C salah karena bukan konteks geografis.",
      "Opsi D salah karena penyimpanan file didukung.")

add_q(71, "intermediate", "TypeScript", "completion",
      "Lengkapi tipe generic utility berikut untuk mengekstrak return type dari sebuah fungsi:",
      {"A": "type Result = ReturnType<typeof myFunction>;",
       "B": "type Result = ResultType<typeof myFunction>;",
       "C": "type Result = OutputOf<typeof myFunction>;",
       "D": "type Result = FunctionReturn<myFunction>;"},
      "A",
      "`ReturnType<T>` mengekstrak tipe nilai kembalian dari suatu tipe fungsi T.",
      "Opsi A benar karena ReturnType adalah utility type resmi TypeScript.",
      "Opsi B salah karena bukan utility type bawaan.",
      "Opsi C salah karena bukan utility type bawaan.",
      "Opsi D salah karena bukan utility type resmi.",
      code="function getUser() { return { id: 1, name: 'Budi' }; }\ntype UserResult = ___;")

add_q(72, "intermediate", "React + TypeScript", "concept",
      "Apa perbedaan mendasar antara `useMemo` dan `useCallback` di React?",
      {"A": "useMemo meng-cache nilai hasil eksekusi fungsi, sedangkan useCallback meng-cache definisi instance fungsi itu sendiri",
       "B": "useMemo hanya untuk string, useCallback untuk angka",
       "C": "useCallback berjalan di server, useMemo di client",
       "D": "Keduanya persis sama tanpa perbedaan"},
      "A",
      "`useMemo(() => compute(), [deps])` meng-cache nilai kalkulasi, sedangkan `useCallback(fn, [deps])` meng-cache fungsi itu sendiri.",
      "Opsi A benar karena membedakan nilai hasil komputasi vs referensi fungsi.",
      "Opsi B salah karena keduanya mendukung semua tipe data.",
      "Opsi C salah karena keduanya adalah hook React client.",
      "Opsi D salah karena kegunaannya berbeda.")

add_q(73, "intermediate", "Java Spring Boot", "output",
      "Apa output dari pemanggilan `.isPresent()` pada `Optional.of(\"Data\")`?",
      {"A": "true", "B": "false", "C": "null", "D": "Exception"},
      "A",
      "`Optional.of(\"Data\")` membungkus nilai non-null, sehingga method `.isPresent()` bernilai true.",
      "Opsi A benar karena objek Optional memiliki isi nilai valid.",
      "Opsi B salah karena Optional tidak kosong.",
      "Opsi C salah karena kembaliannya berupa boolean primitif.",
      "Opsi D salah karena evaluasi aman tanpa error.",
      code="Optional<String> opt = Optional.of(\"Data\");\nSystem.out.println(opt.isPresent());")

add_q(74, "intermediate", "JPA & Hibernate", "concept",
      "Apa fungsi dari anotasi `@Version` pada entitas JPA?",
      {"A": "Mengaktifkan Optimistic Locking untuk mendeteksi pembaruan bersamaan yang saling bertabrakan (Lost Updates)",
       "B": "Mencatat nomor versi compiler Java",
       "C": "Mengatur versi database PostgreSQL",
       "D": "Menghapus entitas lama otomatis"},
      "A",
      "`@Version` memeriksa nomor versi entitas saat UPDATE. Jika nomor versi di database berbeda dengan memori, dilemparkan `OptimisticLockException`.",
      "Opsi A benar sesuai fungsi proteksi Optimistic Locking JPA.",
      "Opsi B salah karena bukan nomor rilis compiler.",
      "Opsi C salah karena bukan versi RDBMS.",
      "Opsi D salah karena bukan pembersih entitas.")

add_q(75, "intermediate", "PostgreSQL/MySQL", "best-practice",
      "Kapan sebaiknya membuat Partial Index di PostgreSQL (`WHERE active = true`)?",
      {"A": "Ketika sebagian besar query dalam sistem hanya menyaring subset baris tertentu (misal data aktif), menghemat ukuran indeks dan mempercepat pencarian",
       "B": "Ketika tabel memiliki kurang dari 5 baris",
       "C": "Hanya untuk kolom numerik",
       "D": "Tidak pernah disarankan"},
      "A",
      "Partial Index menghemat ruang memori dan disk secara signifikan dengan hanya mengindeks baris yang memenuhi kondisi klausul WHERE.",
      "Opsi A benar karena Partial Index sangat optimal untuk query subset data.",
      "Opsi B salah karena tabel sangat kecil tidak membutuhkan partial index.",
      "Opsi C salah karena didukung pada semua tipe data.",
      "Opsi D salah karena ini adalah fitur optimasi unggulan PostgreSQL.",
      code="CREATE INDEX idx_active_orders ON orders(created_at) WHERE status = 'ACTIVE';")

add_q(76, "intermediate", "REST API & HTTP", "debug",
      "Klien menerima error HTTP 405 Method Not Allowed saat mengirim HTTP POST ke `/api/users`. Apa penyebabnya?",
      {"A": "Endpoint tersebut hanya menerima metode HTTP lain (misal hanya di-mapping dengan `@GetMapping`), dan tidak mendukung metode POST",
       "B": "Server sedang offline",
       "C": "Database penuh",
       "D": "Koneksi internet lambat"},
      "A",
      "HTTP 405 terjadi ketika metode HTTP yang dikirim klien tidak diizinkan atau tidak di-mapping oleh resource URL tersebut.",
      "Opsi A benar karena endpoint menolak metode HTTP yang tidak didukung.",
      "Opsi B salah karena server merespon dengan status code HTTP sah.",
      "Opsi C salah karena bukan error kapasitas penyimpanan.",
      "Opsi D salah karena bukan masalah bandwidth.")

add_q(77, "intermediate", "Git & SDLC", "output",
      "Apa yang dilakukan oleh perintah `git stash pop`?",
      {"A": "Menerapkan perubahan kode yang terakhir disimpan di stash ke working directory sekaligus menghapusnya dari stack stash",
       "B": "Menghapus semua perubahan tanpa menerapkannya",
       "C": "Membuat commit baru ke remote",
       "D": "Menghapus repositori lokal"},
      "A",
      "`git stash pop` mengembalikan perubahan dari puncak stack stash ke working tree dan langsung membuangnya dari daftar stash jika berhasil.",
      "Opsi A benar sesuai fungsionalitas git stash pop.",
      "Opsi B salah karena itu adalah perilaku git stash drop.",
      "Opsi C salah karena stash pop tidak membuat commit.",
      "Opsi D salah karena tidak menghapus repositori.")

add_q(78, "intermediate", "GIS Dasar", "concept",
      "Fungsi PostGIS manakah yang digunakan untuk memeriksa apakah dua geometri beririsan atau bertumpukan secara spasial?",
      {"A": "ST_Intersects(geom1, geom2)", "B": "ST_Touch(geom1, geom2)", "C": "ST_Over(geom1, geom2)", "D": "ST_Cross(geom1, geom2)"},
      "A",
      "`ST_Intersects(g1, g2)` mengembalikan true jika dua geometri berbagi ruang spasial apa pun (beririsan/tumpang tindih).",
      "Opsi A benar karena ST_Intersects adalah fungsi standar irisan spasial OGC.",
      "Opsi B salah karena ST_Touches hanya untuk persentuhan batas luar.",
      "Opsi C salah karena bukan fungsi resmi.",
      "Opsi D salah karena ST_Crosses memiliki kondisi dimensi yang berbeda.")

add_q(79, "intermediate", "TypeScript", "output",
      "Apa hasil dari operator kesetaraan nilai string literal enum di TypeScript?",
      {"A": "true", "B": "false", "C": "undefined", "D": "Error"},
      "A",
      "Nilai dari `Role.ADMIN` bernilai `'ADMIN'`, sehingga perbandingan `'ADMIN' === Role.ADMIN` bernilai true.",
      "Opsi A benar karena string enum bernilai teks string literalnya.",
      "Opsi B salah karena nilainya sama.",
      "Opsi C salah karena terdefinisi.",
      "Opsi D salah karena perbandingan valid.",
      code="enum Role { ADMIN = 'ADMIN' }\nconsole.log(Role.ADMIN === 'ADMIN');")

add_q(80, "intermediate", "React + TypeScript", "completion",
      "Lengkapi hook React Router v6 berikut untuk membaca parameter dinamis `id` dari URL:",
      {"A": "const { id } = useParams<{ id: string }>();",
       "B": "const { id } = useRoute();",
       "C": "const { id } = useQuery();",
       "D": "const id = getUrlParam('id');"},
      "A",
      "`useParams` adalah hook React Router v6 untuk membaca path variable dari rute aktif.",
      "Opsi A benar karena useParams adalah hook resmi pembaca parameter URL rute.",
      "Opsi B salah karena useRoute bukan hook React Router v6.",
      "Opsi C salah karena useQuery bukan hook bawaan React Router.",
      "Opsi D salah karena bukan hook React.")

print("Part 2 FT: 80 total test questions written (30 beginner + 50 intermediate)")

# -------------------------------------------------------------
# 3. ADVANCED TEST QUESTIONS (FT-081 to FT-100: 20 questions)
# -------------------------------------------------------------
add_q(81, "advanced", "TypeScript", "concept",
      "Apa fungsi utama dari keyword `infer` dalam Conditional Types TypeScript?",
      {"A": "Mendeduksi dan menangkap variabel tipe baru secara dinamis dari dalam tipe lain selama evaluasi pola conditional type",
       "B": "Menonaktifkan type checking",
       "C": "Mengubah fungsi menjadi asinkron",
       "D": "Memaksa compiler mengabaikan linting"},
      "A",
      "Keyword `infer` mendeklarasikan variabel tipe yang diekstrak dari dalam pola tipe pada klausul `extends` conditional types.",
      "Opsi A benar sesuai fungsi deduksi tipe dinamis keyword infer.",
      "Opsi B salah karena infer bukan untuk mematikan type checking.",
      "Opsi C salah karena tidak mengubah fungsionalitas runtime.",
      "Opsi D salah karena infer adalah fitur sistem tipe bahasa.")

add_q(82, "advanced", "TypeScript", "output",
      "Apa tipe hasil evaluasi dari conditional type berikut?",
      {"A": "\"string\"", "B": "\"other\"", "C": "never", "D": "any"},
      "A",
      "`'hello' extends string` bernilai true, sehingga conditional type mengevaluasi cabang pertama yaitu literal `'string'`.",
      "Opsi A benar karena 'hello' adalah subtipe dari string.",
      "Opsi B salah karena kondisi extends bernilai true.",
      "Opsi C salah karena cabang evaluasi terpenuhi.",
      "Opsi D salah karena tipe menghasilkan literal spesifik.",
      code="type Check<T> = T extends string ? 'string' : 'other';\ntype Result = Check<'hello'>;")

add_q(83, "advanced", "TypeScript", "completion",
      "Lengkapi template literal type berikut agar menerima string yang diawali kata 'handle' diikuti huruf kapital:",
      {"A": "type HandlerName = `handle${Capitalize<string>}`;",
       "B": "type HandlerName = `handle${Uppercase<string>}`;",
       "C": "type HandlerName = 'handle' + Capitalize;",
       "D": "type HandlerName = `handle${string}`;"},
      "A",
      "Intrinsic string utility `Capitalize<T>` mengubah huruf pertama string menjadi huruf kapital.",
      "Opsi A benar karena `Capitalize` hanya mengkapitalkan huruf pertama.",
      "Opsi B salah karena Uppercase membuat semua huruf menjadi kapital.",
      "Opsi C salah karena tanda tambah bukan sintaks template literal type.",
      "Opsi D salah karena tidak menjamin huruf kapital pada karakter pertama.")

add_q(84, "advanced", "React + TypeScript", "concept",
      "Apa peran utama dari hook `useTransition` yang diperkenalkan pada React 18?",
      {"A": "Menandai pembaruan state tertentu sebagai transisi prioritas rendah yang dapat disela agar antarmuka pengguna tetap responsif",
       "B": "Mengatur animasi transisi CSS",
       "C": "Mengatur navigasi rute halaman",
       "D": "Mengurangi pemakaian memori"},
      "A",
      "`useTransition` memisahkan pembaruan state penting (urgent) dari transisi berprioritas rendah (non-urgent) yang dapat ditunda atau dibatalkan jika ada input baru.",
      "Opsi A benar sesuai tujuan Concurrent React useTransition.",
      "Opsi B salah karena bukan engine CSS.",
      "Opsi C salah karena bukan router navigasi.",
      "Opsi D salah karena bukan pengurang memori.")

add_q(85, "advanced", "React + TypeScript", "output",
      "Kapan nilai `deferredValue` dari `useDeferredValue` diperbarui oleh React?",
      {"A": "Setelah render prioritas tinggi selesai dan browser berada dalam kondisi idle, menunda pembaruan nilai",
       "B": "Tepat 5 detik kemudian",
       "C": "Secara instan bersamaan dengan state asli",
       "D": "Hanya saat tombol ditekan"},
      "A",
      "`useDeferredValue` menunda propagasi pembaruan nilai ke siklus render berikutnya saat thread idle.",
      "Opsi A benar karena pembaruan ditunda agar interaksi utama tidak tersendat.",
      "Opsi B salah karena bukan timer detik statis.",
      "Opsi C salah karena sifatnya tertunda.",
      "Opsi D salah karena tidak bergantung pada tombol.")

add_q(86, "advanced", "React + TypeScript", "debug",
      "Sebuah custom hook `useDebounce` tidak pernah memperbarui nilai karena dependency array `useEffect` kosong `[]`. Apa solusinya?",
      {"A": "Masukkan parameter `[value, delay]` ke dalam array dependensi useEffect",
       "B": "Hapus hook useState",
       "C": "Ganti setTimeout dengan setInterval",
       "D": "Ubah hook menjadi class component"},
      "A",
      "Agar efek debounce di-reset setiap kali input berubah, dependensi `value` dan `delay` harus disertakan di dependency array.",
      "Opsi A benar karena dependensi memicu reset timer pada setiap perubahan input.",
      "Opsi B salah karena state dibutuhkan untuk menyimpan nilai ter-debounce.",
      "Opsi C salah karena setInterval mengulang secara berkala tanpa henti.",
      "Opsi D salah karena functional components mendukung custom hooks.")

add_q(87, "advanced", "Java Spring Boot", "concept",
      "Dalam Spring AOP, Advice jenis apakah yang membungkus method target dan dapat mengontrol apakah method target dieksekusi atau tidak via `ProceedingJoinPoint`?",
      {"A": "@Around", "B": "@Before", "C": "@After", "D": "@AfterThrowing"},
      "A",
      "`@Around` advice mengontrol eksekusi method target secara penuh melalui pemanggilan `joinPoint.proceed()`.",
      "Opsi A benar karena @Around memiliki kontrol penuh atas pemanggilan join point.",
      "Opsi B salah karena @Before hanya berjalan sebelum eksekusi.",
      "Opsi C salah karena @After berjalan setelah selesai.",
      "Opsi D salah karena @AfterThrowing hanya aktif saat terjadi exception.")

add_q(88, "advanced", "Java Spring Boot", "output",
      "Jika method transactional dengan `Propagation.REQUIRES_NEW` berhasil commit, lalu transaksi pemanggilnya melempar exception dan rollback, apakah perubahan method REQUIRES_NEW ikut dibatalkan?",
      {"A": "TIDAK dibatalkan (tetap tersimpan permanen karena berjalan di transaksi fisik terpisah yang sudah di-commit)",
       "B": "Ikut dibatalkan",
       "C": "Database terkunci",
       "D": "Error crash"},
      "A",
      "`REQUIRES_NEW` mengisolasi transaksi fisik baru yang commit secara independen, tidak terpengaruh oleh rollback transaksi induk.",
      "Opsi A benar karena transaksi REQUIRES_NEW terisolasi penuh.",
      "Opsi B salah karena transaksi yang sudah di-commit tidak dapat di-rollback oleh transaksi lain.",
      "Opsi C salah karena lock dilepas saat commit.",
      "Opsi D salah karena operasi berjalan normal.")

add_q(89, "advanced", "Java Spring Boot", "completion",
      "Lengkapi anotasi event listener berikut agar aksi hanya dijalankan setelah transaksi database berhasil di-commit secara penuh:",
      {"A": "@TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)",
       "B": "@EventListener(onCommit = true)",
       "C": "@CommitEventListener",
       "D": "@AfterCommitListener"},
      "A",
      "`@TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)` memastikan efek samping hanya dieksekusi jika commit transaksi sukses.",
      "Opsi A benar karena TransactionPhase.AFTER_COMMIT adalah konfigurasi resmi Spring.",
      "Opsi B salah bukan atribut @EventListener biasa.",
      "Opsi C salah bukan anotasi Spring.",
      "Opsi D salah bukan anotasi resmi.")

add_q(90, "advanced", "Java Spring Boot", "best-practice",
      "Mengapa pada pemanggilan method `@Async` di Spring Boot produksi disarankan menggunakan kustom `ThreadPoolTaskExecutor`?",
      {"A": "Mencegah pembuatan thread tanpa batas yang dapat menghabiskan memori server dan memicu OutOfMemoryError",
       "B": "Karena Spring Boot melarang @Async",
       "C": "Agar thread berjalan di frontend",
       "D": "Untuk menonaktifkan database"},
      "A",
      "Kustom ThreadPoolTaskExecutor membatasi core pool, max pool, dan queue capacity, melindungi stabilitas sistem di bawah beban tinggi.",
      "Opsi A benar karena membatasi pemakaian thread OS dan mencegah kehabisan memori.",
      "Opsi B salah karena @Async sepenuhnya didukung.",
      "Opsi C salah karena thread JVM berjalan di backend.",
      "Opsi D salah karena tidak terkait koneksi database.")

add_q(91, "advanced", "JPA & Hibernate", "concept",
      "Apa perbedaan utama antara First-Level Cache (L1) dan Second-Level Cache (L2) di Hibernate?",
      {"A": "L1 Cache ber-scope per EntityManager/Session transaksi tunggal, sedangkan L2 Cache ber-scope SessionFactory aplikasi dan dibagikan lintas sesi",
       "B": "L1 di database, L2 di browser",
       "C": "L1 berbayar, L2 gratis",
       "D": "Keduanya persis sama"},
      "A",
      "First-level cache adalah in-memory session cache default. Second-level cache adalah shared application/cluster cache lintas transaksi.",
      "Opsi A benar karena membedakan session-scope vs application/cluster-scope cache.",
      "Opsi B salah karena keduanya di layer backend ORM.",
      "Opsi C salah karena fitur open-source bawaan.",
      "Opsi D salah karena cakupan lifecyle-nya berbeda total.")

add_q(92, "advanced", "JPA & Hibernate", "output",
      "Klausa SQL apakah yang otomatis disematkan oleh dialek Hibernate di ujung query saat menggunakan `LockModeType.PESSIMISTIC_WRITE`?",
      {"A": "FOR UPDATE", "B": "LOCK TABLE", "C": "READ ONLY", "D": "NO WAIT"},
      "A",
      "`PESSIMISTIC_WRITE` diterjemahkan menjadi klausa native `SELECT ... FOR UPDATE` yang mengunci baris data di level database fisik.",
      "Opsi A benar karena FOR UPDATE adalah padanan SQL native dari PESSIMISTIC_WRITE.",
      "Opsi B salah karena mengunci baris, bukan seluruh tabel.",
      "Opsi C salah karena bukan query read-only.",
      "Opsi D salah karena default-nya adalah menunggu lock.")

add_q(93, "advanced", "PostgreSQL/MySQL", "concept",
      "Apa fungsi utama dari Window Functions di SQL dengan klausa `OVER (PARTITION BY ...)`?",
      {"A": "Melakukan kalkulasi dan pemeringkatan pada partisi baris data tanpa meremukkan (collapse) baris individual menjadi satu baris seperti GROUP BY",
       "B": "Membuka jendela baru di web browser",
       "C": "Menghapus data di background",
       "D": "Membuat tabel cadangan"},
      "A",
      "Window Functions mengevaluasi agregasi/ranking pada jendela partisi tanpa menghilangkan identitas tiap baris data asli.",
      "Opsi A benar karena mempertahankan baris individual dalam perhitungan partisi.",
      "Opsi B salah karena bukan GUI browser.",
      "Opsi C salah karena bukan operasi penghapusan.",
      "Opsi D salah karena bukan pencadangan database.")

add_q(94, "advanced", "PostgreSQL/MySQL", "output",
      "Diberikan nilai skor: 100, 90, 90, 80. Berapakah urutan ranking yang dihasilkan oleh fungsi `DENSE_RANK() OVER (ORDER BY score DESC)`?",
      {"A": "1, 2, 2, 3", "B": "1, 2, 2, 4", "C": "1, 2, 3, 4", "D": "1, 1, 2, 3"},
      "A",
      "`DENSE_RANK()` memberikan ranking yang sama untuk nilai kembar tanpa melompati nomor urut berikutnya: 1, 2, 2, 3.",
      "Opsi A benar karena DENSE_RANK tidak menyisakan gap nomor ranking.",
      "Opsi B salah karena 1, 2, 2, 4 adalah hasil fungsi RANK() biasa.",
      "Opsi C salah karena nilai kembar mendapat rank sama.",
      "Opsi D salah karena nilai tertinggi mendapat rank 1.")

add_q(95, "advanced", "PostgreSQL/MySQL", "best-practice",
      "Perintah apakah yang digunakan untuk memperbarui data pada Materialized View di PostgreSQL secara online tanpa memblokir (locking) query SELECT pengguna?",
      {"A": "REFRESH MATERIALIZED VIEW CONCURRENTLY view_name;",
       "B": "REFRESH MATERIALIZED VIEW view_name;",
       "C": "DROP MATERIALIZED VIEW view_name;",
       "D": "VACUUM ANALYZE view_name;"},
      "A",
      "`REFRESH MATERIALIZED VIEW CONCURRENTLY` memperbarui view tanpa memberlakukan exclusive read-lock (memerlukan Unique Index pada view).",
      "Opsi A benar karena flag CONCURRENTLY mencegah penguncian pembacaan data.",
      "Opsi B salah karena refresh standar memberlakukan exclusive lock.",
      "Opsi C salah karena drop view memicu downtime.",
      "Opsi D salah karena VACUUM bukan perintah refresh data.")

add_q(96, "advanced", "REST API & HTTP", "concept",
      "Mengapa ekstensi PKCE diwajibkan dalam alur OAuth 2.0 untuk aplikasi frontend SPA dan Mobile?",
      {"A": "Karena SPA/mobile tidak dapat menyimpan client_secret secara aman di kode sumber, dan PKCE mencegah intersepsi authorization code via code_verifier dinamis",
       "B": "PKCE mempercepat koneksi internet",
       "C": "PKCE menonaktifkan token JWT",
       "D": "PKCE mempublikasikan password pengguna"},
      "A",
      "PKCE (Proof Key for Code Exchange) melindungi Public Client dari pencurian authorization code tanpa membutuhkan client_secret statis.",
      "Opsi A benar karena PKCE adalah standar mutlak keamanan Public Client OAuth2.",
      "Opsi B salah karena tidak terkait kecepatan jaringan.",
      "Opsi C salah karena token tetap digunakan.",
      "Opsi D salah karena PKCE memperketat proteksi kredensial.")

add_q(97, "advanced", "REST API & HTTP", "completion",
      "Lengkapi header HTTP standar yang digunakan pada API transaksi finansial untuk menjamin idempotensi eksekusi:",
      {"A": "Idempotency-Key: <uuid>", "B": "Safe-Token: true", "C": "No-Retry: yes", "D": "Single-Exec: 1"},
      "A",
      "`Idempotency-Key` adalah header de facto standar industri untuk mencegah eksekusi transaksi ganda pada request retry.",
      "Opsi A benar karena Idempotency-Key adalah standar industri proteksi double billing.",
      "Opsi B salah karena bukan header standar.",
      "Opsi C salah karena bukan header resmi.",
      "Opsi D salah karena bukan header standar.")

add_q(98, "advanced", "Git & SDLC", "concept",
      "Alat bawaan Git apakah yang menggunakan algoritma pencarian biner (Binary Search) untuk menemukan commit spesifik yang memperkenalkan bug/regresi?",
      {"A": "git bisect", "B": "git search", "C": "git debug", "D": "git trace"},
      "A",
      "`git bisect` membagi riwayat commit secara biner di antara commit baik (good) dan buruk (bad) untuk melacak regresi secara otomatis.",
      "Opsi A benar karena git bisect adalah tool binary search commit bawaan Git.",
      "Opsi B salah karena bukan perintah Git.",
      "Opsi C salah karena bukan perintah Git.",
      "Opsi D salah karena bukan perintah Git.")

add_q(99, "advanced", "Git & SDLC", "output",
      "Apa fungsi utama dari mekanisme Git `reflog` dalam situasi darurat?",
      {"A": "Mencatat riwayat pemindahan pointer HEAD lokal, memungkinkan pemulihan commit yang hilang setelah `git reset --hard`",
       "B": "Menghapus riwayat commit",
       "C": "Mengubah password repository",
       "D": "Mengompresi gambar di repositori"},
      "A",
      "`git reflog` menyimpan log seluruh perubahan HEAD lokal, memungkinkan recovery commit terlepas (orphaned/dangling commits).",
      "Opsi A benar karena reflog adalah jaring pengaman pemulihan commit lokal.",
      "Opsi B salah karena reflog tidak menghapus history.",
      "Opsi C salah karena bukan pengubah password.",
      "Opsi D salah karena bukan pengompres gambar.")

add_q(100, "advanced", "GIS Dasar", "completion",
      "Lengkapi query spatial join PostGIS berikut untuk memfilter geometri yang berada dalam radius jarak 1.000 meter menggunakan tipe geography:",
      {"A": "ST_DWithin(f.geom::geography, ST_MakePoint(106.8, -6.2)::geography, 1000)",
       "B": "ST_Distance(f.geom, 1000)",
       "C": "ST_Radius(f.geom, 1000)",
       "D": "ST_Near(f.geom, 1000)"},
      "A",
      "`ST_DWithin(geog1, geog2, distance_in_meters)` menggunakan indeks spasial untuk memfilter geometri dalam radius jarak meter di atas spheroid bumi secara efisien.",
      "Opsi A benar karena ST_DWithin geography mengukur jarak dalam satuan meter menggunakan indeks GiST.",
      "Opsi B salah karena ST_Distance tidak memfilter secara efisien dengan indeks bounding box.",
      "Opsi C salah karena bukan fungsi PostGIS.",
      "Opsi D salah karena bukan fungsi PostGIS.")

print(f"Total test questions generated: {len(questions)}")

# Write to fullstackTestQuestions.ts
output_path = "fullstackTestQuestions.ts"
content = "import type { Question } from './types';\n\nexport const FULLSTACK_TEST_QUESTIONS: Question[] = " + json.dumps(questions, indent=2, ensure_ascii=False) + ";\n"

with open(output_path, "w", encoding="utf-8") as f:
    f.write(content)

print(f"Successfully written to {output_path}")
